server:
	x86_64-w64-mingw32-gcc -O2 -Wall -o server.exe server.c sysinfo.c common.c -lws2_32 -lmswsock -ladvapi32
client:
	x86_64-w64-mingw32-gcc -O2 -Wall -o client.exe client.c common.c -lws2_32 -ladvapi32
