# adig
# Autogenerated from man page /usr/share/man/man1/adig.1.gz
complete -c adig -s c -d 'Sets the query class, defaults to IN.   May also be HS or CH'
complete -c adig -s h -d 'Prints the help'
complete -c adig -s p -d 'Sends query to a port other than 53'
complete -c adig -s q -d 'Specifies the domain name to query'
complete -c adig -s r -d 'Skip adigrc processing'
complete -c adig -s s -d 'Server (alias for @server syntax), compatibility with old cmdline'
complete -c adig -s t -d 'Indicates resource record type to query'
complete -c adig -s x -d 'Simplified reverse lookups'

