# afcclient
# Autogenerated from man page /usr/share/man/man1/afcclient.1.gz
complete -c afcclient -s u -l udid -d 'target specific device by UDID'
complete -c afcclient -s n -l network -d 'connect to network device (not recommended, since the connection might be ter…'
complete -c afcclient -l container -d 'Access the app container directory of the app with given \\f[B]appid\\f[]'
complete -c afcclient -l documents -d 'Access the Documents directory of the app with given \\f[B]appid\\f[]'
complete -c afcclient -s h -l help -d 'Prints usage information'
complete -c afcclient -s d -l debug -d 'Enable communication debugging'
complete -c afcclient -s v -l version -d 'Prints version information'

