# androiddump
# Autogenerated from man page /usr/share/man/man1/androiddump.1.gz
complete -c androiddump -l help
complete -c androiddump -l version
complete -c androiddump -l extcap-version
complete -c androiddump -l debug
complete -c androiddump -l extcap-interfaces
complete -c androiddump -l extcap-interface
complete -c androiddump -l extcap-dlts
complete -c androiddump -l extcap-config
complete -c androiddump -l extcap-capture-filter
complete -c androiddump -l capture
complete -c androiddump -l fifo
complete -c androiddump -l adb-server-ip
complete -c androiddump -l adb-server-tcp-port
complete -c androiddump -l logcat-text -d 'If TRUE then use text logcat rather then binary'
complete -c androiddump -l bt-server-tcp-port -d 'Use other than default Bluetooth server TCP port on Android side'
complete -c androiddump -l bt-forward-socket -d 'If TRUE then socket from Android side is forwarded to host side'
complete -c androiddump -l bt-local-ip
complete -c androiddump -l bt-local-tcp-port

