# aplaymidi2
# Autogenerated from man page /usr/share/man/man1/aplaymidi2.1.gz
complete -c aplaymidi2 -s h -l help -d 'Prints a list of options'
complete -c aplaymidi2 -s V -l version -d 'Prints the current version'
complete -c aplaymidi2 -s p -l port -d 'Sets the sequencer port(s) to which the events in the MIDI Clip file(s) are s…'
complete -c aplaymidi2 -s d -l delay -d 'Specifies how long to wait after the end of each MIDI Clip file, to allow the…'
complete -c aplaymidi2 -s s -l silent -d 'Don\'t show message texts'
complete -c aplaymidi2 -s a -l passall -d 'Pass all UMP packets as is'

