# arch-update
# Autogenerated from man page /usr/share/man/man1/arch-update.1.gz
complete -c arch-update -s l -l list -d 'Display the list of pending updates'
complete -c arch-update -s d -l devel -d 'Include AUR development packages updates'
complete -c arch-update -s n -l news -d 'Display latest Arch news'
complete -c arch-update -s s -l services -d 'Check for services requiring a post upgrade restart'
complete -c arch-update -s D -l debug -d 'Display debug traces'
complete -c arch-update -l gen-config -d 'Generate a default / example `arch-update'
complete -c arch-update -l show-config -d 'Display the content of the `arch-update'
complete -c arch-update -l edit-config -d 'Edit the `arch-update. conf` configuration file (if it exists)'
complete -c arch-update -l tray -d 'Start the Arch-Update systray applet'
complete -c arch-update -s V -l version -d 'Display version information'
complete -c arch-update -s h -l help -d 'Display the help message'

