# arch-chroot
# Autogenerated from man page /usr/share/man/man8/arch-chroot.8.gz
complete -c arch-chroot -s S -d 'Run in systemd mode'
complete -c arch-chroot -s N -d 'Run in unshare mode'
complete -c arch-chroot -s u -d 'Specify non-root user and optional group to use'
complete -c arch-chroot -s r -d 'Do not change the resolv. conf within the chroot'
complete -c arch-chroot -s h -d 'Output syntax and command line options'

