# arecordmidi2
# Autogenerated from man page /usr/share/man/man1/arecordmidi2.1.gz
complete -c arecordmidi2 -s h -l help -d 'Prints a list of options'
complete -c arecordmidi2 -s V -l version -d 'Prints the current version'
complete -c arecordmidi2 -s p -l port -d 'Sets the sequencer port(s) from which events are recorded'
complete -c arecordmidi2 -s b -l bpm -d 'Sets the musical tempo of the MIDI file, in beats per minute'
complete -c arecordmidi2 -s t -l ticks -d 'Sets the resolution of timestamps (ticks) in the MIDI file, in ticks per beat'
complete -c arecordmidi2 -s i -l timesig -d 'Sets the time signature for the MIDI file'
complete -c arecordmidi2 -s n -l num-events -d 'Stops the recording after receiving the given number of events'
complete -c arecordmidi2 -s u -l ump -d 'Sets the UMP MIDI protocol version.  Either 1 or 2 has to be given for MIDI 1'
complete -c arecordmidi2 -s r -l interactive -d 'Run in the interactive mode'
complete -c arecordmidi2 -s s -l silent -d 'Don\'t print messages to stdout'
complete -c arecordmidi2 -s P -l profile -d 'Read the UMP data from the given file and put them into the configuration sec…'
complete -c arecordmidi2 -l song -l clip -l copyright -l composer
complete -c arecordmidi2 -l lyricist -l arranger -l publisher
complete -c arecordmidi2 -l performer -l accompany -l date -l location -d 'Put the given meta data text in the configuration section'

