# aseqsend
# Autogenerated from man page /usr/share/man/man1/aseqsend.1.gz
complete -c aseqsend -s h -l help -d 'Prints a list of options'
complete -c aseqsend -s V -l version -d 'Prints the current version'
complete -c aseqsend -s l -l 'list\\FP' -d 'Prints a list of possible output ports'
complete -c aseqsend -s v -l verbose -d 'Prints number of bytes actually sent'
complete -c aseqsend -s p -l port -d 'Target port by number or name'
complete -c aseqsend -s s -l file -d 'Send raw binary data from given file name'
complete -c aseqsend -s i -l interval -d 'Interval between SysEx messages in milliseconds'
complete -c aseqsend -l listFP -d 'Prints a list of possible output ports'
complete -c aseqsend -s u -l ump -d 'Specify the MIDI version.  0 for the legacy MIDI 1'

