# aucat
# Autogenerated from man page /usr/share/man/man1/aucat.1.gz
complete -c aucat -s b -d 'The buffer size of the audio device in frames.  Default is 7680'
complete -c aucat -s c -d 'The audio file channels count.  The default is 2, i. e.  stereo'
complete -c aucat -s d -d 'Increase log verbosity'
complete -c aucat -s e -d 'Encoding of the audio file.  The default is s24'
complete -c aucat -s f -d 'Use this sndio 7 audio device'
complete -c aucat -s g -d 'Go to the given time position and start playback or recording there'
complete -c aucat -s h -d 'Audio file type'
complete -c aucat -s i -d 'Play this audio file'
complete -c aucat -s m -d 'Map the given range of source channels into the given range of destination ch…'
complete -c aucat -s n -d 'Off-line mode'
complete -c aucat -s o -d 'Record into this audio file'
complete -c aucat -s p -d 'Time offset where the beginning of the file belongs'
complete -c aucat -s q -d 'Control audio device properties through this MIDI port'
complete -c aucat -s r -d 'Sample rate in Hertz of the audio file.  The default is 48000'
complete -c aucat -s v -d 'Software volume attenuation of the file to play'

