# automake-1.18
# Autogenerated from man page /usr/share/man/man1/automake-1.18.1.gz
complete -c 'automake-1.18' -l help -d 'print this help, then exit'
complete -c 'automake-1.18' -l version -d 'print version number, then exit'
complete -c 'automake-1.18' -s v -l verbose -d 'verbosely list files processed'
complete -c 'automake-1.18' -l no-force -d 'only update Makefile. in\'s that are out of date'
complete -c 'automake-1.18' -s W -l warnings -d 'report the warnings falling in CATEGORY . SS "Dependency tracking:"'
complete -c 'automake-1.18' -s i -l ignore-deps -d 'disable dependency tracking code'
complete -c 'automake-1.18' -l include-deps -d 'enable dependency tracking code . SS "Flavors:"'
complete -c 'automake-1.18' -l foreign -d 'set strictness to foreign'
complete -c 'automake-1.18' -l gnits -d 'set strictness to gnits'
complete -c 'automake-1.18' -l gnu -d 'set strictness to gnu . SS "Library files:"'
complete -c 'automake-1.18' -s a -l add-missing -d 'add missing standard files to package'
complete -c 'automake-1.18' -l libdir -d 'set directory storing library files'
complete -c 'automake-1.18' -l print-libdir -d 'print directory storing library files'
complete -c 'automake-1.18' -s c -l copy -d 'with -a, copy missing files (default is symlink)'
complete -c 'automake-1.18' -s f -l force-missing -d 'force update of standard files . SS "Warning categories are:"'

