# axel
# Autogenerated from man page /usr/share/man/man1/axel.1.gz
complete -c axel -l max-speed -s s -d 'Specify a speed (bytes per second) to try to keep the average speed around th…'
complete -c axel -l num-connections -s n -d 'Specify an alternative number of connections'
complete -c axel -l max-redirect -d 'Specify an alternative number of redirections to follow when connecting to th…'
complete -c axel -l output -s o -d 'Downloaded data will be put in a local file with the same name, unless you sp…'
complete -c axel -l search -s S -d 'Axel can do a search for mirrors using the filesearching. com search engine'
complete -c axel -l ipv6 -s 6 -d 'Use the IPv6 protocol only when connecting to the host'
complete -c axel -l ipv4 -s 4 -d 'Use the IPv4 protocol only when connecting to the host'
complete -c axel -l no-proxy -s N -d 'Do not use any proxy server to download the file'
complete -c axel -l insecure -s k -d 'Do not verify the SSL certificate'
complete -c axel -l verbose -s v -d 'Show more status messages.  Use it more than once to see more details'
complete -c axel -l quiet -s q -d 'No output to stdout'
complete -c axel -l alternate -s a -d 'This will show an alternate progress indicator'
complete -c axel -l header -s H -d 'Add an additional HTTP header'
complete -c axel -l user-agent -s U -d 'Set the HTTP user agent to use'
complete -c axel -l help -s h -d 'A brief summary of all the options'
complete -c axel -l timeout -s T -d 'Set I/O and connection timeout'
complete -c axel -l no-clobber -s c
complete -c axel -l version -s V -d 'Get version information'

