# bear
# Autogenerated from man page /usr/share/man/man1/bear.1.gz
complete -c bear -s c -d 'Specify a configuration file path'
complete -c bear -s o -d 'Specify the output file path (default: compile_commands. json)'
complete -c bear -s a -d 'Append results to an existing output file instead of overwriting it'
complete -c bear -s h -d 'Print help information'
complete -c bear -s V -d 'Print version information'

