# bits
# Autogenerated from man page /usr/share/man/man1/bits.1.gz
complete -c bits -s w -l width
complete -c bits -s h -l help
complete -c bits -s V -l version
complete -c bits -s m -l mask
complete -c bits -s g -l grouped-mask
complete -c bits -s b -l binary
complete -c bits -s l -l list

