# bomtool
# Autogenerated from man page /usr/share/man/man1/bomtool.1.gz
complete -c bomtool -l about -d 'Print the version number, the Copyright notice, and the license of the bomtoo…'
complete -c bomtool -l version -d 'Print the version number of the bomtool program to standard output and exit'

