# bpftool-map
# Autogenerated from man page /usr/share/man/man8/bpftool-map.8.gz
complete -c bpftool-map -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool-map -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool-map -s j -l json -d 'Generate JSON output'
complete -c bpftool-map -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool-map -s d -l debug -d 'Print all logs available, even debug-level information'
complete -c bpftool-map -s f -l bpffs -d 'Show file names of pinned maps'
complete -c bpftool-map -s n -l nomount -d 'Do not automatically attempt to mount any virtual file system (such as tracef…'

