# bpftool-prog
# Autogenerated from man page /usr/share/man/man8/bpftool-prog.8.gz
complete -c bpftool-prog -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool-prog -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool-prog -s j -l json -d 'Generate JSON output'
complete -c bpftool-prog -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool-prog -s d -l debug -d 'Print all logs available, even debug-level information'
complete -c bpftool-prog -s f -l bpffs -d 'When showing BPF programs, show file names of pinned programs'
complete -c bpftool-prog -s m -l mapcompat -d 'Allow loading maps with unknown map definitions'
complete -c bpftool-prog -s n -l nomount -d 'Do not automatically attempt to mount any virtual file system (such as tracef…'
complete -c bpftool-prog -s L -l use-loader -d 'Load program as a "loader" program'
complete -c bpftool-prog -s S -l sign -d 'Enable signing of the BPF program before loading'
complete -c bpftool-prog -s k -d 'Path to the private key file in PEM format, required when signing'
complete -c bpftool-prog -s i -d 'Path to the X'
complete -c bpftool-prog -o rw------- -d '# bpftool prog dump jited tag 005a3d2123620c8b 0:   push   %rbp 1:   mov    %…'

