# bpftool-btf
# Autogenerated from man page /usr/share/man/man8/bpftool-btf.8.gz
complete -c bpftool-btf -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool-btf -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool-btf -s j -l json -d 'Generate JSON output'
complete -c bpftool-btf -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool-btf -s d -l debug -d 'Print all logs available, even debug-level information'
complete -c bpftool-btf -s B -l base-btf -d 'Pass a base BTF object'

