# bpftool-link
# Autogenerated from man page /usr/share/man/man8/bpftool-link.8.gz
complete -c bpftool-link -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool-link -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool-link -s j -l json -d 'Generate JSON output'
complete -c bpftool-link -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool-link -s d -l debug -d 'Print all logs available, even debug-level information'
complete -c bpftool-link -s f -l bpffs -d 'When showing BPF links, show file names of pinned links'
complete -c bpftool-link -s n -l nomount -d 'Do not automatically attempt to mount any virtual file system (such as tracef…'
complete -c bpftool-link -o rw------- -d 'SEE ALSO'

