# bpftool-cgroup
# Autogenerated from man page /usr/share/man/man8/bpftool-cgroup.8.gz
complete -c bpftool-cgroup -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool-cgroup -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool-cgroup -s j -l json -d 'Generate JSON output'
complete -c bpftool-cgroup -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool-cgroup -s d -l debug -d 'Print all logs available, even debug-level information'
complete -c bpftool-cgroup -s f -l bpffs -d 'Show file names of pinned programs'

