# bpftool
# Autogenerated from man page /usr/share/man/man8/bpftool.8.gz
complete -c bpftool -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool -s j -l json -d 'Generate JSON output'
complete -c bpftool -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool -s d -l debug -d 'Print all logs available, even debug-level information'
complete -c bpftool -s m -l mapcompat -d 'Allow loading maps with unknown map definitions'
complete -c bpftool -s n -l nomount -d 'Do not automatically attempt to mount any virtual file system (such as tracef…'

