# bpftool-net
# Autogenerated from man page /usr/share/man/man8/bpftool-net.8.gz
complete -c bpftool-net -s h -l help -d 'Print short help message (similar to bpftool help)'
complete -c bpftool-net -s V -l version -d 'Print bpftool\'s version number (similar to bpftool version), the number of th…'
complete -c bpftool-net -s j -l json -d 'Generate JSON output'
complete -c bpftool-net -s p -l pretty -d 'Generate human-readable JSON output.  Implies -j'
complete -c bpftool-net -s d -l debug -d 'Print all logs available, even debug-level information'

