# bpftrace
# Autogenerated from man page /usr/share/man/man8/bpftrace.8.gz
complete -c bpftrace -s B
complete -c bpftrace -s c
complete -c bpftrace -s d
complete -c bpftrace -l dry-run
complete -c bpftrace -s e
complete -c bpftrace -s f
complete -c bpftrace -s h -l help
complete -c bpftrace -s I
complete -c bpftrace -l include
complete -c bpftrace -l info
complete -c bpftrace -s k
complete -c bpftrace -s l
complete -c bpftrace -l no-feature
complete -c bpftrace -l no-warnings
complete -c bpftrace -s o
complete -c bpftrace -s p
complete -c bpftrace -s q
complete -c bpftrace -l unsafe
complete -c bpftrace -l usdt-file-activation
complete -c bpftrace -s V -l version
complete -c bpftrace -s v

