# btop
# Autogenerated from man page /usr/share/man/man1/btop.1.gz
complete -c btop -s c -l config -d 'Path to a config file'
complete -c btop -s d -l debug -d 'Start in debug mode with additional logs and metrics'
complete -c btop -s f -l filter -d 'Set an initial process filter'
complete -c btop -l force-utf -d 'Force start even if no UTF-8 locale was detected'
complete -c btop -s l -l low-color -d 'Disable true color, 256 colors only'
complete -c btop -s p -l preset -d 'Start with a preset (0-9)'
complete -c btop -s t -l tty -d 'Force tty mode with ANSI graph symbols and 16 colors only'
complete -c btop -l no-tty -d 'Force disable tty mode'
complete -c btop -l themes-dir -d 'Path to a custom themes directory'
complete -c btop -s u -l update -d 'Set an initial update rate in milliseconds'
complete -c btop -l default-config -d 'Print default config to standard output'
complete -c btop -s h -l help -d 'Show summary of options'
complete -c btop -s V -l version -d 'Show version of program'

