# btrfs-rescue
# Autogenerated from man page /usr/share/man/man8/btrfs-rescue.8.gz
complete -c btrfs-rescue -s y -d 'assume an answer of yes to all questions'
complete -c btrfs-rescue -s h -d help
complete -c btrfs-rescue -s v -d '(deprecated) alias for global -v option Note: Since chunk-recover will scan t…'
complete -c btrfs-rescue -s r -l readonly -d 'readonly mode, only scan for and report data checksum mismatches, do not repa…'
complete -c btrfs-rescue -s i -l interactive -d 'interactive mode, ask for how to repair, ignore the errors by default'
complete -c btrfs-rescue -s m -l mirror -d 'use specified mirror to update the checksum item for all corrupted blocks'

