# callgrind_annotate
# Autogenerated from man page /usr/share/man/man1/callgrind_annotate.1.gz
complete -c callgrind_annotate -s h -l help -d 'Show summary of options'
complete -c callgrind_annotate -l version -d 'Show version of callgrind_annotate'
complete -c callgrind_annotate -l show -d 'Only show figures for events A,B,C'
complete -c callgrind_annotate -l threshold -d 'Percentage of counts (of primary sort event) we are interested in'
complete -c callgrind_annotate -l sort -d 'Sort columns by events A,B,C [event column order]'
complete -c callgrind_annotate -l show-percs -d 'When enabled, a percentage is printed next to all event counts'
complete -c callgrind_annotate -l auto -d 'Annotate all source files containing functions that helped reach the event co…'
complete -c callgrind_annotate -l context -d 'Print N lines of context before and after annotated lines'
complete -c callgrind_annotate -l inclusive -d 'Add subroutine costs to functions calls'
complete -c callgrind_annotate -l tree -d 'Print for each function their callers, the called functions or both'
complete -c callgrind_annotate -s I -l include -d 'Add dir to the list of directories to search for source files'

