# capinfos
# Autogenerated from man page /usr/share/man/man1/capinfos.1.gz
complete -c capinfos -s a
complete -c capinfos -s A
complete -c capinfos -s b -d 'Separate infos with ASCII SPACE (0x20) characters'
complete -c capinfos -s B
complete -c capinfos -s c
complete -c capinfos -s C -d 'Cancel processing any additional files if and when Capinfos fails to open an …'
complete -c capinfos -s d
complete -c capinfos -s D
complete -c capinfos -s e
complete -c capinfos -s E
complete -c capinfos -s F
complete -c capinfos -s h -l help
complete -c capinfos -s H
complete -c capinfos -s i
complete -c capinfos -s I
complete -c capinfos -s k
complete -c capinfos -s K
complete -c capinfos -s l
complete -c capinfos -s L
complete -c capinfos -s m
complete -c capinfos -s M
complete -c capinfos -s n
complete -c capinfos -s N
complete -c capinfos -s o
complete -c capinfos -s p
complete -c capinfos -s P
complete -c capinfos -s q
complete -c capinfos -s Q
complete -c capinfos -s r
complete -c capinfos -s R
complete -c capinfos -s s
complete -c capinfos -s S
complete -c capinfos -s t
complete -c capinfos -s T
complete -c capinfos -s u
complete -c capinfos -s v -l version
complete -c capinfos -s x
complete -c capinfos -s y
complete -c capinfos -s z
complete -c capinfos -l log-level
complete -c capinfos -l log-fatal
complete -c capinfos -l log-domains
complete -c capinfos -l log-debug
complete -c capinfos -l log-noisy
complete -c capinfos -l log-fatal-domains
complete -c capinfos -l log-file

