# captype
# Autogenerated from man page /usr/share/man/man1/captype.1.gz
complete -c captype -s h -l help
complete -c captype -s v -l version
complete -c captype -l log-level
complete -c captype -l log-fatal
complete -c captype -l log-domains
complete -c captype -l log-debug
complete -c captype -l log-noisy
complete -c captype -l log-fatal-domains
complete -c captype -l log-file

