# cg_annotate
# Autogenerated from man page /usr/share/man/man1/cg_annotate.1.gz
complete -c cg_annotate -s h -l help -d 'Show the help message'
complete -c cg_annotate -l version -d 'Show the version number'
complete -c cg_annotate -l diff -d 'Diff two Cachegrind output files'
complete -c cg_annotate -l mod-filename -d 'Specifies an s/old/new/ search-and-replace expression that is applied to all …'
complete -c cg_annotate -l mod-funcname -d 'Like --mod-filename, but for filenames'
complete -c cg_annotate -l show -d 'Specifies which events to show (and the column order)'
complete -c cg_annotate -l sort -d 'Specifies the events upon which the sorting of the file:function and function…'
complete -c cg_annotate -l threshold -d 'Sets the significance threshold for the file:function and function:files sect…'
complete -c cg_annotate -l show-percs -l no-show-percs -l show-percs -d 'When enabled, a percentage is printed next to all event counts'
complete -c cg_annotate -l annotate -l no-annotate -l auto -d 'Enables or disables source file annotation'
complete -c cg_annotate -l context -d 'The number of lines of context to show before and after each annotated line'

