# cg_diff
# Autogenerated from man page /usr/share/man/man1/cg_diff.1.gz
complete -c cg_diff -s h -l help -d 'Show the help message'
complete -c cg_diff -l version -d 'Show the version number'
complete -c cg_diff -l mod-filename -d 'Specifies an s/old/new/ search-and-replace expression that is applied to all …'
complete -c cg_diff -l mod-funcname -d 'Like --mod-filename, but for filenames'

