# check_lft_balance
# Autogenerated from man page /usr/share/man/man8/check_lft_balance.8.gz
complete -c check_lft_balance -s h -d 'show help'
complete -c check_lft_balance -s R -d 'Recalculate dump_lfts information, ie do not use the cached information'
complete -c check_lft_balance -s v -d 'verbose output'

