# ciscodump
# Autogenerated from man page /usr/share/man/man1/ciscodump.1.gz
complete -c ciscodump -l help
complete -c ciscodump -l version
complete -c ciscodump -l extcap-interfaces
complete -c ciscodump -l extcap-interface
complete -c ciscodump -l extcap-dlts
complete -c ciscodump -l extcap-config
complete -c ciscodump -l capture
complete -c ciscodump -l fifo
complete -c ciscodump -l remote-host
complete -c ciscodump -l remote-port
complete -c ciscodump -l remote-username
complete -c ciscodump -l remote-password
complete -c ciscodump -l remote-filter -d 'The remote filter on the device'
complete -c ciscodump -l sshkey
complete -c ciscodump -l remote-interface -d 'The remote network interface to capture from'
complete -c ciscodump -l remote-count
complete -c ciscodump -l extcap-capture-filter

