# clazy
# Autogenerated from man page /usr/share/man/man1/clazy.1.gz
complete -c clazy -l help -d 'X Item "--help" Print help message and exit'
complete -c clazy -l version -d 'X Item "--version" Print version information and exit'
complete -c clazy -l list -d 'X Item "--list" Print a list of all available checkers, arranged by level'
complete -c clazy -l explain -d 'X Item "--explain" Print explanations for all checkers'
complete -c clazy -l qtdeveloper

