# cmtime
# Autogenerated from man page /usr/share/man/man1/cmtime.1.gz
complete -c cmtime -s C -d 'The network name or IP address of the instance which will provide step synchr…'
complete -c cmtime -s B -d 'The local RDMA interface to bind to.   Only one of -B or -b is accepted'
complete -c cmtime -s b -d 'The local network address to bind to.   Only one of -B or -b is accepted'
complete -c cmtime -s L -d 'Whether this instance is an RDMA CM server (set) or client (unset)'
complete -c cmtime -s c -d 'The number of connections to establish between each client-server pair'
complete -c cmtime -s P -d 'Total number of peers (clients, servers) which are going to be started'
complete -c cmtime -s p -d 'The controller\'s port number'
complete -c cmtime -s q -d 'The first QP number to use when creating connections without allocating hardw…'
complete -c cmtime -s n -d 'Sets the number of threads to spawn used to process connection events and har…'
complete -c cmtime -s m -d '"Simulates" QP creation and modify calls by replacing them with a simple slee…'
complete -c cmtime -s r -d 'Number of retries when resolving address or route.   (default 2)'
complete -c cmtime -s S -d 'Run connection rate test using sockets'
complete -c cmtime -s t -d 'Timeout in millseconds (ms) when resolving address or route'

