# containerd
# Autogenerated from man page /usr/share/man/man8/containerd.8.gz
complete -c containerd -l address -s a
complete -c containerd -l config -s c
complete -c containerd -l log-level -s l
complete -c containerd -l root
complete -c containerd -l state -d 'COMMANDS config Information on the containerd config'
complete -c containerd -l namespace
complete -c containerd -l topic

