# cpupower-set
# Autogenerated from man page /usr/share/man/man1/cpupower-set.1.gz
complete -c cpupower-set -l perf-bias -s b
complete -c cpupower-set -l epp -s e
complete -c cpupower-set -l amd-pstate-mode -s m
complete -c cpupower-set -l turbo-boost -l boost -s t

