# cryptsetup-refresh
# Autogenerated from man page /usr/share/man/man8/cryptsetup-refresh.8.gz
complete -c cryptsetup-refresh -l allow-discards
complete -c cryptsetup-refresh -l batch-mode -s q
complete -c cryptsetup-refresh -l debug -l debug-json
complete -c cryptsetup-refresh -l disable-keyring
complete -c cryptsetup-refresh -l disable-locks
complete -c cryptsetup-refresh -l header
complete -c cryptsetup-refresh -l help -s '?'
complete -c cryptsetup-refresh -l integrity-no-journal
complete -c cryptsetup-refresh -l perf-high_priority
complete -c cryptsetup-refresh -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-refresh -l perf-same_cpu_crypt
complete -c cryptsetup-refresh -l perf-submit_from_crypt_cpus
complete -c cryptsetup-refresh -l persistent
complete -c cryptsetup-refresh -l usage
complete -c cryptsetup-refresh -l version -s V

