# cryptsetup-luksConvertKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksConvertKey.8.gz
complete -c cryptsetup-luksConvertKey -l batch-mode -s q
complete -c cryptsetup-luksConvertKey -l debug -l debug-json
complete -c cryptsetup-luksConvertKey -l disable-locks
complete -c cryptsetup-luksConvertKey -l force-password
complete -c cryptsetup-luksConvertKey -l hash -s h
complete -c cryptsetup-luksConvertKey -l header
complete -c cryptsetup-luksConvertKey -l help -s '?'
complete -c cryptsetup-luksConvertKey -l iter-time -s i
complete -c cryptsetup-luksConvertKey -l key-file -s d
complete -c cryptsetup-luksConvertKey -l keyfile-offset
complete -c cryptsetup-luksConvertKey -l keyfile-size -s l
complete -c cryptsetup-luksConvertKey -l key-slot -s S
complete -c cryptsetup-luksConvertKey -l keyslot-cipher
complete -c cryptsetup-luksConvertKey -l keyslot-key-size
complete -c cryptsetup-luksConvertKey -l new-keyfile-offset
complete -c cryptsetup-luksConvertKey -l new-keyfile-size
complete -c cryptsetup-luksConvertKey -l pbkdf
complete -c cryptsetup-luksConvertKey -l pbkdf-force-iterations
complete -c cryptsetup-luksConvertKey -l pbkdf-memory
complete -c cryptsetup-luksConvertKey -l pbkdf-parallel
complete -c cryptsetup-luksConvertKey -l timeout -s t
complete -c cryptsetup-luksConvertKey -l usage
complete -c cryptsetup-luksConvertKey -l verify-passphrase -s y
complete -c cryptsetup-luksConvertKey -l version -s V

