# cryptsetup-luksAddKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksAddKey.8.gz
complete -c cryptsetup-luksAddKey -l batch-mode -s q
complete -c cryptsetup-luksAddKey -l debug -l debug-json
complete -c cryptsetup-luksAddKey -l disable-locks
complete -c cryptsetup-luksAddKey -l external-tokens-path
complete -c cryptsetup-luksAddKey -l force-password
complete -c cryptsetup-luksAddKey -l hash -s h
complete -c cryptsetup-luksAddKey -l header
complete -c cryptsetup-luksAddKey -l help -s '?'
complete -c cryptsetup-luksAddKey -l iter-time -s i
complete -c cryptsetup-luksAddKey -l key-description
complete -c cryptsetup-luksAddKey -l key-file -s d
complete -c cryptsetup-luksAddKey -l keyfile-offset
complete -c cryptsetup-luksAddKey -l keyfile-size -s l
complete -c cryptsetup-luksAddKey -l key-size -s s
complete -c cryptsetup-luksAddKey -l key-slot -s S
complete -c cryptsetup-luksAddKey -l keyslot-cipher
complete -c cryptsetup-luksAddKey -l keyslot-key-size
complete -c cryptsetup-luksAddKey -l new-keyfile
complete -c cryptsetup-luksAddKey -l new-keyfile-offset
complete -c cryptsetup-luksAddKey -l new-keyfile-size
complete -c cryptsetup-luksAddKey -l new-key-description
complete -c cryptsetup-luksAddKey -l new-key-slot
complete -c cryptsetup-luksAddKey -l new-token-id
complete -c cryptsetup-luksAddKey -l pbkdf
complete -c cryptsetup-luksAddKey -l pbkdf-force-iterations
complete -c cryptsetup-luksAddKey -l pbkdf-memory
complete -c cryptsetup-luksAddKey -l pbkdf-parallel
complete -c cryptsetup-luksAddKey -l timeout -s t
complete -c cryptsetup-luksAddKey -l token-id
complete -c cryptsetup-luksAddKey -l token-only
complete -c cryptsetup-luksAddKey -l token-type
complete -c cryptsetup-luksAddKey -l type
complete -c cryptsetup-luksAddKey -l unbound
complete -c cryptsetup-luksAddKey -l usage
complete -c cryptsetup-luksAddKey -l verify-passphrase -s y
complete -c cryptsetup-luksAddKey -l version -s V
complete -c cryptsetup-luksAddKey -l volume-key-file -l master-key-file
complete -c cryptsetup-luksAddKey -l volume-key-keyring

