# cryptsetup-open
# Autogenerated from man page /usr/share/man/man8/cryptsetup-open.8.gz
complete -c cryptsetup-open -l token-type -l token-id
complete -c cryptsetup-open -l allow-discards
complete -c cryptsetup-open -l batch-mode -s q
complete -c cryptsetup-open -l cipher -s c
complete -c cryptsetup-open -l debug -l debug-json
complete -c cryptsetup-open -l device-size
complete -c cryptsetup-open -l disable-external-tokens
complete -c cryptsetup-open -l disable-keyring
complete -c cryptsetup-open -l disable-locks
complete -c cryptsetup-open -l disable-veracrypt
complete -c cryptsetup-open -l external-tokens-path
complete -c cryptsetup-open -l hash -s h
complete -c cryptsetup-open -l header
complete -c cryptsetup-open -l help -s '?'
complete -c cryptsetup-open -l iv-large-sectors
complete -c cryptsetup-open -l key-description
complete -c cryptsetup-open -l key-file -s d
complete -c cryptsetup-open -l keyfile-offset
complete -c cryptsetup-open -l keyfile-size -s l
complete -c cryptsetup-open -l key-size -s s
complete -c cryptsetup-open -l key-slot -s S
complete -c cryptsetup-open -l link-vk-to-keyring
complete -c cryptsetup-open -l offset -s o
complete -c cryptsetup-open -l perf-high_priority
complete -c cryptsetup-open -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-open -l perf-same_cpu_crypt
complete -c cryptsetup-open -l perf-submit_from_crypt_cpus
complete -c cryptsetup-open -l persistent
complete -c cryptsetup-open -l readonly -s r
complete -c cryptsetup-open -l refresh
complete -c cryptsetup-open -l sector-size
complete -c cryptsetup-open -l serialize-memory-hard-pbkdf
complete -c cryptsetup-open -l shared
complete -c cryptsetup-open -l size -s b
complete -c cryptsetup-open -l skip -s p
complete -c cryptsetup-open -l tcrypt-backup -l tcrypt-hidden -l tcrypt-system
complete -c cryptsetup-open -l test-passphrase
complete -c cryptsetup-open -l timeout -s t
complete -c cryptsetup-open -l token-only
complete -c cryptsetup-open -l tries -s T
complete -c cryptsetup-open -l type
complete -c cryptsetup-open -l unbound
complete -c cryptsetup-open -l usage
complete -c cryptsetup-open -l veracrypt
complete -c cryptsetup-open -l veracrypt-pim -l veracrypt-query-pim
complete -c cryptsetup-open -l verify-passphrase -s y
complete -c cryptsetup-open -l version -s V
complete -c cryptsetup-open -l volume-key-file -l master-key-file
complete -c cryptsetup-open -l volume-key-keyring

