# cryptsetup-luksResume
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksResume.8.gz
complete -c cryptsetup-luksResume -l batch-mode -s q
complete -c cryptsetup-luksResume -l debug -l debug-json
complete -c cryptsetup-luksResume -l disable-external-tokens
complete -c cryptsetup-luksResume -l disable-keyring
complete -c cryptsetup-luksResume -l disable-locks
complete -c cryptsetup-luksResume -l external-tokens-path
complete -c cryptsetup-luksResume -l header
complete -c cryptsetup-luksResume -l help -s '?'
complete -c cryptsetup-luksResume -l key-description
complete -c cryptsetup-luksResume -l key-file -s d
complete -c cryptsetup-luksResume -l keyfile-offset
complete -c cryptsetup-luksResume -l keyfile-size -s l
complete -c cryptsetup-luksResume -l key-slot -s S
complete -c cryptsetup-luksResume -l link-vk-to-keyring
complete -c cryptsetup-luksResume -l timeout -s t
complete -c cryptsetup-luksResume -l token-id
complete -c cryptsetup-luksResume -l token-only
complete -c cryptsetup-luksResume -l token-type
complete -c cryptsetup-luksResume -l tries -s T
complete -c cryptsetup-luksResume -l type
complete -c cryptsetup-luksResume -l usage
complete -c cryptsetup-luksResume -l verify-passphrase -s y
complete -c cryptsetup-luksResume -l version -s V
complete -c cryptsetup-luksResume -l volume-key-keyring

