# cryptsetup-resize
# Autogenerated from man page /usr/share/man/man8/cryptsetup-resize.8.gz
complete -c cryptsetup-resize -l batch-mode -s q
complete -c cryptsetup-resize -l debug -l debug-json
complete -c cryptsetup-resize -l device-size
complete -c cryptsetup-resize -l disable-external-tokens
complete -c cryptsetup-resize -l disable-keyring
complete -c cryptsetup-resize -l disable-locks
complete -c cryptsetup-resize -l external-tokens-path
complete -c cryptsetup-resize -l header
complete -c cryptsetup-resize -l help -s '?'
complete -c cryptsetup-resize -l key-description
complete -c cryptsetup-resize -l key-file -s d
complete -c cryptsetup-resize -l keyfile-offset
complete -c cryptsetup-resize -l keyfile-size -s l
complete -c cryptsetup-resize -l key-slot -s S
complete -c cryptsetup-resize -l size -s b
complete -c cryptsetup-resize -l timeout -s t
complete -c cryptsetup-resize -l token-id
complete -c cryptsetup-resize -l token-only
complete -c cryptsetup-resize -l token-type
complete -c cryptsetup-resize -l usage
complete -c cryptsetup-resize -l verify-passphrase -s y
complete -c cryptsetup-resize -l version -s V
complete -c cryptsetup-resize -l volume-key-keyring

