# cryptsetup-luksKillSlot
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksKillSlot.8.gz
complete -c cryptsetup-luksKillSlot -l batch-mode -s q
complete -c cryptsetup-luksKillSlot -l debug -l debug-json
complete -c cryptsetup-luksKillSlot -l disable-locks
complete -c cryptsetup-luksKillSlot -l header
complete -c cryptsetup-luksKillSlot -l help -s '?'
complete -c cryptsetup-luksKillSlot -l key-file -s d
complete -c cryptsetup-luksKillSlot -l keyfile-offset
complete -c cryptsetup-luksKillSlot -l keyfile-size -s l
complete -c cryptsetup-luksKillSlot -l timeout -s t
complete -c cryptsetup-luksKillSlot -l type
complete -c cryptsetup-luksKillSlot -l usage
complete -c cryptsetup-luksKillSlot -l verify-passphrase -s y
complete -c cryptsetup-luksKillSlot -l version -s V

