# cryptsetup-luksFormat
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksFormat.8.gz
complete -c cryptsetup-luksFormat -l align-payload -l offset
complete -c cryptsetup-luksFormat -l batch-mode -s q
complete -c cryptsetup-luksFormat -l cipher -s c
complete -c cryptsetup-luksFormat -l debug -l debug-json
complete -c cryptsetup-luksFormat -l disable-blkid
complete -c cryptsetup-luksFormat -l disable-keyring
complete -c cryptsetup-luksFormat -l disable-locks
complete -c cryptsetup-luksFormat -l force-password
complete -c cryptsetup-luksFormat -l hash -s h
complete -c cryptsetup-luksFormat -l header
complete -c cryptsetup-luksFormat -l help -s '?'
complete -c cryptsetup-luksFormat -l hw-opal
complete -c cryptsetup-luksFormat -l hw-opal-only
complete -c cryptsetup-luksFormat -l integrity
complete -c cryptsetup-luksFormat -l integrity-inline
complete -c cryptsetup-luksFormat -l integrity-key-size
complete -c cryptsetup-luksFormat -l integrity-legacy-padding
complete -c cryptsetup-luksFormat -l integrity-no-wipe
complete -c cryptsetup-luksFormat -l iter-time -s i
complete -c cryptsetup-luksFormat -l key-description
complete -c cryptsetup-luksFormat -l key-file -s d
complete -c cryptsetup-luksFormat -l keyfile-offset
complete -c cryptsetup-luksFormat -l keyfile-size -s l
complete -c cryptsetup-luksFormat -l key-size -s s
complete -c cryptsetup-luksFormat -l key-slot -s S
complete -c cryptsetup-luksFormat -l keyslot-cipher
complete -c cryptsetup-luksFormat -l keyslot-key-size
complete -c cryptsetup-luksFormat -l label -l subsystem
complete -c cryptsetup-luksFormat -l luks2-keyslots-size
complete -c cryptsetup-luksFormat -l luks2-metadata-size
complete -c cryptsetup-luksFormat -s o
complete -c cryptsetup-luksFormat -l pbkdf
complete -c cryptsetup-luksFormat -l pbkdf-force-iterations
complete -c cryptsetup-luksFormat -l pbkdf-memory
complete -c cryptsetup-luksFormat -l pbkdf-parallel
complete -c cryptsetup-luksFormat -l progress-frequency
complete -c cryptsetup-luksFormat -l progress-json
complete -c cryptsetup-luksFormat -l sector-size
complete -c cryptsetup-luksFormat -l timeout -s t
complete -c cryptsetup-luksFormat -l type
complete -c cryptsetup-luksFormat -l usage
complete -c cryptsetup-luksFormat -l use-random -l use-urandom
complete -c cryptsetup-luksFormat -l uuid
complete -c cryptsetup-luksFormat -l verify-passphrase -s y
complete -c cryptsetup-luksFormat -l version -s V
complete -c cryptsetup-luksFormat -l volume-key-file -l master-key-file

