# cryptsetup-tcryptDump
# Autogenerated from man page /usr/share/man/man8/cryptsetup-tcryptDump.8.gz
complete -c cryptsetup-tcryptDump -l batch-mode -s q
complete -c cryptsetup-tcryptDump -l cipher -s c
complete -c cryptsetup-tcryptDump -l debug -l debug-json
complete -c cryptsetup-tcryptDump -l disable-veracrypt
complete -c cryptsetup-tcryptDump -l dump-volume-key -l dump-master-key
complete -c cryptsetup-tcryptDump -l hash -s h
complete -c cryptsetup-tcryptDump -l header
complete -c cryptsetup-tcryptDump -l help -s '?'
complete -c cryptsetup-tcryptDump -l key-file -s d
complete -c cryptsetup-tcryptDump -l tcrypt-backup -l tcrypt-hidden -l tcrypt-system
complete -c cryptsetup-tcryptDump -l timeout -s t
complete -c cryptsetup-tcryptDump -l usage
complete -c cryptsetup-tcryptDump -l veracrypt
complete -c cryptsetup-tcryptDump -l veracrypt-pim -l veracrypt-query-pim
complete -c cryptsetup-tcryptDump -l verify-passphrase -s y
complete -c cryptsetup-tcryptDump -l version -s V

