# cryptsetup-luksChangeKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksChangeKey.8.gz
complete -c cryptsetup-luksChangeKey -l batch-mode -s q
complete -c cryptsetup-luksChangeKey -l debug -l debug-json
complete -c cryptsetup-luksChangeKey -l disable-locks
complete -c cryptsetup-luksChangeKey -l force-password
complete -c cryptsetup-luksChangeKey -l hash -s h
complete -c cryptsetup-luksChangeKey -l header
complete -c cryptsetup-luksChangeKey -l help -s '?'
complete -c cryptsetup-luksChangeKey -l iter-time -s i
complete -c cryptsetup-luksChangeKey -l key-file -s d
complete -c cryptsetup-luksChangeKey -l keyfile-offset
complete -c cryptsetup-luksChangeKey -l keyfile-size -s l
complete -c cryptsetup-luksChangeKey -l key-slot -s S
complete -c cryptsetup-luksChangeKey -l keyslot-cipher
complete -c cryptsetup-luksChangeKey -l keyslot-key-size
complete -c cryptsetup-luksChangeKey -l new-keyfile-offset
complete -c cryptsetup-luksChangeKey -l new-keyfile-size
complete -c cryptsetup-luksChangeKey -l pbkdf
complete -c cryptsetup-luksChangeKey -l pbkdf-force-iterations
complete -c cryptsetup-luksChangeKey -l pbkdf-memory
complete -c cryptsetup-luksChangeKey -l pbkdf-parallel
complete -c cryptsetup-luksChangeKey -l timeout -s t
complete -c cryptsetup-luksChangeKey -l type
complete -c cryptsetup-luksChangeKey -l usage
complete -c cryptsetup-luksChangeKey -l verify-passphrase -s y
complete -c cryptsetup-luksChangeKey -l version -s V

