# cryptsetup-luksDump
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksDump.8.gz
complete -c cryptsetup-luksDump -l batch-mode -s q
complete -c cryptsetup-luksDump -l debug -l debug-json
complete -c cryptsetup-luksDump -l disable-locks
complete -c cryptsetup-luksDump -l dump-json-metadata
complete -c cryptsetup-luksDump -l dump-volume-key -l dump-master-key
complete -c cryptsetup-luksDump -l external-tokens-path
complete -c cryptsetup-luksDump -l header
complete -c cryptsetup-luksDump -l help -s '?'
complete -c cryptsetup-luksDump -l key-description
complete -c cryptsetup-luksDump -l key-file -s d
complete -c cryptsetup-luksDump -l keyfile-offset
complete -c cryptsetup-luksDump -l keyfile-size -s l
complete -c cryptsetup-luksDump -l key-slot -s S
complete -c cryptsetup-luksDump -l timeout -s t
complete -c cryptsetup-luksDump -l type
complete -c cryptsetup-luksDump -l unbound
complete -c cryptsetup-luksDump -l usage
complete -c cryptsetup-luksDump -l version -s V
complete -c cryptsetup-luksDump -l volume-key-file -l master-key-file

