# ctr
# Autogenerated from man page /usr/share/man/man8/ctr.8.gz
complete -c ctr -l address -s a
complete -c ctr -l connect-timeout
complete -c ctr -l debug
complete -c ctr -l namespace -s n
complete -c ctr -l timeout -d 'COMMANDS plugins, plugin Provides information about containerd plugins'
complete -c ctr -l detailed -s d
complete -c ctr -l quiet -s q
complete -c ctr -l runc-binary
complete -c ctr -l runc-root
complete -c ctr -l runc-systemd-cgroup
complete -c ctr -l runtime
complete -c ctr -l runtime-config-path
complete -c ctr -l allow-new-privs
complete -c ctr -l annotation
complete -c ctr -l apparmor-default-profile
complete -c ctr -l apparmor-profile
complete -c ctr -l blockio-class
complete -c ctr -l blockio-config-file
complete -c ctr -l cap-add
complete -c ctr -l cap-drop
complete -c ctr -l config -s c
complete -c ctr -l cpu-period
complete -c ctr -l cpu-quota -s 1
complete -c ctr -l cwd
complete -c ctr -l device
complete -c ctr -l env
complete -c ctr -l env-file
complete -c ctr -l gpus
complete -c ctr -l hostname
complete -c ctr -l label
complete -c ctr -l memory-limit
complete -c ctr -l mount
complete -c ctr -l net-host
complete -c ctr -l no-pivot
complete -c ctr -l pid-file
complete -c ctr -l privileged
complete -c ctr -l rdt-class
complete -c ctr -l read-only
complete -c ctr -l rootfs
complete -c ctr -l rootfs-propagation
complete -c ctr -l sandbox
complete -c ctr -l seccomp
complete -c ctr -l seccomp-profile
complete -c ctr -l snapshotter
complete -c ctr -l snapshotter-label
complete -c ctr -l tty -s t
complete -c ctr -l user -s u
complete -c ctr -l with-ns
complete -c ctr -l keep-snapshot
complete -c ctr -l spec
complete -c ctr -l image
complete -c ctr -l rw
complete -c ctr -l task
complete -c ctr -l live
complete -c ctr -l root
complete -c ctr -l editor
complete -c ctr -l validate
complete -c ctr -l all-platforms
complete -c ctr -l hosts-dir
complete -c ctr -l http-dump
complete -c ctr -l http-trace
complete -c ctr -l metadata-only
complete -c ctr -l plain-http
complete -c ctr -l platform
complete -c ctr -l refresh
complete -c ctr -l skip-metadata
complete -c ctr -l skip-verify -s k
complete -c ctr -l tlscacert
complete -c ctr -l tlscert
complete -c ctr -l tlskey
complete -c ctr -l media-type
complete -c ctr -l expected-digest
complete -c ctr -l expected-size
complete -c ctr -l async
complete -c ctr -l dry
complete -c ctr -l local
complete -c ctr -l skip-manifest-json
complete -c ctr -l skip-non-distributable
complete -c ctr -l base-name
complete -c ctr -l compress-blobs
complete -c ctr -l digests
complete -c ctr -l discard-unpacked-layers -l no-unpack
complete -c ctr -l index-name
complete -c ctr -l skip-digest-for-named
complete -c ctr -l sync-fs
complete -c ctr -l content
complete -c ctr -l expiration -s x
complete -c ctr -l rm
complete -c ctr -l max-concurrent-downloads
complete -c ctr -l print-chainid
complete -c ctr -l allow-non-distributable-blobs
complete -c ctr -l manifest
complete -c ctr -l manifest-type
complete -c ctr -l max-concurrent-uploaded-layers
complete -c ctr -l all
complete -c ctr -l sync
complete -c ctr -l force
complete -c ctr -l skip-reference-check
complete -c ctr -l replace-all -s r
complete -c ctr -l oci
complete -c ctr -l uncompress
complete -c ctr -l expires
complete -c ctr -l id
complete -c ctr -l cgroup
complete -c ctr -l debug-socket
complete -c ctr -l seconds -s s
complete -c ctr -l cni
complete -c ctr -l cpu-shares
complete -c ctr -l cpus
complete -c ctr -l cpuset-cpus
complete -c ctr -l cpuset-mems
complete -c ctr -l detach
complete -c ctr -l fifo-dir
complete -c ctr -l gidmap
complete -c ctr -l log-uri
complete -c ctr -l null-io
complete -c ctr -l privileged-without-host-devices
complete -c ctr -l remap-labels
complete -c ctr -l uidmap
complete -c ctr -l keep
complete -c ctr -l ref
complete -c ctr -l temp
complete -c ctr -l mounts
complete -c ctr -l target
complete -c ctr -s b
complete -c ctr -l exit
complete -c ctr -l image-path
complete -c ctr -l work-path
complete -c ctr -l exec-id
complete -c ctr -s f
complete -c ctr -l signal
complete -c ctr -l format
complete -c ctr -l libs -s l
complete -c ctr -l path
complete -c ctr -l replace
complete -c ctr -l filters
complete -c ctr -l shim-address
complete -c ctr -l attach
complete -c ctr -s e
complete -c ctr -l stderr
complete -c ctr -l stdin
complete -c ctr -l stdout
complete -c ctr -l api-version
complete -c ctr -l task-id

