# defrag.exfat
# Autogenerated from man page /usr/share/man/man8/defrag.exfat.8.gz
complete -c 'defrag.exfat' -s f -l force -d 'Perform defragmentation without prompting the fsck warning.  Use with caution'
complete -c 'defrag.exfat' -s a -l assessment -d 'Assess the fragmentation status of the exFAT volume without making any changes'
complete -c 'defrag.exfat' -s v -l version -d 'Display version information and exit'
complete -c 'defrag.exfat' -s h -l help -d 'Show usage information and exit'

