# depmod
# Autogenerated from man page /usr/share/man/man8/depmod.8.gz
complete -c depmod -s A -l quick -d 'This option scans to see if any modules are newer than the'
complete -c depmod -s b -l basedir -d 'Override the base directory <BASEDIR> where modules are located'
complete -c depmod -s m -l moduledir -d 'Override the module directory <MODULEDIR>, which defaults to'
complete -c depmod -s r -d 'index files under the same directory.  Unless libkmod is prepared to'
complete -c depmod -s o -l outdir -d 'Set the output directory where depmod will store any generated file'
complete -c depmod -s C -l config -d 'This option overrides the default configuration files.  See'
complete -c depmod -s e -l errsyms -d 'When combined with the -F option, this reports any symbols which a'
complete -c depmod -s E -l symvers -d 'When combined with the -e option, this reports any symbol versions'
complete -c depmod -s F -l filesyms -d 'Supplied with the System. map produced when the kernel was built, this'
complete -c depmod -s h -l help -d 'Print the help message and exit'
complete -c depmod -s n -l show -l dry-run -d 'This sends the resulting modules. dep and the various map files to'
complete -c depmod -s P -d 'Some architectures prefix symbols with an extraneous character.  This'
complete -c depmod -s v -l verbose -d 'In verbose mode, depmod will print (to stdout) all the symbols each'
complete -c depmod -s V -l version -d 'Show version of program and exit.  See below for caveats when run on'
complete -c depmod -s w -d 'Warn on duplicate dependencies, aliases, symbol versions, etc'

