# diffman-git
# Autogenerated from man page /usr/share/man/man1/diffman-git.1.gz
complete -c diffman-git -s s -d 'Report when two files are the same'
complete -c diffman-git -s U -d 'output  n (default 3) lines of unified context'
complete -c diffman-git -s w -d 'Ignore all white space.  ENVIRONMENT See man (1).  EXAMPLES'
complete -c diffman-git -l - -d '+++ 437e4afec6ca:man/man3/sem_open. 3 @@ -14,3 +14,2 @@'

