# docker-plugin-enable
# Autogenerated from man page /usr/share/man/man1/docker-plugin-enable.1.gz
complete -c docker-plugin-enable -l timeout -d '	HTTP client timeout (in seconds) SEE ALSO docker-plugin(1)'

