# docker-plugin-upgrade
# Autogenerated from man page /usr/share/man/man1/docker-plugin-upgrade.1.gz
complete -c docker-plugin-upgrade -l grant-all-permissions -d '	Grant all permissions necessary to run the plugin'
complete -c docker-plugin-upgrade -l skip-remote-check -d '	Do not check if specified remote plugin matches existing plugin image SEE AL…'

