# docker-checkpoint-ls
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint-ls.1.gz
complete -c docker-checkpoint-ls -l checkpoint-dir -d '	Use a custom checkpoint storage directory SEE ALSO docker-checkpoint(1)'

