# docker-volume-prune
# Autogenerated from man page /usr/share/man/man1/docker-volume-prune.1.gz
complete -c docker-volume-prune -s a -l all -d '	Remove all unused volumes, not just anonymous ones'
complete -c docker-volume-prune -l filter -d '	Provide filter values (e. g.  "label=")'
complete -c docker-volume-prune -s f -l force -d '	Do not prompt for confirmation SEE ALSO docker-volume(1)'

