# docker-container-commit
# Autogenerated from man page /usr/share/man/man1/docker-container-commit.1.gz
complete -c docker-container-commit -s a -l author -d '	Author (e. g. , "John Hannibal Smith hannibal@a-team'
complete -c docker-container-commit -s c -l change -d '	Apply Dockerfile instruction to the created image'
complete -c docker-container-commit -s m -l message -d '	Commit message'
complete -c docker-container-commit -l no-pause -d '	Disable pausing container during commit SEE ALSO docker-container(1)'

