# docker-plugin-create
# Autogenerated from man page /usr/share/man/man1/docker-plugin-create.1.gz
complete -c docker-plugin-create -l compress -d '	Compress the context using gzip SEE ALSO docker-plugin(1)'

