# docker-config-ls
# Autogenerated from man page /usr/share/man/man1/docker-config-ls.1.gz
complete -c docker-config-ls -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-config-ls -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-config-ls -s q -l quiet -d '	Only display IDs SEE ALSO docker-config(1)'

