# docker-system-info
# Autogenerated from man page /usr/share/man/man1/docker-system-info.1.gz
complete -c docker-system-info -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'

