# docker-container-inspect
# Autogenerated from man page /usr/share/man/man1/docker-container-inspect.1.gz
complete -c docker-container-inspect -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-container-inspect -s s -l size -d '	Display total file sizes SEE ALSO docker-container(1)'

