# docker-swarm-leave
# Autogenerated from man page /usr/share/man/man1/docker-swarm-leave.1.gz
complete -c docker-swarm-leave -s f -l force -d '	Force this node to leave the swarm, ignoring warnings SEE ALSO docker-swarm(…'

