# docker-image-save
# Autogenerated from man page /usr/share/man/man1/docker-image-save.1.gz
complete -c docker-image-save -s o -l output -d '	Write to a file, instead of STDOUT'
complete -c docker-image-save -l platform -d '	Save only the given platform(s)'

