# docker-plugin-ls
# Autogenerated from man page /usr/share/man/man1/docker-plugin-ls.1.gz
complete -c docker-plugin-ls -s f -l filter -d '	Provide filter values (e. g.  "enabled=true")'
complete -c docker-plugin-ls -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-plugin-ls -l no-trunc -d '	Don\'t truncate output'
complete -c docker-plugin-ls -s q -l quiet -d '	Only display plugin IDs SEE ALSO docker-plugin(1)'

