# docker-container-stats
# Autogenerated from man page /usr/share/man/man1/docker-container-stats.1.gz
complete -c docker-container-stats -s a -l all -d '	Show all containers (default shows just running)'
complete -c docker-container-stats -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-container-stats -l no-stream -d '	Disable streaming stats and only pull the first result'
complete -c docker-container-stats -l no-trunc -d '	Do not truncate output SEE ALSO docker-container(1)'

