# docker-images
# Autogenerated from man page /usr/share/man/man1/docker-images.1.gz
complete -c docker-images -s a -l all -d '	Show all images (default hides intermediate and dangling images)'
complete -c docker-images -l digests -d '	Show digests'
complete -c docker-images -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-images -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-images -l no-trunc -d '	Don\'t truncate output'
complete -c docker-images -s q -l quiet -d '	Only show image IDs'
complete -c docker-images -l tree -d '	List multi-platform images as a tree (EXPERIMENTAL) SEE ALSO docker(1)'

