# docker-info
# Autogenerated from man page /usr/share/man/man1/docker-info.1.gz
complete -c docker-info -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'

