# docker-volume-rm
# Autogenerated from man page /usr/share/man/man1/docker-volume-rm.1.gz
complete -c docker-volume-rm -s f -l force -d '	Force the removal of one or more volumes SEE ALSO docker-volume(1)'

