# docker-context-rm
# Autogenerated from man page /usr/share/man/man1/docker-context-rm.1.gz
complete -c docker-context-rm -s f -l force -d '	Force the removal of a context in use SEE ALSO docker-context(1)'

