# docker-manifest-create
# Autogenerated from man page /usr/share/man/man1/docker-manifest-create.1.gz
complete -c docker-manifest-create -s a -l amend -d '	Amend an existing manifest list'
complete -c docker-manifest-create -l insecure -d '	Allow communication with an insecure registry SEE ALSO docker-manifest(1)'

