# docker-plugin-disable
# Autogenerated from man page /usr/share/man/man1/docker-plugin-disable.1.gz
complete -c docker-plugin-disable -s f -l force -d '	Force the disable of an active plugin SEE ALSO docker-plugin(1)'

