# docker-stack-deploy
# Autogenerated from man page /usr/share/man/man1/docker-stack-deploy.1.gz
complete -c docker-stack-deploy -s c -l compose-file -d '	Path to a Compose file, or "-" to read from stdin'
complete -c docker-stack-deploy -s d -l detach -d '	Exit immediately instead of waiting for the stack services to converge'
complete -c docker-stack-deploy -l prune -d '	Prune services that are no longer referenced'
complete -c docker-stack-deploy -s q -l quiet -d '	Suppress progress output'
complete -c docker-stack-deploy -l resolve-image -d '	Query the registry to resolve image digest and supported platforms ("always"…'
complete -c docker-stack-deploy -l with-registry-auth -d '	Send registry authentication details to Swarm agents SEE ALSO docker-stack(1)'

