# docker-search
# Autogenerated from man page /usr/share/man/man1/docker-search.1.gz
complete -c docker-search -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-search -l format -d '	Pretty-print search using a Go template'
complete -c docker-search -l limit -d '	Max number of search results'
complete -c docker-search -l no-trunc -d '	Don\'t truncate output SEE ALSO docker(1)'

