# docker-secret-inspect
# Autogenerated from man page /usr/share/man/man1/docker-secret-inspect.1.gz
complete -c docker-secret-inspect -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-secret-inspect -l pretty -d '	Print the information in a human friendly format SEE ALSO docker-secret(1)'

