# docker-stack-ps
# Autogenerated from man page /usr/share/man/man1/docker-stack-ps.1.gz
complete -c docker-stack-ps -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-stack-ps -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-stack-ps -l no-resolve -d '	Do not map IDs to Names'
complete -c docker-stack-ps -l no-trunc -d '	Do not truncate output'
complete -c docker-stack-ps -s q -l quiet -d '	Only display task IDs SEE ALSO docker-stack(1)'

