# docker-service-rollback
# Autogenerated from man page /usr/share/man/man1/docker-service-rollback.1.gz
complete -c docker-service-rollback -s d -l detach -d '	Exit immediately instead of waiting for the service to converge'
complete -c docker-service-rollback -s q -l quiet -d '	Suppress progress output SEE ALSO docker-service(1)'

