# docker-save
# Autogenerated from man page /usr/share/man/man1/docker-save.1.gz
complete -c docker-save -s o -l output -d '	Write to a file, instead of STDOUT'
complete -c docker-save -l platform -d '	Save only the given platform(s)'

