# docker-container-cp
# Autogenerated from man page /usr/share/man/man1/docker-container-cp.1.gz
complete -c docker-container-cp -s a -l archive -d '	Archive mode (copy all uid/gid information)'
complete -c docker-container-cp -s L -l follow-link -d '	Always follow symbol link in SRC_PATH'
complete -c docker-container-cp -s q -l quiet -d '	Suppress progress output during copy'

