# docker-version
# Autogenerated from man page /usr/share/man/man1/docker-version.1.gz
complete -c docker-version -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'

