# docker-image-import
# Autogenerated from man page /usr/share/man/man1/docker-image-import.1.gz
complete -c docker-image-import -l platform -d 'daemon.  # docker image import --platform=linux . \\linuximage'
complete -c docker-image-import -s c -l change -d '	Apply Dockerfile instruction to the created image'
complete -c docker-image-import -s m -l message -d '	Set commit message for imported image'

