# docker-image-ls
# Autogenerated from man page /usr/share/man/man1/docker-image-ls.1.gz
complete -c docker-image-ls -s a -l all -d '	Show all images (default hides intermediate and dangling images)'
complete -c docker-image-ls -l digests -d '	Show digests'
complete -c docker-image-ls -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-image-ls -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-image-ls -l no-trunc -d '	Don\'t truncate output'
complete -c docker-image-ls -s q -l quiet -d '	Only show image IDs'
complete -c docker-image-ls -l tree -d '	List multi-platform images as a tree (EXPERIMENTAL) SEE ALSO docker-image(1)'

