# docker-container-export
# Autogenerated from man page /usr/share/man/man1/docker-container-export.1.gz
complete -c docker-container-export -s o -l output -d '	Write to a file, instead of STDOUT SEE ALSO docker-container(1)'

