# docker-start
# Autogenerated from man page /usr/share/man/man1/docker-start.1.gz
complete -c docker-start -s a -l attach -d '	Attach STDOUT/STDERR and forward signals'
complete -c docker-start -l checkpoint -d '	Restore from this checkpoint'
complete -c docker-start -l checkpoint-dir -d '	Use a custom checkpoint storage directory'
complete -c docker-start -l detach-keys -d '	Override the key sequence for detaching a container'
complete -c docker-start -s i -l interactive -d '	Attach container\'s STDIN SEE ALSO docker(1)'

