# docker-network-connect
# Autogenerated from man page /usr/share/man/man1/docker-network-connect.1.gz
complete -c docker-network-connect -l alias -d '	Add network-scoped alias for the container'
complete -c docker-network-connect -l driver-opt -d '	driver options for the network'
complete -c docker-network-connect -l gw-priority -d '	Highest gw-priority provides the default gateway'
complete -c docker-network-connect -l ip -d '	IPv4 address (e. g. , "172. 30. 100. 104")'
complete -c docker-network-connect -l ip6 -d '	IPv6 address (e. g. , "2001:db8::33")'
complete -c docker-network-connect -l link -d '	Add link to another container'
complete -c docker-network-connect -l link-local-ip -d '	Add a link-local address for the container SEE ALSO docker-network(1)'

