# docker-network-prune
# Autogenerated from man page /usr/share/man/man1/docker-network-prune.1.gz
complete -c docker-network-prune -l filter -d '	Provide filter values (e. g.  "until=")'
complete -c docker-network-prune -s f -l force -d '	Do not prompt for confirmation SEE ALSO docker-network(1)'

