# docker-rmi
# Autogenerated from man page /usr/share/man/man1/docker-rmi.1.gz
complete -c docker-rmi -s f -l force -d '	Force removal of the image'
complete -c docker-rmi -l no-prune -d '	Do not delete untagged parents'
complete -c docker-rmi -l platform -d '	Remove only the given platform variant'

