# docker-volume-ls
# Autogenerated from man page /usr/share/man/man1/docker-volume-ls.1.gz
complete -c docker-volume-ls -l filter -d 'more than one filter,  pass multiple flags (for example,'
complete -c docker-volume-ls -l cluster -d '	Display only cluster volumes, and use cluster volume list formatting'
complete -c docker-volume-ls -s f -d '	Provide filter values (e. g.  "dangling=true")'
complete -c docker-volume-ls -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-volume-ls -s q -l quiet -d '	Only display volume names SEE ALSO docker-volume(1)'

