# docker-stack-config
# Autogenerated from man page /usr/share/man/man1/docker-stack-config.1.gz
complete -c docker-stack-config -s c -l compose-file -d '	Path to a Compose file, or "-" to read from stdin'
complete -c docker-stack-config -l skip-interpolation -d '	Skip interpolation and output only merged config SEE ALSO docker-stack(1)'

