# docker-container-kill
# Autogenerated from man page /usr/share/man/man1/docker-container-kill.1.gz
complete -c docker-container-kill -s s -l signal -d '	Signal to send to the container SEE ALSO docker-container(1)'

