# docker-manifest-inspect
# Autogenerated from man page /usr/share/man/man1/docker-manifest-inspect.1.gz
complete -c docker-manifest-inspect -l insecure -d '	Allow communication with an insecure registry'
complete -c docker-manifest-inspect -s v -l verbose -d '	Output additional info including layers and platform SEE ALSO docker-manifes…'

