# docker-stop
# Autogenerated from man page /usr/share/man/man1/docker-stop.1.gz
complete -c docker-stop -s s -l signal -d '	Signal to send to the container'
complete -c docker-stop -s t -l timeout -d '	Seconds to wait before killing the container SEE ALSO docker(1)'

