# docker-attach
# Autogenerated from man page /usr/share/man/man1/docker-attach.1.gz
complete -c docker-attach -l detach-keys -d '	Override the key sequence for detaching a container'
complete -c docker-attach -l no-stdin -d '	Do not attach STDIN'
complete -c docker-attach -l sig-proxy -d '	Proxy all received signals to the process SEE ALSO docker(1)'

