# docker-config-inspect
# Autogenerated from man page /usr/share/man/man1/docker-config-inspect.1.gz
complete -c docker-config-inspect -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-config-inspect -l pretty -d '	Print the information in a human friendly format SEE ALSO docker-config(1)'

