# docker-container-restart
# Autogenerated from man page /usr/share/man/man1/docker-container-restart.1.gz
complete -c docker-container-restart -s s -l signal -d '	Signal to send to the container'
complete -c docker-container-restart -s t -l timeout -d '	Seconds to wait before killing the container SEE ALSO docker-container(1)'

