# docker-system-events
# Autogenerated from man page /usr/share/man/man1/docker-system-events.1.gz
complete -c docker-system-events -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-system-events -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-system-events -l since -d '	Show all events created since timestamp'
complete -c docker-system-events -l until -d '	Stream events until this timestamp SEE ALSO docker-system(1)'

