# docker-config-create
# Autogenerated from man page /usr/share/man/man1/docker-config-create.1.gz
complete -c docker-config-create -s l -l label -d '	Config labels'
complete -c docker-config-create -l template-driver -d '	Template driver SEE ALSO docker-config(1)'

