# docker-pull
# Autogenerated from man page /usr/share/man/man1/docker-pull.1.gz
complete -c docker-pull -s a -l all-tags -d '	Download all tagged images in the repository'
complete -c docker-pull -l platform -d '	Set platform if server is multi-platform capable'
complete -c docker-pull -s q -l quiet -d '	Suppress verbose output SEE ALSO docker(1)'

