# docker-swarm-join-token
# Autogenerated from man page /usr/share/man/man1/docker-swarm-join-token.1.gz
complete -c docker-swarm-join-token -s q -l quiet -d '	Only display token'
complete -c docker-swarm-join-token -l rotate -d '	Rotate join token SEE ALSO docker-swarm(1)'

