# docker-stack-services
# Autogenerated from man page /usr/share/man/man1/docker-stack-services.1.gz
complete -c docker-stack-services -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-stack-services -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-stack-services -s q -l quiet -d '	Only display IDs SEE ALSO docker-stack(1)'

