# docker-image-load
# Autogenerated from man page /usr/share/man/man1/docker-image-load.1.gz
complete -c docker-image-load -s i -l input -d '	Read from tar archive file, instead of STDIN'
complete -c docker-image-load -l platform -d '	Load only the given platform(s)'
complete -c docker-image-load -s q -l quiet -d '	Suppress the load output SEE ALSO docker-image(1)'

