# docker-node-inspect
# Autogenerated from man page /usr/share/man/man1/docker-node-inspect.1.gz
complete -c docker-node-inspect -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-node-inspect -l pretty -d '	Print the information in a human friendly format SEE ALSO docker-node(1)'

