# docker-plugin-rm
# Autogenerated from man page /usr/share/man/man1/docker-plugin-rm.1.gz
complete -c docker-plugin-rm -s f -l force -d '	Force the removal of an active plugin SEE ALSO docker-plugin(1)'

