# docker-context-inspect
# Autogenerated from man page /usr/share/man/man1/docker-context-inspect.1.gz
complete -c docker-context-inspect -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'

