# docker-checkpoint-rm
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint-rm.1.gz
complete -c docker-checkpoint-rm -l checkpoint-dir -d '	Use a custom checkpoint storage directory SEE ALSO docker-checkpoint(1)'

