# docker-image-history
# Autogenerated from man page /usr/share/man/man1/docker-image-history.1.gz
complete -c docker-image-history -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-image-history -s H -l human -d '	Print sizes and dates in human readable format'
complete -c docker-image-history -l no-trunc -d '	Don\'t truncate output'
complete -c docker-image-history -l platform -d '	Show history for the given platform.  Formatted as "os[/arch[/variant]]" (e'
complete -c docker-image-history -s q -l quiet -d '	Only show image IDs SEE ALSO docker-image(1)'

