# docker-image-push
# Autogenerated from man page /usr/share/man/man1/docker-image-push.1.gz
complete -c docker-image-push -s a -l all-tags -d '	Push all tags of an image to the repository'
complete -c docker-image-push -l platform -d '	Push a platform-specific manifest as a single-platform image to the registry'
complete -c docker-image-push -s q -l quiet -d '	Suppress verbose output SEE ALSO docker-image(1)'

