# docker-network-disconnect
# Autogenerated from man page /usr/share/man/man1/docker-network-disconnect.1.gz
complete -c docker-network-disconnect -s f -l force -d '	Force the container to disconnect from a network SEE ALSO docker-network(1)'

