# docker-context-update
# Autogenerated from man page /usr/share/man/man1/docker-context-update.1.gz
complete -c docker-context-update -l description -d '	Description of the context'
complete -c docker-context-update -l docker -d '	set the docker endpoint SEE ALSO docker-context(1)'

