# docker-plugin-install
# Autogenerated from man page /usr/share/man/man1/docker-plugin-install.1.gz
complete -c docker-plugin-install -l alias -d '	Local name for plugin'
complete -c docker-plugin-install -l disable -d '	Do not enable the plugin on install'
complete -c docker-plugin-install -l grant-all-permissions -d '	Grant all permissions necessary to run the plugin SEE ALSO docker-plugin(1)'

