# docker-container-exec
# Autogenerated from man page /usr/share/man/man1/docker-container-exec.1.gz
complete -c docker-container-exec -l privileged -d 'USER user sets the username or UID used and optionally the groupname or GID f…'
complete -c docker-container-exec -s d -l detach -d '	Detached mode: run command in the background'
complete -c docker-container-exec -l detach-keys -d '	Override the key sequence for detaching a container'
complete -c docker-container-exec -s e -l env -d '	Set environment variables'
complete -c docker-container-exec -l env-file -d '	Read in a file of environment variables'
complete -c docker-container-exec -s i -l interactive -d '	Keep STDIN open even if not attached'
complete -c docker-container-exec -s t -l tty -d '	Allocate a pseudo-TTY'
complete -c docker-container-exec -s u -l user -d '	Username or UID (format: "[:]")'
complete -c docker-container-exec -s w -l workdir -d '	Working directory inside the container SEE ALSO docker-container(1)'

