# docker-volume-create
# Autogenerated from man page /usr/share/man/man1/docker-volume-create.1.gz
complete -c docker-volume-create -s o -l opt -d '$ docker volume create --driver fake --opt tardis=blue --opt timey=wimey Thes…'
complete -c docker-volume-create -l availability -d '	Cluster Volume availability ("active", "pause", "drain")'
complete -c docker-volume-create -s d -l driver -d '	Specify volume driver name'
complete -c docker-volume-create -l group -d '	Cluster Volume group (cluster volumes)'
complete -c docker-volume-create -l label -d '	Set metadata for a volume'
complete -c docker-volume-create -l limit-bytes -d '	Minimum size of the Cluster Volume in bytes'
complete -c docker-volume-create -l required-bytes -d '	Maximum size of the Cluster Volume in bytes'
complete -c docker-volume-create -l scope -d '	Cluster Volume access scope ("single", "multi")'
complete -c docker-volume-create -l secret -d '	Cluster Volume secrets'
complete -c docker-volume-create -l sharing -d '	Cluster Volume access sharing ("none", "readonly", "onewriter", "all")'
complete -c docker-volume-create -l topology-preferred -d '	A topology that the Cluster Volume would be preferred in'
complete -c docker-volume-create -l topology-required -d '	A topology that the Cluster Volume must be accessible from'
complete -c docker-volume-create -l type -d '	Cluster Volume access type ("mount", "block") SEE ALSO docker-volume(1)'

