# docker-inspect
# Autogenerated from man page /usr/share/man/man1/docker-inspect.1.gz
complete -c docker-inspect -s f -l format -d '	Format output using a custom template: \'json\':             Print in JSON for…'
complete -c docker-inspect -s s -l size -d '	Display total file sizes if the type is container'
complete -c docker-inspect -l type -d '	Only inspect objects of the given type SEE ALSO docker(1)'

