# docker-system-df
# Autogenerated from man page /usr/share/man/man1/docker-system-df.1.gz
complete -c docker-system-df -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-system-df -s v -l verbose -d '	Show detailed information on space usage SEE ALSO docker-system(1)'

