# docker-network-ls
# Autogenerated from man page /usr/share/man/man1/docker-network-ls.1.gz
complete -c docker-network-ls -s f -s f -d 'The currently supported filters are: o 2 driver o 2 id (network\'s id) o 2 lab…'
complete -c docker-network-ls -l filter -d '	Provide filter values (e. g.  "driver=bridge")'
complete -c docker-network-ls -l format -d '	Format output using a custom template: \'table\':            Print output in t…'
complete -c docker-network-ls -l no-trunc -d '	Do not truncate the output'
complete -c docker-network-ls -s q -l quiet -d '	Only display network IDs SEE ALSO docker-network(1)'

