# docker-container-prune
# Autogenerated from man page /usr/share/man/man1/docker-container-prune.1.gz
complete -c docker-container-prune -l filter -d '	Provide filter values (e. g.  "until=")'
complete -c docker-container-prune -s f -l force -d '	Do not prompt for confirmation SEE ALSO docker-container(1)'

