# docker-image-rm
# Autogenerated from man page /usr/share/man/man1/docker-image-rm.1.gz
complete -c docker-image-rm -s f -l force -d '	Force removal of the image'
complete -c docker-image-rm -l no-prune -d '	Do not delete untagged parents'
complete -c docker-image-rm -l platform -d '	Remove only the given platform variant'

