# docker-push
# Autogenerated from man page /usr/share/man/man1/docker-push.1.gz
complete -c docker-push -s a -l all-tags -d '	Push all tags of an image to the repository'
complete -c docker-push -l platform -d '	Push a platform-specific manifest as a single-platform image to the registry'
complete -c docker-push -s q -l quiet -d '	Suppress verbose output SEE ALSO docker(1)'

