# docker-import
# Autogenerated from man page /usr/share/man/man1/docker-import.1.gz
complete -c docker-import -s c -l change -d '	Apply Dockerfile instruction to the created image'
complete -c docker-import -s m -l message -d '	Set commit message for imported image'
complete -c docker-import -l platform -d '	Set platform if server is multi-platform capable SEE ALSO docker(1)'

