# docker-container-stop
# Autogenerated from man page /usr/share/man/man1/docker-container-stop.1.gz
complete -c docker-container-stop -s s -l signal -d '	Signal to send to the container'
complete -c docker-container-stop -s t -l timeout -d '	Seconds to wait before killing the container SEE ALSO docker-container(1)'

