# docker-login
# Autogenerated from man page /usr/share/man/man1/docker-login.1.gz
complete -c docker-login -s p -l password -d '	Password or Personal Access Token (PAT)'
complete -c docker-login -l password-stdin -d '	Take the Password or Personal Access Token (PAT) from stdin'
complete -c docker-login -s u -l username -d '	Username SEE ALSO docker(1)'

