# dpauxmon
# Autogenerated from man page /usr/share/man/man1/dpauxmon.1.gz
complete -c dpauxmon -l help
complete -c dpauxmon -l version
complete -c dpauxmon -l extcap-interfaces
complete -c dpauxmon -l extcap-interface
complete -c dpauxmon -l extcap-dlts
complete -c dpauxmon -l extcap-config
complete -c dpauxmon -l capture
complete -c dpauxmon -l fifo
complete -c dpauxmon -l interface_idt

