# dump.exfat
# Autogenerated from man page /usr/share/man/man8/dump.exfat.8.gz
complete -c 'dump.exfat' -s V -d 'Prints the version number and exits'
complete -c 'dump.exfat' -s d -l dentry-set -d 'Print information of directory entries from a given path that exits in the gi…'
complete -c 'dump.exfat' -s s -l scan-dir -d 'Scan and print information of directory entries from a given path that exits …'
complete -c 'dump.exfat' -s r -l recursive -d 'Scan and print information of directory entries from a given path recursively…'
complete -c 'dump.exfat' -s c -l cluster-chain -d 'Print the cluster chain while printing the directory entry information'

