# dump_mfts
# Autogenerated from man page /usr/share/man/man8/dump_mfts.8.gz
complete -c dump_mfts -s a -l all -d 'show all lids in range, even invalid entries'
complete -c dump_mfts -s n -l no_dests -d 'do not try to resolve destinations'
complete -c dump_mfts -s M -l Multicast -d 'show multicast forwarding tables In this case, the range parameters are speci…'
complete -c dump_mfts -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c dump_mfts -s e -d 'show send and receive errors (timeouts and others)'
complete -c dump_mfts -s v -l verbose -d 'increase the application verbosity level'
complete -c dump_mfts -s y -l m_key -d 'use the specified M_key for requests'
complete -c dump_mfts -s C -l Ca
complete -c dump_mfts -s P -l Port -d 'Local port Selection'
complete -c dump_mfts -s h -l help
complete -c dump_mfts -s V -l version -d 'Configuration flags'
complete -c dump_mfts -s t -l timeout
complete -c dump_mfts -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c dump_mfts -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

