# dumpcap
# Autogenerated from man page /usr/share/man/man1/dumpcap.1.gz
complete -c dumpcap -s a -l autostop -d 'Specify a criterion that specifies when Dumpcap is to stop writing to a captu…'
complete -c dumpcap -s b -l ring-buffer -d 'Cause Dumpcap to run in "multiple files" mode'
complete -c dumpcap -s B -l buffer-size -d 'Set capture buffer size (in MiB, default is 2 MiB)'
complete -c dumpcap -s c
complete -c dumpcap -s C
complete -c dumpcap -s d
complete -c dumpcap -s D -l list-interfaces
complete -c dumpcap -s f -d 'Set the capture filter expression'
complete -c dumpcap -s F
complete -c dumpcap -s g
complete -c dumpcap -s h -l help
complete -c dumpcap -s i -l interface -d 'Set the name of the network interface or pipe to use for live packet capture'
complete -c dumpcap -s P
complete -c dumpcap -l 'ifdescr>'
complete -c dumpcap -l 'ifname>'
complete -c dumpcap -s I -l monitor-mode -d 'Put the interface in "monitor mode"; this is supported only on IEEE 802'
complete -c dumpcap -s k -d 'Set the channel on the interface; this is supported only on IEEE 802'
complete -c dumpcap -s L -l list-data-link-types
complete -c dumpcap -s M -d 'When used with -D, -L, -S or --list-time-stamp-types print machine-readable o…'
complete -c dumpcap -s n
complete -c dumpcap -s N -d 'Limit the number of packets used for storing captured packets in memory while…'
complete -c dumpcap -s p -l no-promiscuous-mode -d 'Don\'t put the interface into promiscuous mode'
complete -c dumpcap -s q -d 'When capturing packets, don\'t display the continuous count of packets capture…'
complete -c dumpcap -s Q -d 'When capturing packets, don\'t display, on the standard error, the initial mes…'
complete -c dumpcap -s s -l snapshot-length -d 'Set the default snapshot length to use when capturing live data'
complete -c dumpcap -s S
complete -c dumpcap -s t
complete -c dumpcap -l temp-dir -d 'Specifies the directory into which temporary files (including capture files) …'
complete -c dumpcap -s v -l version
complete -c dumpcap -s w
complete -c dumpcap -s y -l linktype -d 'Set the data link type to use while capturing packets'
complete -c dumpcap -l application-flavor
complete -c dumpcap -l capture-comment -d 'Add a capture comment to the output file, if supported by the output file for…'
complete -c dumpcap -l list-time-stamp-types
complete -c dumpcap -l time-stamp-type
complete -c dumpcap -l update-interval
complete -c dumpcap -l log-level
complete -c dumpcap -l log-fatal
complete -c dumpcap -l log-domains
complete -c dumpcap -l log-debug
complete -c dumpcap -l log-noisy
complete -c dumpcap -l log-fatal-domains
complete -c dumpcap -l log-file

