# ecm
# Autogenerated from man page /usr/share/man/man1/ecm.1.gz
complete -c ecm -s k -d 'option.  All primes B1 <= p <= B2 are processed in step 2'
complete -c ecm -o pm1
complete -c ecm -o pp1
complete -c ecm -o x0
complete -c ecm -o sigma
complete -c ecm -s A
complete -c ecm -o go
complete -c ecm -o treefile
complete -c ecm -o power
complete -c ecm -o dickson
complete -c ecm -o maxmem
complete -c ecm -o ntt -o no-ntt
complete -c ecm -s q
complete -c ecm -s v
complete -c ecm -o timestamp
complete -c ecm -o mpzmod
complete -c ecm -o modmuln
complete -c ecm -o redc
complete -c ecm -o nobase2
complete -c ecm -o base2
complete -c ecm -o inp
complete -c ecm -o save
complete -c ecm -o savea
complete -c ecm -o resume
complete -c ecm -o chkpoint
complete -c ecm -s c
complete -c ecm -o one
complete -c ecm -s b
complete -c ecm -s d
complete -c ecm -o ve
complete -c ecm -s i
complete -c ecm -s I
complete -c ecm -o prpcmd
complete -c ecm -o faccmd
complete -c ecm -o idlecmd
complete -c ecm -s n
complete -c ecm -o nn
complete -c ecm -o B2scale
complete -c ecm -o stage1time
complete -c ecm -o cofdec
complete -c ecm -s h -l help
complete -c ecm -o printconfig

