# editcap
# Autogenerated from man page /usr/share/man/man1/editcap.1.gz
complete -c editcap -s a -d 'For the specified frame number, assign the given comment string'
complete -c editcap -s A -d 'Reads only the packets whose timestamp is on or after <start time>'
complete -c editcap -s B -d 'Reads only the packets whose timestamp is before <stop time>'
complete -c editcap -s c -d 'Splits the packet output to different files based on uniform packet counts wi…'
complete -c editcap -s C -d 'Sets the chop length to use when writing the packet data'
complete -c editcap -s d -d 'Attempts to remove duplicate packets'
complete -c editcap -s D -d 'Attempts to remove duplicate packets'
complete -c editcap -s E -d 'Sets the probability that bytes in the output file are randomly changed'
complete -c editcap -s F -d 'Sets the file format of the output capture file'
complete -c editcap -s h -l help
complete -c editcap -s i -d 'Splits the packet output to different files based on uniform time intervals u…'
complete -c editcap -s I -d 'Ignore the specified number of bytes at the beginning of the frame during MD5…'
complete -c editcap -s L -d 'Adjust the original frame length accordingly when chopping and/or snapping (i…'
complete -c editcap -s o -d 'When used in conjunction with -E, skip some bytes from the beginning of the p…'
complete -c editcap -s r -d 'Reverse the packet selection'
complete -c editcap -s R -d 'For the specified frame number, assign the given timestamp'
complete -c editcap -s s -d 'Sets the snapshot length to use when writing the data'
complete -c editcap -l seed -d 'When used in conjunction with -E, set the seed for the pseudo-random number g…'
complete -c editcap -l skip-radiotap-header -d 'Skip the radiotap header of each frame when checking for packet duplicates'
complete -c editcap -s S -d 'Time adjust selected packets to ensure strict chronological order'
complete -c editcap -s t -d 'Sets the time adjustment to use on selected packets'
complete -c editcap -s T -d 'Sets the packet encapsulation type of the output capture file'
complete -c editcap -s v -l version
complete -c editcap -s V -d 'Causes editcap to print verbose messages while it\'s working'
complete -c editcap -s w -d 'Attempts to remove duplicate packets'
complete -c editcap -l inject-secrets -d 'Inserts the contents of <file> into a Decryption Secrets Block (DSB) within t…'
complete -c editcap -l extract-secrets -d 'Extracts each Decryption Secrets Block (DSB) contained within infile'
complete -c editcap -l discard-all-secrets -d 'Discard all decryption secrets from the input file when writing the output fi…'
complete -c editcap -l capture-comment -d 'Adds the given comment to the output file, if supported by the output file fo…'
complete -c editcap -l discard-capture-comment -d 'Discard all capture file comments from the input file when writing the output…'
complete -c editcap -l set-unused -d 'Set the unused bytes (if any) to zero in SLL link type'
complete -c editcap -l discard-packet-comments -d 'Discard all packet comments from the input file when writing the output file'
complete -c editcap -l preserve-packet-comments -d 'When adding a new packet comment with the -a option preserve from the input f…'
complete -c editcap -l compress -d 'Compress the output file using the type compression format'
complete -c editcap -l log-level
complete -c editcap -l log-fatal
complete -c editcap -l log-domains
complete -c editcap -l log-debug
complete -c editcap -l log-noisy
complete -c editcap -l log-fatal-domains
complete -c editcap -l log-file

