# etwdump
# Autogenerated from man page /usr/share/man/man1/etwdump.1.gz
complete -c etwdump -l help
complete -c etwdump -l version
complete -c etwdump -l extcap-interfaces
complete -c etwdump -l extcap-interface
complete -c etwdump -l extcap-dlts
complete -c etwdump -l extcap-config
complete -c etwdump -l capture
complete -c etwdump -l fifo
complete -c etwdump -l iue
complete -c etwdump -l etlfile
complete -c etwdump -l params

