# falcodump
# Autogenerated from man page /usr/share/man/man1/falcodump.1.gz
complete -c falcodump -l help
complete -c falcodump -l version
complete -c falcodump -l plugin-api-version
complete -c falcodump -l extcap-interfaces
complete -c falcodump -l extcap-interface
complete -c falcodump -l extcap-dlts
complete -c falcodump -l extcap-config
complete -c falcodump -l extcap-capture-filter
complete -c falcodump -l capture
complete -c falcodump -l fifo
complete -c falcodump -l plugin-source
complete -c falcodump -l log-level
complete -c falcodump -l log-file
complete -c falcodump -l include-capture-processes
complete -c falcodump -l include-switch-calls
complete -c falcodump -l cloudtrail-s3downloadconcurrency
complete -c falcodump -l cloudtrail-s3interval
complete -c falcodump -l cloudtrail-s3accountlist
complete -c falcodump -l cloudtrail-sqsdelete
complete -c falcodump -l cloudtrail-useasync
complete -c falcodump -l cloudtrail-uses3sns
complete -c falcodump -l cloudtrail-aws-profile
complete -c falcodump -l cloudtrail-aws-region
complete -c falcodump -l cloudtrail-aws-config
complete -c falcodump -l cloudtrail-aws-credentials

