# flac
# Autogenerated from man page /usr/share/man/man1/flac.1.gz
complete -c flac -l 'tag\\f' -d 'Add a FLAC tag.  The comment must adhere to the Vorbis comment spec; i. e'
complete -c flac -s 8 -l fast -l best -d 'actually are just synonyms for different groups of specific encoding options …'
complete -c flac -s d -s a
complete -c flac -s t -d 'Depending on which way is chosen, encoding, decoding, analysis or testing opt…'
complete -c flac -s o
complete -c flac -s 3 -s f -o fo -o 3mVj2 -d 'flac also employs the convention that -- (with whitespace!) signifies end of …'
complete -c flac -o do -d 'The decoder can force other output formats, or different versions of the WAVE…'
complete -c flac -s v -l version -d 'Show the flac version number, and quit'
complete -c flac -s h -l help -d 'Show basic usage and a list of all options, and quit'
complete -c flac -l decode -d 'Decode (the default behavior is to encode)'
complete -c flac -l test -d 'Test a flac encoded file'
complete -c flac -l analyze -d 'Analyze a FLAC encoded file'
complete -c flac -s c -l stdout -d 'Write output to stdout'
complete -c flac -l force -d 'Force overwriting of output files'
complete -c flac -l delete-input-file -d 'Automatically delete the input file after a successful encode or decode'
complete -c flac -l output-name -d 'Force the output file name (usually flac just changes the extension)'
complete -c flac -l output-prefix -d 'Prefix each output file name with the given string'
complete -c flac -l preserve-modtime -d '(Enabled by default'
complete -c flac -l keep-foreign-metadata -d 'If encoding, save WAVE, RF64, or AIFF non-audio chunks in FLAC metadata'
complete -c flac -l keep-foreign-metadata-if-present -d 'Like --keep-foreign-metadata, but without throwing an error if foreign metada…'
complete -c flac -l skip -d 'Skip the first number of samples of the input'
complete -c flac -l until -d 'Stop at the given sample number (which is not included)'
complete -c flac -l no-utf8-convert -d 'Do not convert tags from local charset to UTF-8'
complete -c flac -s s -l silent -d 'Silent mode (do not write runtime encode/decode statistics to stderr)'
complete -c flac -l totally-silent -d 'Do not print anything of any kind, including warnings or errors'
complete -c flac -s w -l warnings-as-errors -d 'Treat all warnings as errors (which cause flac to terminate with a non-zero e…'
complete -c flac -s F -l decode-through-errors -d 'By default flac stops decoding with an error message and removes the partiall…'
complete -c flac -l cue -d 'Set the beginning and ending cuepoints to decode'
complete -c flac -l apply-replaygain-which-is-not-lossless -d 'Applies ReplayGain values while decoding.  WARNING: THIS IS NOT LOSSLESS'
complete -c flac -s V -l verify -d 'Verify a correct encoding by decoding the output in parallel and comparing to…'
complete -c flac -s 0 -l compression-level-0 -d 'Fastest compression preset.  Currently synonymous with'
complete -c flac -s l -s b -s r -l no-mid-side
complete -c flac -s 1 -l compression-level-1 -d 'Currently synonymous with -l 0 -b 1152 -M -r 3'
complete -c flac -s 2 -l compression-level-2 -d 'Currently synonymous with -l 0 -b 1152 -m -r 3'
complete -c flac -l compression-level-3 -d 'Currently synonymous with'
complete -c flac -s 4 -l compression-level-4 -d 'Currently synonymous with -l 8 -b 4096 -M -r 4'
complete -c flac -s 5 -l compression-level-5 -d 'Currently synonymous with -l 8 -b 4096 -m -r 5'
complete -c flac -s 6 -l compression-level-6 -d 'Currently synonymous with'
complete -c flac -s m -s A
complete -c flac -s 7 -l compression-level-7 -d 'Currently synonymous with'
complete -c flac -l compression-level-8 -d 'Currently synonymous with'
complete -c flac -l max-lpc-order -d 'Specifies the maximum LPC order.  This number must be <= 32'
complete -c flac -l blocksize -d 'Specify the blocksize in samples'
complete -c flac -l mid-side -d 'Try mid-side coding for each frame (stereo only, otherwise ignored)'
complete -c flac -s M -l adaptive-mid-side -d 'Adaptive mid-side coding for all frames (stereo only, otherwise ignored)'
complete -c flac -l rice-partition-order -d 'Set the [min,]max residual partition order (0. 15)'
complete -c flac -l apodization -d 'Window audio data with given apodization function'
complete -c flac -s e -l exhaustive-model-search -d 'Do exhaustive model search (expensive!)'
complete -c flac -s q -l qlp-coeff-precision -d 'Precision of the quantized linear-predictor coefficients'
complete -c flac -s p -l qlp-coeff-precision-search -d 'Do exhaustive search of LP coefficient quantization (expensive!)'
complete -c flac -l lax -d 'Allow encoder to generate non-Subset files'
complete -c flac -l limit-min-bitrate -d 'Limit minimum bitrate by not allowing frames consisting of only constant subf…'
complete -c flac -s j -l threads -d 'Try to set a maximum number of threads to use for encoding'
complete -c flac -l ignore-chunk-sizes -d 'When encoding to flac, ignore the file size headers in WAV and AIFF files to …'
complete -c flac -l replay-gain -d 'Calculate ReplayGain values and store them as FLAC tags, similar to vorbisgain'
complete -c flac -l cuesheet -d 'Import the given cuesheet file and store it in a CUESHEET metadata block'
complete -c flac -l picture -d 'Import a picture and store it in a PICTURE metadata block'
complete -c flac -s S -l seekpoint -d 'Specifies point(s) to include in SEEKTABLE, to override the encoder[cq]s defa…'
complete -c flac -s P -l padding -d '(Default: 8192 bytes, although 65536 for input above 20 minutes'
complete -c flac -s T -l tag -d 'Add a FLAC tag.  The comment must adhere to the Vorbis comment spec; i. e'
complete -c flac -l tag-from-file -d 'Like --tag, except FILENAME is a file whose contents will be read verbatim to…'
complete -c flac -l ogg -d 'When encoding, generate Ogg FLAC output instead of native FLAC'
complete -c flac -l serial-number -d 'When used with --ogg, specifies the serial number to use for the first Ogg FL…'
complete -c flac -l force-aiff-format
complete -c flac -l force-rf64-format
complete -c flac -l force-wave64-format -d 'output format and force output to AIFF/RF64/WAVE64, respectively'
complete -c flac -l force-legacy-wave-format
complete -c flac -l force-extensible-wave-format -d 'output a WAVE file with WAVE_FORMAT_PCM and WAVE_FORMAT_EXTENSIBLE respective…'
complete -c flac -l force-aiff-c-none-format
complete -c flac -l force-aiff-c-sowt-format -d 'output an AIFF-C file with format NONE and sowt respectively'
complete -c flac -l force-raw-format -d 'Force input (when encoding) or output (when decoding) to be treated as raw sa…'
complete -c flac -l sign -d 'Specify the sign of samples'
complete -c flac -l endian -d 'Specify the byte order for samples'
complete -c flac -l channels -d '(Input only) specify number of channels'
complete -c flac -l bps -d '(Input only) specify bits per sample (per channel: 16 for CDDA. )'
complete -c flac -l sample-rate -d '(Input only) specify sample rate (in Hz.  Only integers supported. )'
complete -c flac -l input-size -d '(Input only) specify the size of the raw input in bytes'
complete -c flac -l residual-text -d 'Includes the residual signal in the analysis file'
complete -c flac -l residual-gnuplot -d 'Generates a gnuplot file for every subframe; each file will contain the resid…'
complete -c flac -l no-adaptive-mid-side
complete -c flac -l no-cued-seekpoints
complete -c flac -l no-decode-through-errors
complete -c flac -l no-delete-input-file
complete -c flac -l no-preserve-modtime
complete -c flac -l no-keep-foreign-metadata
complete -c flac -l no-exhaustive-model-search
complete -c flac -l no-force
complete -c flac -l no-lax
complete -c flac -l no-ogg
complete -c flac -l no-padding
complete -c flac -l no-qlp-coeff-prec-search
complete -c flac -l no-replay-gain
complete -c flac -l no-residual-gnuplot
complete -c flac -l no-residual-text
complete -c flac -l no-seektable
complete -c flac -l no-silent
complete -c flac -l no-verify
complete -c flac -l no-warnings-as-errors -d 'ReplayGain application specification The option'

