# fuzzel
# Autogenerated from man page /usr/share/man/man1/fuzzel.1.gz
complete -c fuzzel -l config
complete -c fuzzel -l check-config
complete -c fuzzel -s n -l namespace
complete -c fuzzel -l cache
complete -c fuzzel -s o -l output
complete -c fuzzel -s f -l font
complete -c fuzzel -l use-bold
complete -c fuzzel -s D -l dpi-aware
complete -c fuzzel -l gamma-correct
complete -c fuzzel -s p -l prompt
complete -c fuzzel -l prompt-only
complete -c fuzzel -l hide-prompt
complete -c fuzzel -l placeholder
complete -c fuzzel -l mesg
complete -c fuzzel -l mesg-mode
complete -c fuzzel -l search
complete -c fuzzel -s i
complete -c fuzzel -l icon-theme
complete -c fuzzel -s I -l no-icons
complete -c fuzzel -l hide-before-typing
complete -c fuzzel -s F -l fields
complete -c fuzzel -l password
complete -c fuzzel -s T -l terminal
complete -c fuzzel -s a -l anchor
complete -c fuzzel -l x-margin
complete -c fuzzel -l y-margin
complete -c fuzzel -l select
complete -c fuzzel -l auto-select
complete -c fuzzel -l select-index
complete -c fuzzel -s l -l lines
complete -c fuzzel -l minimal-lines
complete -c fuzzel -s w -l width
complete -c fuzzel -l tabs
complete -c fuzzel -s x -l horizontal-pad
complete -c fuzzel -s y -l vertical-pad
complete -c fuzzel -s P -l inner-pad
complete -c fuzzel -s b -l background
complete -c fuzzel -s t -l text-color
complete -c fuzzel -l message-color
complete -c fuzzel -l prompt-color
complete -c fuzzel -l placeholder-color
complete -c fuzzel -l input-color
complete -c fuzzel -s m -l match-color
complete -c fuzzel -s s -l selection-color
complete -c fuzzel -s S -l selection-text-color
complete -c fuzzel -s M -l selection-match-color
complete -c fuzzel -l selection-radius
complete -c fuzzel -l counter-color
complete -c fuzzel -s B -l border-width
complete -c fuzzel -s r -l border-radius
complete -c fuzzel -s C -l border-color
complete -c fuzzel -l show-actions
complete -c fuzzel -l match-mode
complete -c fuzzel -l no-sort
complete -c fuzzel -l counter
complete -c fuzzel -l filter-desktop
complete -c fuzzel -l fuzzy-min-length
complete -c fuzzel -l fuzzy-max-length-discrepancy
complete -c fuzzel -l fuzzy-max-distance
complete -c fuzzel -l line-height
complete -c fuzzel -l letter-spacing
complete -c fuzzel -l layer
complete -c fuzzel -l keyboard-focus
complete -c fuzzel -l no-exit-on-keyboard-focus-loss
complete -c fuzzel -l launch-prefix
complete -c fuzzel -l list-executables-in-path
complete -c fuzzel -l render-workers
complete -c fuzzel -l match-workers
complete -c fuzzel -l delayed-filter-ms
complete -c fuzzel -l delayed-filter-limit
complete -c fuzzel -l scaling-filter
complete -c fuzzel -s d -l dmenu
complete -c fuzzel -l dmenu0
complete -c fuzzel -l index
complete -c fuzzel -l with-nth
complete -c fuzzel -l nth-delimiter -d 'input line is printed on stdout.  dmenu mode only'
complete -c fuzzel -l accept-nth
complete -c fuzzel -l match-nth
complete -c fuzzel -l only-match
complete -c fuzzel -s R -l no-run-if-empty
complete -c fuzzel -l log-level
complete -c fuzzel -l log-colorize
complete -c fuzzel -l log-no-syslog
complete -c fuzzel -l print-timing-info
complete -c fuzzel -l no-mouse
complete -c fuzzel -s v -l version

