# gegps
# Autogenerated from man page /usr/share/man/man1/gegps.1.gz
complete -c gegps -s '?' -s h -l help
complete -c gegps -s d -l kmldir
complete -c gegps -s D -l debug
complete -c gegps -l device
complete -c gegps -l host
complete -c gegps -s i -l initialize
complete -c gegps -l port
complete -c gegps -s V -l version

