# gnome-session
# Autogenerated from man page /usr/share/man/man1/gnome-session.1.gz
complete -c gnome-session -l session -d 'Use the applications defined in SESSION. session.  If not specified, gnome'
complete -c gnome-session -l debug -d 'Enable debugging code'

