# gnome-service-client
# Autogenerated from man page /usr/share/man/man1/gnome-service-client.1.gz
complete -c gnome-service-client -l help -s h -d 'Show a help message and exit'
complete -c gnome-service-client -l tag -s t -d 'Optionally specifies the tag to set for all windows of the client.  EXAMPLES'

