# gpgme-json
# Autogenerated from man page /usr/share/man/man1/gpgme-json.1.gz
complete -c gpgme-json -s i -d 'TQ   --interactive Enable interactive mode'
complete -c gpgme-json -s s -d 'TQ   --single Enable single request mode'
complete -c gpgme-json -l identify -d 'Identify the type of the data found in \'file\' or standard input -'
complete -c gpgme-json -l debug -d 'Enable debug mode.  Logs are saved to to \'~/. gnupg/S. gpgme-json. log\''
complete -c gpgme-json -l lib-version -d 'Print GPGME library version'
complete -c gpgme-json -l interactive -d 'Enable interactive mode.   Interactive mode also provides some online help'
complete -c gpgme-json -l single -d 'Enable single request mode'
complete -c gpgme-json -s h
complete -c gpgme-json -l help -d 'Print a usage message summarizing the most useful command-line options'

