# gprofng-display-text
# Autogenerated from man page /usr/share/man/man1/gprofng-display-text.1.gz
complete -c gprofng-display-text -l version -d 'X Item "--version" Print the version number and exit'
complete -c gprofng-display-text -l help -d 'X Item "--help" Print usage information and exit'
complete -c gprofng-display-text -o script

