# gps2udp
# Autogenerated from man page /usr/share/man/man1/gps2udp.1.gz
complete -c gps2udp -s '?' -s h -l help
complete -c gps2udp -o Print
complete -c gps2udp -s a -l ais
complete -c gps2udp -s b -l daemon
complete -c gps2udp -s c -l count
complete -c gps2udp -s d -l debug
complete -c gps2udp -s j -l json
complete -c gps2udp -s n -l nmea
complete -c gps2udp -s t -l tpv
complete -c gps2udp -s u -l udp
complete -c gps2udp -s v -s V -l version

