# gpsctl
# Autogenerated from man page /usr/share/man/man1/gpsctl.1.gz
complete -c gpsctl -s '?' -s h -l help
complete -c gpsctl -s b -l binary
complete -c gpsctl -s c -l rate
complete -c gpsctl -s D -l debug
complete -c gpsctl -s e -l echo
complete -c gpsctl -s f -l force
complete -c gpsctl -s l -l list
complete -c gpsctl -s n -l nmea
complete -c gpsctl -s r -l reset
complete -c gpsctl -s R -l rmshm
complete -c gpsctl -s s -l speed
complete -c gpsctl -s t -l type
complete -c gpsctl -s T -l timeout
complete -c gpsctl -s V -l version
complete -c gpsctl -s x -l ship

