# gpscat
# Autogenerated from man page /usr/share/man/man1/gpscat.1.gz
complete -c gpscat -s '?' -s h -l help
complete -c gpscat -s D -l debug
complete -c gpscat -s p -l packetizer
complete -c gpscat -s s -l speed
complete -c gpscat -s t -l typeflag
complete -c gpscat -s V -l version

