# gpscsv
# Autogenerated from man page /usr/share/man/man1/gpscsv.1.gz
complete -c gpscsv -s '?' -s h -l help
complete -c gpscsv -s c -l class
complete -c gpscsv -l cvt-isotime
complete -c gpscsv -s D -l debug
complete -c gpscsv -l device
complete -c gpscsv -s f -o fields
complete -c gpscsv -l file
complete -c gpscsv -l header
complete -c gpscsv -l host
complete -c gpscsv -s n -l count
complete -c gpscsv -l port
complete -c gpscsv -l separator
complete -c gpscsv -s V -l version
complete -c gpscsv -s x -l seconds

