# gpsdecode
# Autogenerated from man page /usr/share/man/man1/gpsdecode.1.gz
complete -c gpsdecode -s '?' -s h -l help
complete -c gpsdecode -s c -l json
complete -c gpsdecode -s d -l decode
complete -c gpsdecode -s D -l debug
complete -c gpsdecode -s e -l encode
complete -c gpsdecode -s j
complete -c gpsdecode -s m -l minlength
complete -c gpsdecode -s n -l nmea
complete -c gpsdecode -s s -l split24
complete -c gpsdecode -s t -l types
complete -c gpsdecode -s u -l unsscaled
complete -c gpsdecode -s v -l verbose
complete -c gpsdecode -s V -l version

