# gpsd
# Autogenerated from man page /usr/share/man/man8/gpsd.8.gz
complete -c gpsd -s '?' -s h -l -help
complete -c gpsd -s b -l readonly
complete -c gpsd -s D -l debug
complete -c gpsd -s F -l sockfile
complete -c gpsd -s f -l framing
complete -c gpsd -s G -l listenany
complete -c gpsd -s l -l drivers
complete -c gpsd -s n -l nowait
complete -c gpsd -s N -l foreground
complete -c gpsd -s p -l passive
complete -c gpsd -s P -l pidfile
complete -c gpsd -s r -l badtime
complete -c gpsd -l port -s S
complete -c gpsd -s s -l speed
complete -c gpsd -s V -l version
complete -c gpsd -o O2

