# gpsfake
# Autogenerated from man page /usr/share/man/man1/gpsfake.1.gz
complete -c gpsfake -s '?' -s h -l help
complete -c gpsfake -s 1 -l singleshot
complete -c gpsfake -s b -l baton
complete -c gpsfake -s c -l cycle
complete -c gpsfake -s d -l debug
complete -c gpsfake -s g -s G -l gdb -l lldb
complete -c gpsfake -o tui -d 'program output don\'t play nicely together'
complete -c gpsfake -s i -l promptme
complete -c gpsfake -s l -l linedump
complete -c gpsfake -s m -l monitor
complete -c gpsfake -s n -l nowait
complete -c gpsfake -s o -l option
complete -c gpsfake -s p -l pipe
complete -c gpsfake -s P -l port
complete -c gpsfake -s q -l quiet
complete -c gpsfake -s r -l clientinit
complete -c gpsfake -s s -l speed
complete -c gpsfake -s S -l slow
complete -c gpsfake -s t -l tcp
complete -c gpsfake -s T -l sysinfo
complete -c gpsfake -s u -l udp
complete -c gpsfake -s v -l verbose
complete -c gpsfake -s w -l wait
complete -c gpsfake -s x -l predump

