# gpslogntp
# Autogenerated from man page /usr/share/man/man1/gpslogntp.1.gz
complete -c gpslogntp -s h -l help
complete -c gpslogntp -s l -l logfile
complete -c gpslogntp -s o -l once
complete -c gpslogntp -s v -l verbose
complete -c gpslogntp -s w -l wait
complete -c gpslogntp -s V -l version

