# gpsmon
# Autogenerated from man page /usr/share/man/man1/gpsmon.1.gz
complete -c gpsmon -s '?' -s h -l help
complete -c gpsmon -s a -l nocurses
complete -c gpsmon -s d -l debug
complete -c gpsmon -s l -l logfile
complete -c gpsmon -s L -l list
complete -c gpsmon -s n -l nmea
complete -c gpsmon -s t -l type
complete -c gpsmon -s x -d X

