# gpsplot
# Autogenerated from man page /usr/share/man/man1/gpsplot.1.gz
complete -c gpsplot -s '?' -s h -l help
complete -c gpsplot -s b -l backend
complete -c gpsplot -s B -l backends
complete -c gpsplot -s d -l debug
complete -c gpsplot -l device
complete -c gpsplot -l exit
complete -c gpsplot -l fields
complete -c gpsplot -l file
complete -c gpsplot -l host
complete -c gpsplot -l image
complete -c gpsplot -s n -l count
complete -c gpsplot -l plottype
complete -c gpsplot -s p -l port
complete -c gpsplot -s V -l version
complete -c gpsplot -s x -l seconds

