# gpspipe
# Autogenerated from man page /usr/share/man/man1/gpspipe.1.gz
complete -c gpspipe -s '?' -s h -l help
complete -c gpspipe -s 2 -l split24
complete -c gpspipe -s B -l nobuffer
complete -c gpspipe -s d -l daemonize
complete -c gpspipe -s D -l debug
complete -c gpspipe -s l -l sleep
complete -c gpspipe -s n -l count
complete -c gpspipe -s o -l output
complete -c gpspipe -s p -l profile
complete -c gpspipe -s P -l pps
complete -c gpspipe -s r -l nmea
complete -c gpspipe -s R -l raw
complete -c gpspipe -s s -l serial
complete -c gpspipe -s S -l scaled
complete -c gpspipe -s t -l timestamp
complete -c gpspipe -s T -l timefmt
complete -c gpspipe -s u -l usec
complete -c gpspipe -s v -l spinner
complete -c gpspipe -s V -l version
complete -c gpspipe -s w -l json
complete -c gpspipe -s x -l seconds
complete -c gpspipe -s Z -l zulu

