# gpsprof
# Autogenerated from man page /usr/share/man/man1/gpsprof.1.gz
complete -c gpsprof -s '?' -s h -l help
complete -c gpsprof -s d -l dumpfile
complete -c gpsprof -l debug
complete -c gpsprof -s l -l logfile
complete -c gpsprof -s n -l wait
complete -c gpsprof -s r -l redo
complete -c gpsprof -s S -l subtitle
complete -c gpsprof -s t -l title
complete -c gpsprof -s T -l terminal

