# gpsrinex
# Autogenerated from man page /usr/share/man/man1/gpsrinex.1.gz
complete -c gpsrinex -s f
complete -c gpsrinex -s '?' -s h -l help
complete -c gpsrinex -s D -o debug
complete -c gpsrinex -l fileout
complete -c gpsrinex -s F -l filein
complete -c gpsrinex -s g -l gnss
complete -c gpsrinex -s i -l interval
complete -c gpsrinex -s n -l count
complete -c gpsrinex -s V -l version
complete -c gpsrinex -l agency
complete -c gpsrinex -l ant_num
complete -c gpsrinex -l ant_type
complete -c gpsrinex -l comment
complete -c gpsrinex -l marker_name
complete -c gpsrinex -l marker_type
complete -c gpsrinex -l observer
complete -c gpsrinex -l rec_num
complete -c gpsrinex -l rec_type
complete -c gpsrinex -l rec_vers
complete -c gpsrinex -l ant_e
complete -c gpsrinex -l ant_h
complete -c gpsrinex -l ant_n

