# gpssubframe
# Autogenerated from man page /usr/share/man/man1/gpssubframe.1.gz
complete -c gpssubframe -s '?' -s h -l help
complete -c gpssubframe -o Print
complete -c gpssubframe -s c -l count
complete -c gpssubframe -s D -l debug
complete -c gpssubframe -l desc
complete -c gpssubframe -l device
complete -c gpssubframe -l file
complete -c gpssubframe -l host
complete -c gpssubframe -l load
complete -c gpssubframe -s n
complete -c gpssubframe -l port
complete -c gpssubframe -l progress
complete -c gpssubframe -l satpos
complete -c gpssubframe -l save
complete -c gpssubframe -l test
complete -c gpssubframe -l time
complete -c gpssubframe -s V -l version
complete -c gpssubframe -s x -l seconds

