# gpssnmp
# Autogenerated from man page /usr/share/man/man1/gpssnmp.1.gz
complete -c gpssnmp -s '?' -s h -l help
complete -c gpssnmp -s g
complete -c gpssnmp -s n
complete -c gpssnmp -s p -l persist
complete -c gpssnmp -s V -l version

