# gpxlogger
# Autogenerated from man page /usr/share/man/man1/gpxlogger.1.gz
complete -c gpxlogger -s i -l interval
complete -c gpxlogger -s '?' -s h -l help
complete -c gpxlogger -s d -l daemonize
complete -c gpxlogger -s D -l debug
complete -c gpxlogger -s e -l export
complete -c gpxlogger -s f -l output
complete -c gpxlogger -s F -l filein
complete -c gpxlogger -s g -l garmin
complete -c gpxlogger -s l -l exports
complete -c gpxlogger -s m -l minmove
complete -c gpxlogger -s r -l reconnect
complete -c gpxlogger -s V -l version

