# grub-protect
# Autogenerated from man page /usr/share/man/man1/grub-protect.1.gz
complete -c grub-protect -s a -l action -d 'Add or remove a key protector to or from a key'
complete -c grub-protect -s p -l protector -d 'Set key protector to use (only tpm2 is currently supported)'
complete -c grub-protect -l tpm2-asymmetric -d '(ECC_NIST_P256). (default: ECC)'
complete -c grub-protect -l tpm2-bank -d 'Set the bank of PCRs used to authorize key release: SHA1, SHA256, SHA384, or …'
complete -c grub-protect -l tpm2-device -d 'Set the path to the TPM2 device.  (default: \\,/dev/tpm0\\/)'
complete -c grub-protect -l tpm2-evict -d 'Evict a previously persisted SRK from the TPM, if any'
complete -c grub-protect -l tpm2-keyfile -d 'Set the path to a file that contains the cleartext key to protect'
complete -c grub-protect -l tpm2-nvindex -d 'Store the sealed key in a persistent or NV index handle'
complete -c grub-protect -l tpm2-outfile -d 'Set the path to the file that will contain the key after sealing (must be acc…'
complete -c grub-protect -l tpm2-pcrs -d 'Set a comma-separated list of PCRs used to authorize key release e. g'
complete -c grub-protect -l tpm2-srk -d 'Set the SRK handle if the SRK is to be made persistent'
complete -c grub-protect -l tpm2key -d 'Use TPM 2. 0 Key File format'
complete -c grub-protect -s '?' -l help -d 'give this help list'
complete -c grub-protect -l usage -d 'give a short usage message'
complete -c grub-protect -s V -l version -d 'print program version'

