# gtk4-image-tool
# Autogenerated from man page /usr/share/man/man1/gtk4-image-tool.1.gz
complete -c gtk4-image-tool -l undecorated
complete -c gtk4-image-tool -l output -d 'Save the differences as a png image in FILE'
complete -c gtk4-image-tool -l quiet -d 'Don\'t write results to stdout.  Conversion'
complete -c gtk4-image-tool -l format -d 'Convert to the given format'
complete -c gtk4-image-tool -l color-state -d 'Convert to the given color state'
complete -c gtk4-image-tool -l cicp -d 'Convert to a color state that is specified as a cicp tuple'

