# hello_xr
# Autogenerated from man page /usr/share/man/man1/hello_xr.1.gz
complete -c hello_xr -s h -d 'Show brief usage instructions'
complete -c hello_xr -o ff -d 'Specify the form factor to use'
complete -c hello_xr -o vc -d 'Specify the view configuration to use'
complete -c hello_xr -o bm -d 'Specify the environment blend mode to use'
complete -c hello_xr -s s -d 'Specify the space to use'
complete -c hello_xr -s v -d 'Enable verbose logging output from the hello_xr application itself'

