# ib_acme
# Autogenerated from man page /usr/share/man/man1/ib_acme.1.gz
complete -c ib_acme -s f -d 'Specifies the format of the src_addr and dest_addr parameters'
complete -c ib_acme -s s -d 'Specifies the local source address of the path to resolve'
complete -c ib_acme -s d -d 'Specifies the destination address of the path to resolve'
complete -c ib_acme -s v -d 'Indicates that the resolved path information should be verified with the acti…'
complete -c ib_acme -s c -d 'Instructs the ACM service to only returned information that currently resides…'
complete -c ib_acme -s e -d 'Displays one (N = 1, 2, . ) or all endpoints (N = 0 or not present)'
complete -c ib_acme -s P -d 'Queries performance data from the destination service'
complete -c ib_acme -s S -d 'Hostname, IPv4-address or Unix-domain socket of ACM service, default: /run/ib…'
complete -c ib_acme -s C -d 'number of repetitions to perform resolution'
complete -c ib_acme -s A -d 'With this option, the ib_acme utility automatically generates the address con…'
complete -c ib_acme -s O -d 'With this option, the ib_acme utility automatically generates the option conf…'
complete -c ib_acme -s D -d 'Specify the destination directory for the output files'

