# ibacm
# Autogenerated from man page /usr/share/man/man8/ibacm.8.gz
complete -c ibacm -s D -d 'run in daemon mode (default)'
complete -c ibacm -s P -d 'run as standard process'
complete -c ibacm -s A -d 'address configuration file'
complete -c ibacm -s O -d 'option configuration file'

