# ibaddr
# Autogenerated from man page /usr/share/man/man8/ibaddr.8.gz
complete -c ibaddr -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibaddr -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibaddr -s v -l verbose -d 'increase the application verbosity level'
complete -c ibaddr -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibaddr -l gid_show -s g -d 'show gid address only'
complete -c ibaddr -l lid_show -s l -d 'show lid range only'
complete -c ibaddr -l Lid_show -s L -d 'show lid range (in decimal) only Addressing Flags'
complete -c ibaddr -s D -l Direct -d 'Examples:    [options] -D [options] "0"          # self port    [options] -D …'
complete -c ibaddr -s G -l Guid
complete -c ibaddr -s s -l sm_port -d 'Debugging flags'
complete -c ibaddr -s h -l help
complete -c ibaddr -s V -l version -d 'Port Selection flags'
complete -c ibaddr -s C -l Ca
complete -c ibaddr -s P -l Port -d 'Local port Selection'
complete -c ibaddr -s t -l timeout
complete -c ibaddr -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

