# ibcacheedit
# Autogenerated from man page /usr/share/man/man8/ibcacheedit.8.gz
complete -c ibcacheedit -l switchguid -d 'Specify a switchguid that should be changed'
complete -c ibcacheedit -l caguid -d 'Specify a caguid that should be changed'
complete -c ibcacheedit -l sysimgguid -d 'Specify a sysimgguid that should be changed'
complete -c ibcacheedit -l portguid -d 'Specify a portguid that should be changed.   The nodeguid of the port (e. g'
complete -c ibcacheedit -l cache -d OPTIONS
complete -c ibcacheedit -s h -l help
complete -c ibcacheedit -s V -l version -d 'AUTHORS Albert Chu < %<chu11@llnl. gov> >'

