# ibccquery
# Autogenerated from man page /usr/share/man/man8/ibccquery.8.gz
complete -c ibccquery -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibccquery -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibccquery -s v -l verbose -d 'increase the application verbosity level'
complete -c ibccquery -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibccquery -l cckey -s c -d 'Specify a congestion control (CC) key'
complete -c ibccquery -s h -l help
complete -c ibccquery -s V -l version -d 'Addressing Flags'
complete -c ibccquery -s G -l Guid
complete -c ibccquery -s L -l Lid
complete -c ibccquery -s s -l sm_port -d 'Port Selection flags'
complete -c ibccquery -s C -l Ca
complete -c ibccquery -s P -l Port -d 'Local port Selection'
complete -c ibccquery -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

