# ibccconfig
# Autogenerated from man page /usr/share/man/man8/ibccconfig.8.gz
complete -c ibccconfig -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibccconfig -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibccconfig -s v -l verbose -d 'increase the application verbosity level'
complete -c ibccconfig -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibccconfig -l cckey -s c -d 'Specify a congestion control (CC) key'
complete -c ibccconfig -s h -l help
complete -c ibccconfig -s V -l version -d 'Addressing Flags'
complete -c ibccconfig -s G -l Guid
complete -c ibccconfig -s L -l Lid
complete -c ibccconfig -s s -l sm_port -d 'Port Selection flags'
complete -c ibccconfig -s C -l Ca
complete -c ibccconfig -s P -l Port -d 'Local port Selection'
complete -c ibccconfig -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag'

