# ibfindnodesusing
# Autogenerated from man page /usr/share/man/man8/ibfindnodesusing.8.gz
complete -c ibfindnodesusing -s h -d 'show help'
complete -c ibfindnodesusing -s R -d 'Recalculate the ibnetdiscover information, ie do not use the cached informati…'
complete -c ibfindnodesusing -s C
complete -c ibfindnodesusing -s P -d 'FILES CONFIG FILE'

