# ibhosts
# Autogenerated from man page /usr/share/man/man8/ibhosts.8.gz
complete -c ibhosts -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibhosts -s C -l Ca
complete -c ibhosts -s P -l Port
complete -c ibhosts -s t -l timeout
complete -c ibhosts -s h -l help
complete -c ibhosts -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf Local port Selection'

