# ibidsverify
# Autogenerated from man page /usr/share/man/man8/ibidsverify.8.gz
complete -c ibidsverify -s R -d 'Recalculate the ibnetdiscover information, ie do not use the cached informati…'
complete -c ibidsverify -s C
complete -c ibidsverify -s P -d 'EXIT STATUS'

