# iblinkinfo
# Autogenerated from man page /usr/share/man/man8/iblinkinfo.8.gz
complete -c iblinkinfo -l outstanding_smps -s o -d 'Specify the number of outstanding SMP\'s which should be issued during the sca…'
complete -c iblinkinfo -s y -l m_key -d 'use the specified M_key for requests'
complete -c iblinkinfo -s e -d 'show send and receive errors (timeouts and others)'
complete -c iblinkinfo -s v -l verbose -d 'increase the application verbosity level'
complete -c iblinkinfo -l down -s d -d 'Print only nodes which have a port in the "Down" state'
complete -c iblinkinfo -l line -s l -d 'Print all information for each link on one line'
complete -c iblinkinfo -l additional -s p -d 'Print additional port settings (<LifeTime>,<HoqLife>,<VLStallCount>)'
complete -c iblinkinfo -l switches-only -d 'Show only switches in output'
complete -c iblinkinfo -l cas-only -d 'Show only CAs in output.  Partial Scan flags'
complete -c iblinkinfo -l port-guid -s G
complete -c iblinkinfo -s D -l Direct -d 'Examples:    -D "0"          # self port    -D "0,1,2,1,4"  # out via port 1,…'
complete -c iblinkinfo -l switch -s S
complete -c iblinkinfo -l all -s a -d 'Print all nodes found in a partial fabric scan'
complete -c iblinkinfo -l hops -s n -d 'Specify the number of hops away from a specified node to scan'
complete -c iblinkinfo -l load-cache -d 'Load and use the cached ibnetdiscover data stored in the specified filename'
complete -c iblinkinfo -l diff -d 'Load cached ibnetdiscover data and do a diff comparison to the current networ…'
complete -c iblinkinfo -l diffcheck -d 'Specify what diff checks should be done in the --diff option above'
complete -c iblinkinfo -l filterdownports -d 'Filter downports indicated in a ibnetdiscover cache'
complete -c iblinkinfo -s C -l Ca
complete -c iblinkinfo -s P -l Port -d 'Local port Selection'
complete -c iblinkinfo -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf'
complete -c iblinkinfo -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c iblinkinfo -s t -l timeout
complete -c iblinkinfo -s h -l help
complete -c iblinkinfo -s V -l version -d 'EXIT STATUS'

