# ibnetdiscover
# Autogenerated from man page /usr/share/man/man8/ibnetdiscover.8.gz
complete -c ibnetdiscover -l outstanding_smps -s o -d 'Specify the number of outstanding SMP\'s which should be issued during the sca…'
complete -c ibnetdiscover -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibnetdiscover -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibnetdiscover -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibnetdiscover -s v -l verbose -d 'increase the application verbosity level'
complete -c ibnetdiscover -s l -l list -d 'List of connected nodes'
complete -c ibnetdiscover -s g -l grouping -d 'Show grouping'
complete -c ibnetdiscover -s H -l Hca_list -d 'List of connected CAs'
complete -c ibnetdiscover -s S -l Switch_list -d 'List of connected switches'
complete -c ibnetdiscover -s R -l Router_list -d 'List of connected routers'
complete -c ibnetdiscover -s s -l show -d 'Show progress information during discovery'
complete -c ibnetdiscover -s f -l full -d 'Show full information (ports\' speed and width, vlcap)'
complete -c ibnetdiscover -s p -l ports -d 'Obtain a ports report which is a list of connected ports with relevant inform…'
complete -c ibnetdiscover -s m -l max_hops -d 'Report max hops discovered'
complete -c ibnetdiscover -l cache -d 'Cache the ibnetdiscover network data in the specified filename'
complete -c ibnetdiscover -l load-cache -d 'Load and use the cached ibnetdiscover data stored in the specified filename'
complete -c ibnetdiscover -l diff -d 'Load cached ibnetdiscover data and do a diff comparison to the current networ…'
complete -c ibnetdiscover -l diffcheck -d 'Specify what diff checks should be done in the --diff option above'
complete -c ibnetdiscover -s C -l Ca
complete -c ibnetdiscover -s P -l Port -d 'Local port Selection'
complete -c ibnetdiscover -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf'
complete -c ibnetdiscover -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c ibnetdiscover -s t -l timeout
complete -c ibnetdiscover -s h -l help
complete -c ibnetdiscover -s V -l version -d 'FILES CONFIG FILE'

