# ibnodes
# Autogenerated from man page /usr/share/man/man8/ibnodes.8.gz
complete -c ibnodes -s C -l Ca
complete -c ibnodes -s P -l Port
complete -c ibnodes -s t -l timeout
complete -c ibnodes -s h -l help
complete -c ibnodes -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf Local port Selection'

