# ibping
# Autogenerated from man page /usr/share/man/man8/ibping.8.gz
complete -c ibping -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibping -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibping -s v -l verbose -d 'increase the application verbosity level'
complete -c ibping -s c -l count -d 'stop after count packets'
complete -c ibping -s f -l flood -d 'flood destination: send packets back to back without delay'
complete -c ibping -s o -l oui -d 'use specified OUI number to multiplex vendor mads'
complete -c ibping -s S -l Server -d 'start in server mode (do not return) Addressing Flags'
complete -c ibping -s L -l Lid
complete -c ibping -s G -l Guid
complete -c ibping -s s -l sm_port -d 'Port Selection flags'
complete -c ibping -s C -l Ca
complete -c ibping -s P -l Port -d 'Local port Selection'
complete -c ibping -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf'
complete -c ibping -s t -l timeout -d 'Debugging flags'
complete -c ibping -s h -l help
complete -c ibping -s V -l version -d 'FILES CONFIG FILE'

