# ibportstate
# Autogenerated from man page /usr/share/man/man8/ibportstate.8.gz
complete -c ibportstate -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibportstate -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibportstate -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibportstate -s K -l show_keys -d 'show security keys (mkey, smkey, etc. ) associated with the request'
complete -c ibportstate -s v -l verbose -d 'increase the application verbosity level'
complete -c ibportstate -s L -l Lid
complete -c ibportstate -s G -l Guid
complete -c ibportstate -s D -l Direct -d 'Examples:    [options] -D [options] "0"          # self port    [options] -D …'
complete -c ibportstate -s s -l sm_port -d 'Port Selection flags'
complete -c ibportstate -s C -l Ca
complete -c ibportstate -s P -l Port -d 'Local port Selection'
complete -c ibportstate -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf'
complete -c ibportstate -s t -l timeout
complete -c ibportstate -s h -l help
complete -c ibportstate -s V -l version -d 'FILES CONFIG FILE'

