# ibqueryerrors
# Autogenerated from man page /usr/share/man/man8/ibqueryerrors.8.gz
complete -c ibqueryerrors -l outstanding_smps -s o -d 'Specify the number of outstanding SMP\'s which should be issued during the sca…'
complete -c ibqueryerrors -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibqueryerrors -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibqueryerrors -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibqueryerrors -s v -l verbose -d 'increase the application verbosity level'
complete -c ibqueryerrors -s s -l suppress -d 'Suppress the errors listed in the comma separated list provided'
complete -c ibqueryerrors -s c -l suppress-common -d 'Suppress some of the common "side effect" counters'
complete -c ibqueryerrors -s r -l report-port -d 'Report the port information'
complete -c ibqueryerrors -l data -d 'Include the optional transmit and receive data counters'
complete -c ibqueryerrors -l threshold-file -d 'Specify an alternate threshold file'
complete -c ibqueryerrors -l switch
complete -c ibqueryerrors -l ca
complete -c ibqueryerrors -l skip-sl -d 'using a QoS aware routing engine as it can cause a credit deadlock'
complete -c ibqueryerrors -l router
complete -c ibqueryerrors -l clear-errors -s k
complete -c ibqueryerrors -l clear-counts -s K
complete -c ibqueryerrors -l details
complete -c ibqueryerrors -l counters -d 'Partial Scan flags'
complete -c ibqueryerrors -l port-guid -s G
complete -c ibqueryerrors -s D -l Direct -d 'Examples:    -D "0"          # self port    -D "0,1,2,1,4"  # out via port 1,…'
complete -c ibqueryerrors -s S -d 'Cache File flags'
complete -c ibqueryerrors -l load-cache -d 'Load and use the cached ibnetdiscover data stored in the specified filename'
complete -c ibqueryerrors -s C -l Ca
complete -c ibqueryerrors -s P -l Port -d 'Local port Selection'
complete -c ibqueryerrors -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf'
complete -c ibqueryerrors -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c ibqueryerrors -s t -l timeout
complete -c ibqueryerrors -s h -l help
complete -c ibqueryerrors -s V -l version
complete -c ibqueryerrors -s R -d 'EXIT STATUS'
complete -c ibqueryerrors -s 1

