# ibroute
# Autogenerated from man page /usr/share/man/man8/ibroute.8.gz
complete -c ibroute -s a -l all -d 'show all lids in range, even invalid entries'
complete -c ibroute -s n -l no_dests -d 'do not try to resolve destinations'
complete -c ibroute -s M -l Multicast -d 'show multicast forwarding tables In this case, the range parameters are speci…'
complete -c ibroute -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibroute -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibroute -s v -l verbose -d 'increase the application verbosity level'
complete -c ibroute -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibroute -s D -l Direct -d 'Examples:    [options] -D [options] "0"          # self port    [options] -D …'
complete -c ibroute -s G -l Guid
complete -c ibroute -s L -l Lid
complete -c ibroute -s s -l sm_port -d 'Port Selection flags'
complete -c ibroute -s C -l Ca
complete -c ibroute -s P -l Port -d 'Local port Selection'
complete -c ibroute -s h -l help
complete -c ibroute -s V -l version -d 'Configuration flags'
complete -c ibroute -s t -l timeout
complete -c ibroute -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c ibroute -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

