# ibrouters
# Autogenerated from man page /usr/share/man/man8/ibrouters.8.gz
complete -c ibrouters -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibrouters -s C -l Ca
complete -c ibrouters -s P -l Port
complete -c ibrouters -s t -l timeout
complete -c ibrouters -s h -l help
complete -c ibrouters -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf Local port Selection'

