# ibsrpdm
# Autogenerated from man page /usr/share/man/man8/ibsrpdm.8.gz
complete -c ibsrpdm -s c -d 'Generate output suitable for piping directly to a /sys/class/infiniband_srp/s…'
complete -c ibsrpdm -s d -d 'Use device file DEVICE (default /dev/infiniband/umad0)'
complete -c ibsrpdm -s k -d 'Use InfiniBand partition key P_KEY (default 0xffff)'
complete -c ibsrpdm -s v -d 'Print more verbose output'

