# ibswitches
# Autogenerated from man page /usr/share/man/man8/ibswitches.8.gz
complete -c ibswitches -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibswitches -s C -l Ca
complete -c ibswitches -s P -l Port
complete -c ibswitches -s t -l timeout
complete -c ibswitches -s h -l help
complete -c ibswitches -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf Local port Selection'

