# ibsysstat
# Autogenerated from man page /usr/share/man/man8/ibsysstat.8.gz
complete -c ibsysstat -s o -l oui -d 'use specified OUI number to multiplex vendor mads'
complete -c ibsysstat -s S -l Server -d 'start in server mode (do not return)'
complete -c ibsysstat -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibsysstat -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibsysstat -s v -l verbose -d 'increase the application verbosity level'
complete -c ibsysstat -s G -l Guid
complete -c ibsysstat -s L -l Lid
complete -c ibsysstat -s s -l sm_port -d 'Port Selection flags'
complete -c ibsysstat -s C -l Ca
complete -c ibsysstat -s P -l Port -d 'Local port Selection'
complete -c ibsysstat -s h -l help
complete -c ibsysstat -s V -l version -d 'Configuration flags'
complete -c ibsysstat -s t -l timeout
complete -c ibsysstat -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

