# ibtracert
# Autogenerated from man page /usr/share/man/man8/ibtracert.8.gz
complete -c ibtracert -s n -l no_info -d 'simple format; don\'t show additional information'
complete -c ibtracert -s m -d 'show the multicast trace of the specified mlid'
complete -c ibtracert -s f -l force -d 'force route to destination port'
complete -c ibtracert -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c ibtracert -s e -d 'show send and receive errors (timeouts and others)'
complete -c ibtracert -s v -l verbose -d 'increase the application verbosity level'
complete -c ibtracert -s y -l m_key -d 'use the specified M_key for requests'
complete -c ibtracert -s G -l Guid
complete -c ibtracert -s L -l Lid
complete -c ibtracert -s s -l sm_port
complete -c ibtracert -l ports-file -d 'This file contains multiple source and destination lid or guid pairs'
complete -c ibtracert -s C -l Ca
complete -c ibtracert -s P -l Port -d 'Local port Selection'
complete -c ibtracert -s h -l help
complete -c ibtracert -s V -l version -d 'Configuration flags'
complete -c ibtracert -s t -l timeout
complete -c ibtracert -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c ibtracert -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

