# ibv_rc_pingpong
# Autogenerated from man page /usr/share/man/man1/ibv_rc_pingpong.1.gz
complete -c ibv_rc_pingpong -s p -l port -d 'use TCP port PORT for initial synchronization (default 18515)'
complete -c ibv_rc_pingpong -s d -l ib-dev -d 'use IB device DEVICE (default first device found)'
complete -c ibv_rc_pingpong -s i -l ib-port -d 'use IB port PORT (default port 1)'
complete -c ibv_rc_pingpong -s s -l size -d 'ping-pong messages of size SIZE (default 4096)'
complete -c ibv_rc_pingpong -s m -l mtu -d 'path MTU SIZE (default 1024)'
complete -c ibv_rc_pingpong -s r -l rx-depth -d 'post DEPTH receives at a time (default 1000)'
complete -c ibv_rc_pingpong -s n -l iters -d 'perform ITERS message exchanges (default 1000)'
complete -c ibv_rc_pingpong -s l -l sl -d 'use SL as the service level value of the QP (default 0)'
complete -c ibv_rc_pingpong -s e -l events -d 'sleep while waiting for work completion events (default is to poll for comple…'
complete -c ibv_rc_pingpong -s g -l gid-idx -d 'local port GIDINDEX'
complete -c ibv_rc_pingpong -s o -l odp -d 'use on demand paging'
complete -c ibv_rc_pingpong -s P -l prefetch -d 'prefetch an ODP MR'
complete -c ibv_rc_pingpong -s t -l ts -d 'get CQE with timestamp'
complete -c ibv_rc_pingpong -s c -l chk -d 'validate received buffer'
complete -c ibv_rc_pingpong -s j -l dm -d 'use device memory'
complete -c ibv_rc_pingpong -s N -l new_send -d 'use new post send WR API'

