# ibv_xsrq_pingpong
# Autogenerated from man page /usr/share/man/man1/ibv_xsrq_pingpong.1.gz
complete -c ibv_xsrq_pingpong -s p -l port -d 'use TCP port PORT for initial synchronization (default 18515)'
complete -c ibv_xsrq_pingpong -s d -l ib-dev -d 'use IB device DEVICE (default first device found)'
complete -c ibv_xsrq_pingpong -s i -l ib-port -d 'use IB port PORT (default port 1)'
complete -c ibv_xsrq_pingpong -s s -l size -d 'ping-pong messages of size SIZE (default 4096)'
complete -c ibv_xsrq_pingpong -s m -l mtu -d 'use path mtu of size MTU (default 2048)'
complete -c ibv_xsrq_pingpong -s c -l clients -d 'number of clients CLIENTS (on server only, default 1)'
complete -c ibv_xsrq_pingpong -s n -l num-tests -d 'perform NUM_TESTS tests per client (default 5)'
complete -c ibv_xsrq_pingpong -s l -l sl -d 'use SL as the service level value (default 0)'
complete -c ibv_xsrq_pingpong -s e -l events -d 'sleep while waiting for work completion events (default is to poll for comple…'
complete -c ibv_xsrq_pingpong -s g -l gid-idx -d 'local port GIDINDEX'

