# idevicebtlogger
# Autogenerated from man page /usr/share/man/man1/idevicebtlogger.1.gz
complete -c idevicebtlogger -s u -l udid -d 'target specific device by UDID'
complete -c idevicebtlogger -s n -l network -d 'connect to network device'
complete -c idevicebtlogger -s f -l format -d 'set log format: PacketLogger (default), or pcap'
complete -c idevicebtlogger -s x -l exit -d 'exit when device disconnects'
complete -c idevicebtlogger -s d -l debug -d 'enable communication debugging'
complete -c idevicebtlogger -s h -l help -d 'prints usage information'
complete -c idevicebtlogger -s v -l version -d 'prints version information'

