# idevicedevmodectl
# Autogenerated from man page /usr/share/man/man1/idevicedevmodectl.1.gz
complete -c idevicedevmodectl -s u -l udid -d 'target specific device by UDID'
complete -c idevicedevmodectl -s n -l network -d 'connect to network device'
complete -c idevicedevmodectl -s d -l debug -d 'enable communication debugging'
complete -c idevicedevmodectl -s h -l help -d 'print usage information'
complete -c idevicedevmodectl -s v -l version -d 'print version information'

