# idevicenotificationproxy
# Autogenerated from man page /usr/share/man/man1/idevicenotificationproxy.1.gz
complete -c idevicenotificationproxy -s u -l udid -d 'Target specific device by UDID'
complete -c idevicenotificationproxy -s i -l insecure -d 'Connect to insecure notification proxy (for non-paired devices)'
complete -c idevicenotificationproxy -s n -l network -d 'Connect to network device'
complete -c idevicenotificationproxy -s d -l debug -d 'Enable communication debugging'
complete -c idevicenotificationproxy -s h -l help -d 'Prints usage information'
complete -c idevicenotificationproxy -s v -l version -d 'Prints version information'

