# idevicepair
# Autogenerated from man page /usr/share/man/man1/idevicepair.1.gz
complete -c idevicepair -s u -l udid -d 'target specific device by UDID'
complete -c idevicepair -s w -l wireless -d 'perform wireless pairing (\\f[B]see NOTE\\f[])'
complete -c idevicepair -s n -l network -d 'connect to network device (\\f[B]see NOTE\\f[])'
complete -c idevicepair -s d -l debug -d 'enable communication debugging'
complete -c idevicepair -s h -l help -d 'prints usage information'
complete -c idevicepair -s v -l version -d 'prints version information'

