# infiniband-diags
# Autogenerated from man page /usr/share/man/man8/infiniband-diags.8.gz
complete -c infiniband-diags -s D -l Direct -d 'Examples:    [options] -D [options] "0"          # self port    [options] -D …'
complete -c infiniband-diags -s G -l Guid
complete -c infiniband-diags -l port-guid
complete -c infiniband-diags -s L -l Lid
complete -c infiniband-diags -s s -l sm_port -d 'Port Selection flags'
complete -c infiniband-diags -s C -l Ca
complete -c infiniband-diags -s P -l Port -d 'Local port Selection'
complete -c infiniband-diags -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c infiniband-diags -s e -d 'show send and receive errors (timeouts and others)'
complete -c infiniband-diags -s h -l help
complete -c infiniband-diags -s v -l verbose -d 'increase the application verbosity level'
complete -c infiniband-diags -s V -l version -d 'Configuration flags'
complete -c infiniband-diags -s t -l timeout
complete -c infiniband-diags -l outstanding_smps -s o -d 'Specify the number of outstanding SMP\'s which should be issued during the scan'
complete -c infiniband-diags -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c infiniband-diags -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf COMMON FILES'
complete -c infiniband-diags -l enable-compat-utils

