# insmod
# Autogenerated from man page /usr/share/man/man8/insmod.8.gz
complete -c insmod -s s -l syslog -d 'Send errors to syslog instead of standard error'
complete -c insmod -s v -l verbose -d 'Print messages about what the program is doing.  Usually insmod prints'
complete -c insmod -s V -l version -d 'Show version of program and exit'
complete -c insmod -s h -l help -d 'Print the help message and exit'

