# installkernel
# Autogenerated from man page /usr/share/man/man8/installkernel.8.gz
complete -c installkernel -l esp-path -d 'Path to the EFI System Partition (ESP)'
complete -c installkernel -l boot-path -d 'Path to the Extended Boot Loader partition, as defined in the \\m[blue]UAPI'
complete -c installkernel -l make-entry-directory -d 'Controls creation and deletion of the \\m[blue]UAPI'
complete -c installkernel -l entry-type -d 'Controls the type of entries handled by the command'
complete -c installkernel -l entry-token -d 'Controls how to name and identify boot loader entries for this kernel install…'
complete -c installkernel -s v -l verbose -d 'Output additional information about operations being performed'
complete -c installkernel -l root -d 'Takes a directory path as an argument'
complete -c installkernel -l image -d 'Takes a path to a disk image file or block device node'
complete -c installkernel -s h -l help -d 'Print a short help text and exit'
complete -c installkernel -l version -d 'Print a short version string and exit'
complete -c installkernel -l no-pager -d 'Do not pipe output into a pager'
complete -c installkernel -l json -d 'Shows output formatted as JSON'
complete -c installkernel -l image-policy -d 'Takes an image policy string as argument, as per systemd. image-policy(7)'
complete -c installkernel -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'

