# integritysetup
# Autogenerated from man page /usr/share/man/man8/integritysetup.8.gz
complete -c integritysetup -l allow-discards
complete -c integritysetup -l batch-mode -s q
complete -c integritysetup -l bitmap-flush-time
complete -c integritysetup -l bitmap-sectors-per-bit
complete -c integritysetup -l buffer-sectors
complete -c integritysetup -l cancel-deferred
complete -c integritysetup -l data-device
complete -c integritysetup -l debug
complete -c integritysetup -l deferred
complete -c integritysetup -l help -s '?'
complete -c integritysetup -l integrity -s I
complete -c integritysetup -l integrity-bitmap-mode -s B
complete -c integritysetup -l integrity-inline
complete -c integritysetup -l integrity-key-file
complete -c integritysetup -l integrity-key-size
complete -c integritysetup -l integrity-no-journal -s D
complete -c integritysetup -l integrity-recalculate
complete -c integritysetup -l integrity-recalculate-reset
complete -c integritysetup -l integrity-recovery-mode -s R
complete -c integritysetup -l interleave-sectors
complete -c integritysetup -l journal-commit-time
complete -c integritysetup -l journal-crypt
complete -c integritysetup -l journal-crypt-key-file
complete -c integritysetup -l journal-crypt-key-size
complete -c integritysetup -l journal-integrity
complete -c integritysetup -l journal-integrity-key-file
complete -c integritysetup -l journal-integrity-key-size
complete -c integritysetup -l journal-size -s j
complete -c integritysetup -l journal-watermark
complete -c integritysetup -l no-wipe
complete -c integritysetup -l progress-frequency
complete -c integritysetup -l progress-json
complete -c integritysetup -l sector-size -s s
complete -c integritysetup -l tag-size -s t
complete -c integritysetup -l usage
complete -c integritysetup -l verbose -s v
complete -c integritysetup -l version -s V
complete -c integritysetup -l wipe
complete -c integritysetup -l integrity-legacy-padding
complete -c integritysetup -l integrity-legacy-hmac
complete -c integritysetup -l integrity-legacy-recalculate

