# javac-openjdk25
# Autogenerated from man page /usr/share/man/man1/javac-openjdk25.1.gz
complete -c javac-openjdk25 -o Aname
complete -c javac-openjdk25 -o proc:only
complete -c javac-openjdk25 -s d
complete -c javac-openjdk25 -l module-version
complete -c javac-openjdk25 -o Akey -d 'Specifies options to pass to annotation processors'
complete -c javac-openjdk25 -l add-modules -d 'Specifies root modules to resolve in addition to the initial modules, or all …'
complete -c javac-openjdk25 -l boot-class-path -o bootclasspath -d 'Overrides the location of the bootstrap class files'
complete -c javac-openjdk25 -o source -o target -d 'details.  For JDK 9 or later, see --system'
complete -c javac-openjdk25 -l class-path -o classpath -o cp -d 'Specifies where to find user class files and annotation processors'
complete -c javac-openjdk25 -l source-path -o sourcepath -d 'specified, then the user class path is also searched for source files'
complete -c javac-openjdk25 -o deprecation -d 'Shows a description of each use or override of a deprecated member or class'
complete -c javac-openjdk25 -o Xlint:deprecation
complete -c javac-openjdk25 -l enable-preview -d 'Enables preview language features'
complete -c javac-openjdk25 -l release
complete -c javac-openjdk25 -o encoding -d 'Specifies character encoding used by source files, such as EUC-JP and UTF-8'
complete -c javac-openjdk25 -o endorseddirs -d 'Overrides the location of the endorsed standards path'
complete -c javac-openjdk25 -o extdirs -d 'Overrides the location of the installed extensions'
complete -c javac-openjdk25 -s g -d 'Generates all debugging information, including local variables'
complete -c javac-openjdk25 -o 'g:[lines' -d 'Generates only the kinds of debugging information specified by the comma-sepa…'
complete -c javac-openjdk25 -o g:none -d 'Does not generate debugging information'
complete -c javac-openjdk25 -s h -d 'Specifies where to place generated native header files'
complete -c javac-openjdk25 -l help -o help -s '?' -d 'Prints a synopsis of the standard options'
complete -c javac-openjdk25 -l help-extra -s X -d 'Prints a synopsis of the set of extra options'
complete -c javac-openjdk25 -l help-lint -d 'Prints the supported keys for the -Xlint option'
complete -c javac-openjdk25 -o 'implicit:[none' -d 'Specifies whether or not to generate class files for implicitly referenced fi…'
complete -c javac-openjdk25 -o implicit:class -l - -d '[bu] 2'
complete -c javac-openjdk25 -o implicit:none
complete -c javac-openjdk25 -o Joption -d 'Passes option to the runtime system, where option is one of the Java options …'
complete -c javac-openjdk25 -s J -d launcher
complete -c javac-openjdk25 -l limit-modules -d 'Limits the universe of observable modules'
complete -c javac-openjdk25 -l module -s m -d 'Compiles those source files in the named modules that are newer than the corr…'
complete -c javac-openjdk25 -l module-path -s p -d 'Specifies where to find application modules'
complete -c javac-openjdk25 -l module-source-path -d 'Specifies where to find source files when compiling code in multiple modules'
complete -c javac-openjdk25 -o nowarn -d 'Generate only mandatory warnings'
complete -c javac-openjdk25 -o parameters -d 'Generates metadata for reflection on method parameters'
complete -c javac-openjdk25 -o 'proc:[none' -d 'Controls whether annotation processing and compilation are done'
complete -c javac-openjdk25 -o proc:none -d 'annotation processing [bu] 2'
complete -c javac-openjdk25 -o proc:full -d done
complete -c javac-openjdk25 -o processor -d 'Names of the annotation processors to run'
complete -c javac-openjdk25 -l processor-module-path -d 'Specifies the module path used for finding annotation processors'
complete -c javac-openjdk25 -l processor-path -o processorpath -d 'Specifies where to find annotation processors'
complete -c javac-openjdk25 -o profile -d 'Checks that the API used is available in the specified profile'
complete -c javac-openjdk25 -l target/-target
complete -c javac-openjdk25 -l add-exports -d 'packages exported by the Java SE, JDK, and standard modules in the specified …'
complete -c javac-openjdk25 -s s -d 'Specifies the directory used to place the generated source files'
complete -c javac-openjdk25 -l source -d 'Compiles source code according to the rules of the Java programming language …'
complete -c javac-openjdk25 -l system -d 'Overrides the location of system modules'
complete -c javac-openjdk25 -l target -d 'Generates class files suitable for the specified Java SE release'
complete -c javac-openjdk25 -l upgrade-module-path -d 'Overrides the location of upgradeable modules'
complete -c javac-openjdk25 -o verbose -d 'Outputs messages about what the compiler is doing'
complete -c javac-openjdk25 -l version -o version -d 'Prints version information'
complete -c javac-openjdk25 -o Werror -d 'Terminates compilation when warnings occur.  Extra Options'
complete -c javac-openjdk25 -l add-reads -d 'Specifies additional modules to be considered as required by a given module'
complete -c javac-openjdk25 -l default-module-for-created-files -d 'Specifies the fallback target module for files created by annotation processo…'
complete -c javac-openjdk25 -l disable-line-doc-comments -d 'Disables support for documentation comments with lines beginning ///'
complete -c javac-openjdk25 -o 'Djava.endorsed.dirs' -d 'Overrides the location of the endorsed standards path'
complete -c javac-openjdk25 -o 'Djava.ext.dirs' -d 'Overrides the location of installed extensions'
complete -c javac-openjdk25 -l patch-module -d 'Overrides or augments a module with classes and resources in JAR files or dir…'
complete -c javac-openjdk25 -o Xbootclasspath:path -d 'Overrides the location of the bootstrap class files'
complete -c javac-openjdk25 -o Xbootclasspath/a:path -d 'Adds a suffix to the bootstrap class path'
complete -c javac-openjdk25 -o Xbootclasspath/p:path -d 'Adds a prefix to the bootstrap class path'
complete -c javac-openjdk25 -o 'Xdiags:[compact' -d 'Selects a diagnostic mode'
complete -c javac-openjdk25 -o Xdoclint -d 'Enables recommended checks for problems in documentation comments'
complete -c javac-openjdk25 -o Xdoclint:all/protected -d 'The following option enables all groups of checks for all access levels, exce…'
complete -c javac-openjdk25 -o Xdoclint:all -o html/package
complete -c javac-openjdk25 -o Xdoclint/package:packages -d 'Enables or disables checks in specific packages'
complete -c javac-openjdk25 -o Xlint -d 'Enables all recommended warnings'
complete -c javac-openjdk25 -o Xlint:key -d 'Enables and/or disables warning categories using the one or more of the keys …'
complete -c javac-openjdk25 -o Xmaxerrs -d 'Sets the maximum number of errors to print'
complete -c javac-openjdk25 -o Xmaxwarns -d 'Sets the maximum number of warnings to print'
complete -c javac-openjdk25 -o 'Xpkginfo:[always' -d 'Specifies when and how the javac command generates package-info'
complete -c javac-openjdk25 -o Xplugin:name -d 'Specifies the name and optional arguments for a plug-in to be run'
complete -c javac-openjdk25 -o 'Xprefer:[source' -d 'Specifies which file to read when both a source file and class file are found…'
complete -c javac-openjdk25 -o Xprefer:newer -d 'for a type (default).  [bu] 2'
complete -c javac-openjdk25 -o Xprefer:source -d 'Use -Xprefer:source when you want to be sure that any annotation processors c…'
complete -c javac-openjdk25 -o Xprint -d 'Prints a textual representation of specified types for debugging purposes'
complete -c javac-openjdk25 -o XprintProcessorInfo -d 'Prints information about which annotations a processor is asked to process'
complete -c javac-openjdk25 -o XprintRounds -d 'Prints information about initial and subsequent annotation processing rounds'
complete -c javac-openjdk25 -o Xstdout -d 'Sends compiler messages to the named file'
complete -c javac-openjdk25 -o implicit -d 'a warning that the file is being compiled without being subject to annotation…'
complete -c javac-openjdk25 -l add-opens
complete -c javac-openjdk25 -o Xbootclasspath/p
complete -c javac-openjdk25 -o Xbootclasspath
complete -c javac-openjdk25 -o Xbootclasspath/a

