# jcmd-openjdk25
# Autogenerated from man page /usr/share/man/man1/jcmd-openjdk25.1.gz
complete -c jcmd-openjdk25 -o all -d ' Compiler'
complete -c jcmd-openjdk25 -s H -d '[bu] 2'
complete -c jcmd-openjdk25 -s s -d 'Compiler. perfmap [arguments] (Linux only) Write map file for Linux perf tool'
complete -c jcmd-openjdk25 -o parallel -d 'heap inspection'
complete -c jcmd-openjdk25 -o gz -d 'gzipped format using the given compression level'
complete -c jcmd-openjdk25 -o overwrite -d 'overwritten if it exists (BOOLEAN, false) [bu] 2'
complete -c jcmd-openjdk25 -s F -d 'If %p is specified in the filename, it is expanded to the JVM[aq]s PID'
complete -c jcmd-openjdk25 -o format -d '[dq]json[dq]) (STRING, plain)'
complete -c jcmd-openjdk25 -s e -d 'false) [bu] 2'
complete -c jcmd-openjdk25 -s l -d '(BOOLEAN, false) Thread'
complete -c jcmd-openjdk25 -s i -d '(BOOLEAN, false) [bu] 2'
complete -c jcmd-openjdk25 -o verbose -d class
complete -c jcmd-openjdk25 -o date -d '(BOOLEAN, false) VM. version Print JVM version information.  Impact: Low'

