# jconsole-openjdk25
# Autogenerated from man page /usr/share/man/man1/jconsole-openjdk25.1.gz
complete -c jconsole-openjdk25 -o interval -d 'Sets the update interval to n seconds (default is 4 seconds)'
complete -c jconsole-openjdk25 -o notile -d 'Doesn[aq]t tile the windows for two or more connections'
complete -c jconsole-openjdk25 -o pluginpath -d 'Specifies the path that jconsole uses to look up plug-ins'
complete -c jconsole-openjdk25 -o version -d 'Prints the program version'
complete -c jconsole-openjdk25 -o Jinput_arguments -d 'Passes input_arguments to the JVM on which the jconsole command is run'
complete -c jconsole-openjdk25 -o help -l help -d 'Displays the help message for the command'

