# jdeprscan-openjdk25
# Autogenerated from man page /usr/share/man/man1/jdeprscan-openjdk25.1.gz
complete -c jdeprscan-openjdk25 -l class-path -d 'Provides a search path for resolution of dependent classes'
complete -c jdeprscan-openjdk25 -l for-removal -d 'Limits scanning or listing to APIs that are deprecated for removal'
complete -c jdeprscan-openjdk25 -l full-version -d 'Prints out the full version string of the tool'
complete -c jdeprscan-openjdk25 -l help -s h -d 'Prints out a full help message'
complete -c jdeprscan-openjdk25 -l list -s l -d 'Prints the set of deprecated APIs'
complete -c jdeprscan-openjdk25 -l release -d 'Specifies the Java SE release that provides the set of deprecated APIs for sc…'
complete -c jdeprscan-openjdk25 -l verbose -s v -d 'Enables additional message output during processing'
complete -c jdeprscan-openjdk25 -l version -d 'Prints out the abbreviated version string of the tool'

