# jnativescan-openjdk25
# Autogenerated from man page /usr/share/man/man1/jnativescan-openjdk25.1.gz
complete -c jnativescan-openjdk25 -l class-path -d 'Used to specify a list of paths pointing to jar files to be scanned'
complete -c jnativescan-openjdk25 -l module-path -d 'Used to specify a list of paths pointing to jar files or directories containi…'
complete -c jnativescan-openjdk25 -l add-modules -d 'For both the --class-path and --module-path options, path should be a search …'
complete -c jnativescan-openjdk25 -l release -d 'Used to specify the Java SE release that specifies the set of restricted meth…'
complete -c jnativescan-openjdk25 -l print-native-access -d 'Print a comma-separated list of module names that use native functionalities,…'
complete -c jnativescan-openjdk25 -l help -s h -d 'Prints out a full help message'
complete -c jnativescan-openjdk25 -l version -d 'Prints out the abbreviated version string of the tool'

