# jps-openjdk25
# Autogenerated from man page /usr/share/man/man1/jps-openjdk25.1.gz
complete -c jps-openjdk25 -s q -d 'Suppresses the output of the class name, JAR file name, and arguments passed …'
complete -c jps-openjdk25 -o mlvV -d 'You can specify any combination of these options'
complete -c jps-openjdk25 -s m -d 'method.  The output may be null for embedded JVMs.  [bu] 2'
complete -c jps-openjdk25 -s l -d 'main class or the full path name to the application[aq]s JAR file.  [bu] 2'
complete -c jps-openjdk25 -s v -d '[bu] 2'
complete -c jps-openjdk25 -s V -d 'and arguments passed to the main method, producing a list of only local JVM i…'
complete -c jps-openjdk25 -o help -d 'Displays the help message for the jps command'

