# json-glib-format
# Autogenerated from man page /usr/share/man/man1/json-glib-format.1.gz
complete -c json-glib-format -s h -l help -d 'Print a help message and exit'
complete -c json-glib-format -l output -d 'Redirects the output to FILE instead of using the standard output'
complete -c json-glib-format -s p -l prettify -d 'Prettifies the output, by adding spaces and indentation'
complete -c json-glib-format -l indent-spaces -d 'Changes the number of spaces using to indent the JSON data from the default o…'

