# jstack-openjdk25
# Autogenerated from man page /usr/share/man/man1/jstack-openjdk25.1.gz
complete -c jstack-openjdk25 -s l -d 'The long listing option prints additional information about locks'
complete -c jstack-openjdk25 -s h -o help -d 'Prints a help message'

