# jwebserver-openjdk25
# Autogenerated from man page /usr/share/man/man1/jwebserver-openjdk25.1.gz
complete -c jwebserver-openjdk25 -s h -s '?' -l help -d 'Prints the help message and exits'
complete -c jwebserver-openjdk25 -s b -l bind-address -d 'Specifies the address to bind to.  Default: 127. 0. 0. 1 or ::1 (loopback)'
complete -c jwebserver-openjdk25 -s d -l directory -d 'Specifies the directory to serve.  Default: current directory'
complete -c jwebserver-openjdk25 -s o -l output -d 'Specifies the output format.  none | info | verbose.  Default: info'
complete -c jwebserver-openjdk25 -s p -l port -d 'Specifies the port to listen on.  Default: 8000'
complete -c jwebserver-openjdk25 -o version -l version -d 'Prints the version information and exits'

