# keyd-application-mapper
# Autogenerated from man page /usr/share/man/man1/keyd-application-mapper.1.gz
complete -c keyd-application-mapper -s v -l verbose -d 'Write verbose output'
complete -c keyd-application-mapper -s d -l daemonize -d 'Daemonize, write output to ~/. config/keyd/app. log instead of stdout'

