# libtool-next-version
# Autogenerated from man page /usr/share/man/man1/libtool-next-version.1.gz
complete -c libtool-next-version -l help -d 'print this help and exit'
complete -c libtool-next-version -l version -d 'print version information and exit'

