# llvm-remarkutil
# Autogenerated from man page /usr/share/man/man1/llvm-remarkutil.1.gz
complete -c llvm-remarkutil -l parser -d 'Select the type of input remark parser.  Required'
complete -c llvm-remarkutil -l count-by -d 'Select option to collect remarks by'
complete -c llvm-remarkutil -l group-by -d 'group count of remarks by property'
complete -c llvm-remarkutil -l args -d 'If count-by is set to arg this flag can be used to collect from specified rem…'
complete -c llvm-remarkutil -l rargs -d 'If count-by is set to arg this flag can be used to collect from specified rem…'
complete -c llvm-remarkutil -l pass-name -d 'Filter count by pass name'
complete -c llvm-remarkutil -l rpass-name -d 'Filter count by pass name using regular expressions'
complete -c llvm-remarkutil -l remark-name -d 'Filter count by remark name'
complete -c llvm-remarkutil -l rremark-name -d 'Filter count by remark name using regular expressions'
complete -c llvm-remarkutil -l filter-arg-by -d 'Filter count by argument value'
complete -c llvm-remarkutil -l rfilter-arg-by -d 'Filter count by argument value using regular expressions'
complete -c llvm-remarkutil -l remark-type -d 'Filter remarks by type with the following options'
complete -c llvm-remarkutil -l report-style -d 'Output style'
complete -c llvm-remarkutil -l pretty -d 'Pretty-print JSON output.  Optional'
complete -c llvm-remarkutil -s o -d 'Output file for the report.  Outputs to stdout by default'

