# llvm-cgdata
# Autogenerated from man page /usr/share/man/man1/llvm-cgdata.1.gz
complete -c llvm-cgdata -l format -d 'Specify the format of the output . cgdata file'
complete -c llvm-cgdata -l output -d 'Specify the output file name'
complete -c llvm-cgdata -l cgdata-version -d 'Print the version of the llvm-cgdata tool'
complete -c llvm-cgdata -l convert -d 'Convert a . cgdata file from one format to another'
complete -c llvm-cgdata -l merge -d 'Merge multiple raw codgen data in binaries into a single . cgdata file'
complete -c llvm-cgdata -l show -d 'Show summary information about a . cgdata file'

