# localsearch-reset
# Autogenerated from man page /usr/share/man/man1/localsearch-reset.1.gz
complete -c localsearch-reset -s s -l filesystem -d 'Removes indexed filesystem data'
complete -c localsearch-reset -s f -l file -d 'Resets all indexed information about FILE, works recursively for directories'

