# localsearch-3
# Autogenerated from man page /usr/share/man/man1/localsearch-3.1.gz
complete -c localsearch-3 -s '?' -l help -d 'Show summary of options'
complete -c localsearch-3 -s V -l version -d 'Returns the version of this binary'
complete -c localsearch-3 -s n -l no-daemon -d 'Tells the indexer to exit once all indexing has finished and the database is …'
complete -c localsearch-3 -s e -l eligible -d 'Checks if FILE is eligible for being mined based on the current configuration…'
complete -c localsearch-3 -l initial-sleep -d 'option moot'

