# localsearch-extract
# Autogenerated from man page /usr/share/man/man1/localsearch-extract.1.gz
complete -c localsearch-extract -s o -l output-format -d 'Choose which format to use to output results'

