# localsearch-search
# Autogenerated from man page /usr/share/man/man1/localsearch-search.1.gz
complete -c localsearch-search -s l -l limit -d 'Limit search to limit results'
complete -c localsearch-search -s o -l offset -d 'Offset the search results by offset'
complete -c localsearch-search -s d -l detailed -d 'Show the unique URN associated with each search result and a snippet of the m…'
complete -c localsearch-search -s a -l all -d 'Show results which might not be available'
complete -c localsearch-search -s r
complete -c localsearch-search -s f -l files
complete -c localsearch-search -s s -l folders
complete -c localsearch-search -s m -l music
complete -c localsearch-search -l music-albums
complete -c localsearch-search -l music-artists
complete -c localsearch-search -s i -l images
complete -c localsearch-search -s v -l videos
complete -c localsearch-search -s t -l documents
complete -c localsearch-search -l software

