# localsearch-tag
# Autogenerated from man page /usr/share/man/man1/localsearch-tag.1.gz
complete -c localsearch-tag -s t -l list -d 'List all tags'
complete -c localsearch-tag -s s -l show-files -d 'Show the files associated with each tag'
complete -c localsearch-tag -s a -l add -d 'Add a tag with the name TAG'
complete -c localsearch-tag -s d -l delete -d 'Delete a tag with the name TAG'
complete -c localsearch-tag -s e -l description -d 'This option ONLY applies when using --add and provides a description to go wi…'
complete -c localsearch-tag -s l -l limit -d 'Limit search to N results.  The default is 512'
complete -c localsearch-tag -s o -l offset -d 'Offset the search results by N'

