# localsearch-status
# Autogenerated from man page /usr/share/man/man1/localsearch-status.1.gz
complete -c localsearch-status -l stat -d 'List statistics of stored RDF classes (e. g'
complete -c localsearch-status -s f -l follow -d 'Follow status changes to daemons as they happen'
complete -c localsearch-status -s w -l watch -d 'Watch changes that happen to the database in real time'

