# localsearch-info
# Autogenerated from man page /usr/share/man/man1/localsearch-info.1.gz
complete -c localsearch-info -s f -l full-namespaces -d 'By default, all keys and values reported about any given file are returned in…'
complete -c localsearch-info -s c -l plain-text-content -d 'If the resource being displayed has nie:PlainTextContent (i. e'
complete -c localsearch-info -s o -l output-format -d 'Choose which format to use to output results'
complete -c localsearch-info -s e -l eligible -d 'Checks whether a file is eligible for indexing'

