# lsmod
# Autogenerated from man page /usr/share/man/man8/lsmod.8.gz
complete -c lsmod -s v -l verbose -d 'Print messages about what the program is doing.  Usually lsmod prints'
complete -c lsmod -s V -l version -d 'Show version of program and exit'
complete -c lsmod -s h -l help -d 'Print the help message and exit'

