# lsusb.py
# Autogenerated from man page /usr/share/man/man1/lsusb.py.1.gz
complete -c 'lsusb.py' -s h -l help -d 'Displays options supported by  lsusb (1)'
complete -c 'lsusb.py' -s i -l interfaces -d 'Display information about the interfaces of each device, excluding hubs'
complete -c 'lsusb.py' -s I -l hub-interfaces -d 'Display information about the interfaces of each device, including hubs'
complete -c 'lsusb.py' -s u -l hide-empty-hubs -d 'Suppress information about hubs that have no devices connected'
complete -c 'lsusb.py' -s U -l hide-hubs -d 'Suppress information about hubs, even if they have devices connected'
complete -c 'lsusb.py' -s c -l color -d 'Use color'
complete -c 'lsusb.py' -s C -l no-color -d 'Don\'t use color'
complete -c 'lsusb.py' -s e -l endpoints -d 'Include information about device (and interface, with  -i ) endpoints'
complete -c 'lsusb.py' -s f -l usbids-path -d 'Overrides the path of the usb. ids file'

