# lv2ls
# Autogenerated from man page /usr/share/man/man1/lv2ls.1.gz
complete -c lv2ls -s V -d 'Print version information and exit'
complete -c lv2ls -s h -d 'Print usage information and exit'
complete -c lv2ls -s n -d 'Show names instead of URIs'

