# memusage
# Autogenerated from man page /usr/share/man/man1/memusage.1.gz
complete -c memusage -o 'n\\~' -d 'TQ  --progname= name Name of the program file to profile'
complete -c memusage -o 'p\\~' -d 'TQ  --png= file Generate PNG graphic and store it in R file '
complete -c memusage -o 'd\\~' -d 'TQ  --data= file Generate binary data file and store it in R file '
complete -c memusage -s u -d 'TQ  --unbuffered Do not buffer output'
complete -c memusage -o 'b\\~' -d 'TQ  --buffer= size Collect  size entries before writing them out'
complete -c memusage -l no-timer -d 'Disable timer-based . RB ( SIGPROF ) sampling of stack pointer value'
complete -c memusage -s m -d 'TQ  --mmap Also trace  mmap (2),  mremap (2), and  munmap (2)'
complete -c memusage -s '?' -d 'TQ  --help Print help and exit'
complete -c memusage -l usage -d 'Print a short usage message and exit'
complete -c memusage -s V -d 'TQ  --version Print version information and exit'
complete -c memusage -s t -d 'TQ  --time-based Use time (rather than number of function calls) as the scale…'
complete -c memusage -s T -d 'TQ  --total Also draw a graph of total memory use'
complete -c memusage -l title -d 'Use  name as the title of the graph'
complete -c memusage -o 'x\\~' -d 'TQ  --x-size= size Make the graph  size pixels wide'
complete -c memusage -s p -d 'option,  below) to create a PNG file containing graphical representation of t…'
complete -c memusage -s n
complete -c memusage -l progname -d 'Name of the program file to profile'
complete -c memusage -l png -d 'Generate PNG graphic and store it in file '
complete -c memusage -s d
complete -c memusage -l data -d 'Generate binary data file and store it in file '
complete -c memusage -l unbuffered -d 'Do not buffer output'
complete -c memusage -s b
complete -c memusage -l buffer -d 'Collect size entries before writing them out'
complete -c memusage -l mmap -d 'Also trace mmap (2), mremap (2), and munmap (2)'
complete -c memusage -l help -d 'Print help and exit'
complete -c memusage -l version -d 'Print version information and exit'
complete -c memusage -l time-based -d 'Use time (rather than number of function calls) as the scale for the X axis'
complete -c memusage -l total -d 'Also draw a graph of total memory use'
complete -c memusage -s x
complete -c memusage -l x-size -d 'Make the graph size pixels wide'
complete -c memusage -s y
complete -c memusage -l y-size -d 'Make the graph size pixels high'

