# memusagestat
# Autogenerated from man page /usr/share/man/man1/memusagestat.1.gz
complete -c memusagestat -o 'o\\~' -d 'TQ  --output= file Name of the output file'
complete -c memusagestat -o 's\\~' -d 'TQ  --string= string Use  string as the title inside the output graph'
complete -c memusagestat -s t -d 'TQ  --time Use time (rather than number of function calls) as the scale for t…'
complete -c memusagestat -s T -d 'TQ  --total Also draw a graph of total memory consumption'
complete -c memusagestat -o 'x\\~' -d 'TQ  --x-size= size Make the output graph  size pixels wide'
complete -c memusagestat -o 'y\\~' -d 'TQ  --y-size= size Make the output graph  size pixels high'
complete -c memusagestat -s '?' -d 'TQ  --help Print a help message and exit'
complete -c memusagestat -l usage -d 'Print a short usage message and exit'
complete -c memusagestat -s d -d '(or'
complete -c memusagestat -l data -d 'option of memusage (1)'
complete -c memusagestat -s o
complete -c memusagestat -l output -d 'Name of the output file'
complete -c memusagestat -s s
complete -c memusagestat -l string -d 'Use string as the title inside the output graph'
complete -c memusagestat -l time -d 'Use time (rather than number of function calls) as the scale for the X axis'
complete -c memusagestat -l total -d 'Also draw a graph of total memory consumption'
complete -c memusagestat -s x
complete -c memusagestat -l x-size -d 'Make the output graph size pixels wide'
complete -c memusagestat -s y
complete -c memusagestat -l y-size -d 'Make the output graph size pixels high'
complete -c memusagestat -l help -d 'Print a help message and exit'
complete -c memusagestat -s V
complete -c memusagestat -l version -d 'Print version information and exit'

