# mergecap
# Autogenerated from man page /usr/share/man/man1/mergecap.1.gz
complete -c mergecap -s a -d 'Causes the frame timestamps to be ignored, writing all packets from the first…'
complete -c mergecap -s F -d 'Sets the file format of the output capture file'
complete -c mergecap -s h -l help
complete -c mergecap -s I -d 'Sets the Interface Description Block (IDB) merge mode to use during merging'
complete -c mergecap -s s -d 'Sets the snapshot length to use when writing the data'
complete -c mergecap -s v -l version
complete -c mergecap -s V
complete -c mergecap -s w
complete -c mergecap -l compress -d 'Compress the output file using the type compression format'
complete -c mergecap -l log-level
complete -c mergecap -l log-fatal
complete -c mergecap -l log-domains
complete -c mergecap -l log-debug
complete -c mergecap -l log-noisy
complete -c mergecap -l log-fatal-domains
complete -c mergecap -l log-file

