# micro
# Autogenerated from man page /usr/share/man/man1/micro.1.gz
complete -c micro -o clean
complete -c micro -o config-dir -d dir
complete -c micro -o options
complete -c micro -o debug
complete -c micro -o profile
complete -c micro -o version
complete -c micro -o plugin -d '[ PLUGIN ]'
complete -c micro -s '<' -d value

