# mirage
# Autogenerated from man page /usr/share/man/man1/mirage.1.gz
complete -c mirage -s h -l help -d 'Show this help and exit'
complete -c mirage -s v -l version -d 'Show version information and exit'
complete -c mirage -s V -l verbose -d 'Show more detailed information'
complete -c mirage -s R -l recursive -d 'Recursively include all images found in subdirectories of FOLDERS'
complete -c mirage -s s -l slideshow -d 'Start in slideshow mode'
complete -c mirage -s f -l fullscreen -d 'Start in fullscreen mode'
complete -c mirage -s o -l onload -d 'Execute \'cmd\' when an image is loaded (uses same syntax as custom actions,  i'

