# modinfo
# Autogenerated from man page /usr/share/man/man8/modinfo.8.gz
complete -c modinfo -s F -l field -d 'Only print this field value, one per line.  This is most useful for'
complete -c modinfo -s b -l basedir -d 'Root directory for modules, / by default'
complete -c modinfo -s k -d 'Provide information about a kernel other than the running one.  This is'
complete -c modinfo -s 0 -l null -d 'Use the ASCII zero character to separate field values, instead of a new'
complete -c modinfo -s a -l author -s d -l description -s l -l license -s p -l parameters -s n -l filename -d 'These are shortcuts for the --field flag\'s author, description,'
complete -c modinfo -s h -l help -d 'Print the help message and exit'

