# mpc
# Autogenerated from man page /usr/share/man/man1/mpc.1.gz
complete -c mpc -s f -l format -d 'Configure the format used to display songs. sp The metadata delimiters are: '
complete -c mpc -l wait -d 'Wait for operation to finish (e. g.  database update)'
complete -c mpc -l range -d 'Operate on a range (e. g.  when loading a playlist)'
complete -c mpc -l with-prio -d 'Show only songs that have a non-zero priority'
complete -c mpc -s q -l quiet -l no-status -d 'Prevents the current song status from being printed on completion of some of …'
complete -c mpc -l verbose -d 'Verbose output'
complete -c mpc -l host -d 'The MPD server to connect to'
complete -c mpc -l port -s p -d 'The TCP port of the MPD server to connect to'
complete -c mpc -l partition -s a -d 'The partition of the MPD server to operate on'

