# ms_print
# Autogenerated from man page /usr/share/man/man1/ms_print.1.gz
complete -c ms_print -s h -l help -d 'Show the help message'
complete -c ms_print -l version -d 'Show the version number'
complete -c ms_print -l threshold -d 'Same as Massif\\*(Aqs --threshold option, but applied after profiling rather t…'
complete -c ms_print -l x -d 'Width of the graph, in columns'
complete -c ms_print -l y -d 'Height of the graph, in rows'

