# nfsdctl
# Autogenerated from man page /usr/share/man/man8/nfsdctl.8.gz
complete -c nfsdctl -l help -d 'nfsdctl listener --help OPTIONS'
complete -c nfsdctl -s d -l debug
complete -c nfsdctl -s h
complete -c nfsdctl -s s -l syslog
complete -c nfsdctl -s V -l version

