# ntpshmmon
# Autogenerated from man page /usr/share/man/man1/ntpshmmon.1.gz
complete -c ntpshmmon -s '?' -s h -l help
complete -c ntpshmmon -s n -l count
complete -c ntpshmmon -s o -l offset
complete -c ntpshmmon -s s -l rmshm
complete -c ntpshmmon -s t -l seconds
complete -c ntpshmmon -s v -l verbose
complete -c ntpshmmon -s V -l version

