# nvidia-smi
# Autogenerated from man page /usr/share/man/man1/nvidia-smi.1.gz
complete -c nvidia-smi -s h -l help
complete -c nvidia-smi -l version
complete -c nvidia-smi -s L -l list-gpus
complete -c nvidia-smi -s B -l list-excluded-gpus
complete -c nvidia-smi -o col -l columns
complete -c nvidia-smi -s i -l id
complete -c nvidia-smi -s f -l filename
complete -c nvidia-smi -s l -l loop
complete -c nvidia-smi -s q -l query
complete -c nvidia-smi -s u -l unit
complete -c nvidia-smi -s x -l xml-format
complete -c nvidia-smi -l dtd
complete -c nvidia-smi -l debug
complete -c nvidia-smi -s d -l display
complete -c nvidia-smi -o lms -l loop-ms
complete -c nvidia-smi -l query-gpu
complete -c nvidia-smi -l query-supported-clocks
complete -c nvidia-smi -l query-compute-apps
complete -c nvidia-smi -l query-accounted-apps
complete -c nvidia-smi -l query-retired-pages
complete -c nvidia-smi -l query-remapped-rows
complete -c nvidia-smi -l format
complete -c nvidia-smi -o pm -l persistence-mode
complete -c nvidia-smi -s e -l ecc-config
complete -c nvidia-smi -s p -l reset-ecc-errors
complete -c nvidia-smi -s c -l compute-mode
complete -c nvidia-smi -o dm -l driver-model
complete -c nvidia-smi -o fdm -l force-driver-model
complete -c nvidia-smi -l gom
complete -c nvidia-smi -s r -l gpu-reset
complete -c nvidia-smi -l ---------- -l ---------------------------- -l ---------------------------- -d ' Pre-Ampere | All PEER connected GPUs must | All PEER connected GPUs must    …'
complete -c nvidia-smi -l ----------------------------------------------------- -d ' Pre-Ampere | All PEER connected GPUs must be reset in same command   Ampere+…'
complete -c nvidia-smi -o vm -l virt-mode
complete -c nvidia-smi -o lgc -l lock-gpu-clocks
complete -c nvidia-smi -l mode -d 'This mode is the default clock locking mode and provides the highest possible…'
complete -c nvidia-smi -o lmc -l lock-memory-clocks
complete -c nvidia-smi -o rgc -l reset-gpu-clocks
complete -c nvidia-smi -o rmc -l reset-memory-clocks
complete -c nvidia-smi -o ac -l applications-clocks
complete -c nvidia-smi -o rac -l reset-applications-clocks
complete -c nvidia-smi -o lmcd -l lock-memory-clocks-deferred
complete -c nvidia-smi -o rmcd -l reset-memory-clocks-deferred
complete -c nvidia-smi -o pl -l power-limit
complete -c nvidia-smi -o sc -l scope
complete -c nvidia-smi -o cc -l cuda-clocks
complete -c nvidia-smi -o am -l accounting-mode
complete -c nvidia-smi -o caa -l clear-accounted-apps
complete -c nvidia-smi -l auto-boost-default
complete -c nvidia-smi -l auto-boost-permission
complete -c nvidia-smi -o mig -l multi-instance-gpu
complete -c nvidia-smi -o gtt -l gpu-target-temp
complete -c nvidia-smi -l set-hostname
complete -c nvidia-smi -l get-hostname
complete -c nvidia-smi -o eom -l error-on-warning
complete -c nvidia-smi -s t -l toggle-led

