# oggz-rip
# Autogenerated from man page /usr/share/man/man1/oggz-rip.1.gz
complete -c oggz-rip -s o -l output -d 'Write output to the specified filename instead of printing it to standard out…'
complete -c oggz-rip -s h -l help -d 'Display usage information and exit'
complete -c oggz-rip -s v -l version -d 'Output version information and exit'
complete -c oggz-rip -s s -l serialno -d 'Output streams with given serialno'
complete -c oggz-rip -s i -l stream-index -d 'Filter by stream index'
complete -c oggz-rip -s c -l content-type -d 'Filter by content-type'

