# pango-segmentation
# Autogenerated from man page /usr/share/man/man1/pango-segmentation.1.gz
complete -c pango-segmentation -s h -l help -d 'Show help options'
complete -c pango-segmentation -l version -d 'Print the command\'s version and exit.  APPLICATION OPTIONS'
complete -c pango-segmentation -l text -d 'Text to display (instead of FILE)'
complete -c pango-segmentation -l kind -d 'The boundary to show'

