# pango-list
# Autogenerated from man page /usr/share/man/man1/pango-list.1.gz
complete -c pango-list -s h -l help -d 'Show help options'
complete -c pango-list -l version -d 'Print the command\'s version and exit.  APPLICATION OPTIONS'
complete -c pango-list -l verbose -d 'Print verbose information'
complete -c pango-list -l metrics -d 'Print font metrics'
complete -c pango-list -l variations -d 'Print font variations'

