# pcap-config
# Autogenerated from man page /usr/share/man/man1/pcap-config.1.gz
complete -c pcap-config -l help -d 'Produce a help message and exit'
complete -c pcap-config -l version -d 'Produce libpcap version and exit'
complete -c pcap-config -l cflags -d 'Produce the  -I compiler flag required to include libpcap\'s header files'
complete -c pcap-config -l libs -d 'Produce the  -L and  -l linker flags required to link with libpcap, including…'
complete -c pcap-config -l additional-libs -d 'Produce the  -L and  -l linker flags for libraries required by libpcap, but n…'
complete -c pcap-config -l static -d 'This option causes  --libs and  --additional-libs to produce linker flags app…'
complete -c pcap-config -s I -d 'compiler flag required to include libpcap\'s header files'
complete -c pcap-config -s L -d and
complete -c pcap-config -s l -d 'linker flags required to link with libpcap, including'
complete -c pcap-config -l static-pcap-only -d 'This option causes'

