# perfquery
# Autogenerated from man page /usr/share/man/man8/perfquery.8.gz
complete -c perfquery -s x -l extended -d 'show extended port counters rather than (basic) port counters'
complete -c perfquery -s X -l xmtsl -d 'show transmit data SL counter.  This is an optional counter for QoS'
complete -c perfquery -s S -l rcvsl -d 'show receive data SL counter.  This is an optional counter for QoS'
complete -c perfquery -s D -l xmtdisc -d 'show transmit discard details.  This is an optional counter'
complete -c perfquery -s E -l rcverr -d 'show receive error details.  This is an optional counter'
complete -c perfquery -s T -l extended_speeds -d 'show extended speeds port counters.  This is an optional counter'
complete -c perfquery -l oprcvcounters -d 'show Rcv Counters per Op code.  This is an optional counter'
complete -c perfquery -l flowctlcounters -d 'show flow control counters.  This is an optional counter'
complete -c perfquery -l vloppackets -d 'show packets received per Op code per VL.  This is an optional counter'
complete -c perfquery -l vlopdata -d 'show data received per Op code per VL.  This is an optional counter'
complete -c perfquery -l vlxmitflowctlerrors -d 'show flow control update errors per VL.  This is an optional counter'
complete -c perfquery -l vlxmitcounters -d 'show ticks waiting to transmit counters per VL.  This is an optional counter'
complete -c perfquery -l swportvlcong -d 'show sw port VL congestion.  This is an optional counter'
complete -c perfquery -l rcvcc -d 'show Rcv congestion control counters.  This is an optional counter'
complete -c perfquery -l slrcvfecn -d 'show SL Rcv FECN counters.  This is an optional counter'
complete -c perfquery -l slrcvbecn -d 'show SL Rcv BECN counters.  This is an optional counter'
complete -c perfquery -l xmitcc -d 'show Xmit congestion control counters.  This is an optional counter'
complete -c perfquery -l vlxmittimecc -d 'show VL Xmit Time congestion control counters.  This is an optional counter'
complete -c perfquery -s c -l smplctl -d 'show port samples control'
complete -c perfquery -s a -l all_ports -d 'show aggregated counters for all ports of the destination lid, reset all coun…'
complete -c perfquery -s l -l loop_ports -d 'If all ports are selected by the user (either through the -a option or port 2…'
complete -c perfquery -s r -l reset_after_read -d 'reset counters after read'
complete -c perfquery -s R -l Reset_only -d 'only reset counters'
complete -c perfquery -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c perfquery -s e -d 'show send and receive errors (timeouts and others)'
complete -c perfquery -s v -l verbose -d 'increase the application verbosity level'
complete -c perfquery -s y -l m_key -d 'use the specified M_key for requests'
complete -c perfquery -s G -l Guid
complete -c perfquery -s L -l Lid
complete -c perfquery -s s -l sm_port -d 'Port Selection flags'
complete -c perfquery -s C -l Ca
complete -c perfquery -s P -l Port -d 'Local port Selection'
complete -c perfquery -s h -l help
complete -c perfquery -s V -l version -d 'Configuration flags'
complete -c perfquery -s t -l timeout
complete -c perfquery -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

