# pkgfile
# Autogenerated from man page /usr/share/man/man1/pkgfile.1.gz
complete -c pkgfile -s l -l list
complete -c pkgfile -l glob -l regex
complete -c pkgfile -s s -l search
complete -c pkgfile -s u -l update
complete -c pkgfile -s b -l binaries
complete -c pkgfile -s d -l directories
complete -c pkgfile -s g
complete -c pkgfile -s i -l ignorecase
complete -c pkgfile -s r
complete -c pkgfile -s R -l repo
complete -c pkgfile -s 0 -l null
complete -c pkgfile -s q -l quiet
complete -c pkgfile -s v -l verbose
complete -c pkgfile -s w -l raw
complete -c pkgfile -s z -l compress
complete -c pkgfile -s C -l config
complete -c pkgfile -s D -l cachedir
complete -c pkgfile -s h -l help
complete -c pkgfile -s V -l version

