# pkgfiled
# Autogenerated from man page /usr/share/man/man1/pkgfiled.1.gz
complete -c pkgfiled -s f -l force -d 'X Item "-f, --force" On the initial sync, ignore timestamp comparisons and re…'
complete -c pkgfiled -s o -l oneshot -d 'X Item "-o, --oneshot" Exit after pkgfiled\\*(Aqs initial sync, rather than co…'
complete -c pkgfiled -s z -l compress -d 'X Item "-z, --compress[=COMPRESSION]" Repack repos with the optionally suppli…'
complete -c pkgfiled -s h -l help -d 'X Item "-h, --help" Print help and exit'
complete -c pkgfiled -s V -l version

