# po-fetch
# Autogenerated from man page /usr/share/man/man1/po-fetch.1.gz
complete -c po-fetch -l git -d 'Make changes in the git index, to prepare for a git commit'
complete -c po-fetch -l help -d 'Show this help text'
complete -c po-fetch -l version -d 'Show version and authorship information.  AUTHOR Written by Bruno Haible'

