# ppscheck
# Autogenerated from man page /usr/share/man/man8/ppscheck.8.gz
complete -c ppscheck -s '?'
complete -c ppscheck -s m
complete -c ppscheck -s p
complete -c ppscheck -s V
complete -c ppscheck -s x -l seconds

