# primesieve
# Autogenerated from man page /usr/share/man/man1/primesieve.1.gz
complete -c primesieve -s c -l count -d 'Count primes and/or prime k-tuplets, 1 <= NUM <= 6'
complete -c primesieve -l cpu-info -d 'Print CPU information: CPU name, frequency, number of cores, cache sizes, '
complete -c primesieve -s d -l dist -d 'Sieve the interval [START, START + DIST]'
complete -c primesieve -s h -l help -d 'Print this help menu'
complete -c primesieve -s n -l nth-prime -d 'Find the nth prime, e. g.  100 -n finds the 100th prime'
complete -c primesieve -l no-status -d 'Turn off the progressing status'
complete -c primesieve -s p -l print -d 'Print primes or prime k-tuplets, 1 <= NUM <= 6'
complete -c primesieve -s q -l quiet -d 'Quiet mode, prints less output'
complete -c primesieve -s R -l RiemannR -d 'Approximate PrimePi(x) using the Riemann R function: R(x)'
complete -c primesieve -l RiemannR-inverse -d 'Approximate the nth prime using the inverse Riemann R function: R^-1(x)'
complete -c primesieve -s s -l size -d 'Set the size of the sieve array in KiB, 16 <= SIZE <= 8192'
complete -c primesieve -s S -l stress-test -d 'Run a stress test.  The MODE can be either CPU (default) or RAM'
complete -c primesieve -l test -d 'Run various correctness tests (< 1 minute)'
complete -c primesieve -s t -l threads -d 'Set the number of threads, 1 <= NUM <= CPU cores'
complete -c primesieve -l time -d 'Print the time elapsed in seconds'
complete -c primesieve -l timeout -d 'Set the stress test timeout in seconds'
complete -c primesieve -s v -l version -d 'Print version and license information'
complete -c primesieve -o c2 -d or
complete -c primesieve -o c3 -d or
complete -c primesieve -o c123 -d 'counts primes, twin primes and prime triplets'
complete -c primesieve -o p2
complete -c primesieve -o p3

