# printf_ngettext
# Autogenerated from man page /usr/share/man/man1/printf_ngettext.1.gz
complete -c printf_ngettext -s c -l context -d 'specify context for FORMAT'
complete -c printf_ngettext -s h -l help -d 'display this help and exit'
complete -c printf_ngettext -s V -l version -d 'display version information and exit '

