# printf_gettext
# Autogenerated from man page /usr/share/man/man1/printf_gettext.1.gz
complete -c printf_gettext -s c -l context -d 'specify context for FORMAT'
complete -c printf_gettext -s h -l help -d 'display this help and exit'
complete -c printf_gettext -s V -l version -d 'display version information and exit '

