# pyenv
# Autogenerated from man page /usr/share/man/man1/pyenv.1.gz
complete -c pyenv -s h -l help -d 'Show summary of options'
complete -c pyenv -s v -l version -d 'Show version of program.  COMPARISON'

