# randpktdump
# Autogenerated from man page /usr/share/man/man1/randpktdump.1.gz
complete -c randpktdump -l help
complete -c randpktdump -l version
complete -c randpktdump -l extcap-interfaces
complete -c randpktdump -l extcap-interface
complete -c randpktdump -l extcap-dlts
complete -c randpktdump -l extcap-config
complete -c randpktdump -l capture
complete -c randpktdump -l fifo
complete -c randpktdump -l maxbytes
complete -c randpktdump -l count
complete -c randpktdump -l delay
complete -c randpktdump -l random-type
complete -c randpktdump -l all-random
complete -c randpktdump -l type

