# randpkt
# Autogenerated from man page /usr/share/man/man1/randpkt.1.gz
complete -c randpkt -s b -d 'Default 5000'
complete -c randpkt -s c -d 'Default 1000'
complete -c randpkt -s F -d 'Default pcapng'
complete -c randpkt -s h -l help
complete -c randpkt -s r -d 'The packet type is determined randomly for each packet'
complete -c randpkt -s t -d 'Default Ethernet II frame'
complete -c randpkt -s v -l version
complete -c randpkt -l log-level
complete -c randpkt -l log-fatal
complete -c randpkt -l log-domains
complete -c randpkt -l log-debug
complete -c randpkt -l log-noisy
complete -c randpkt -l log-fatal-domains
complete -c randpkt -l log-file

