# rawshark
# Autogenerated from man page /usr/share/man/man1/rawshark.1.gz
complete -c rawshark -s d -d 'Specify how the packet data should be dissected'
complete -c rawshark -s F -d 'Add the matching field to the output'
complete -c rawshark -s h -l help
complete -c rawshark -s l -d 'Flush the standard output after the information for each packet is printed'
complete -c rawshark -s m
complete -c rawshark -s o -d 'Set a preference value, overriding the default value and any value read from …'
complete -c rawshark -s p -d 'Assume that packet data is preceded by a pcap_pkthdr struct as defined in pcap'
complete -c rawshark -s r -d 'Read packet data from input source'
complete -c rawshark -s R -l read-filter -d 'Cause the specified filter (which uses the syntax of read/display filters, ra…'
complete -c rawshark -s s
complete -c rawshark -s S -d 'Use the specified format string to print each field'
complete -c rawshark -s v -l version
complete -c rawshark -s Y -l display-filter -d 'Cause the specified filter (which uses the syntax of read/display filters, ra…'
complete -c rawshark -l disable-all-protocols
complete -c rawshark -l disable-protocol
complete -c rawshark -l disable-heuristic
complete -c rawshark -l enable-protocol -d 'Enable dissection of proto_name'
complete -c rawshark -l enable-heuristic
complete -c rawshark -s K -d 'Load kerberos crypto keys from the specified keytab file'
complete -c rawshark -s n
complete -c rawshark -s N -d 'Turn on name resolving only for particular types of addresses and port number…'
complete -c rawshark -l only-protocols
complete -c rawshark -s t -d 'Set the format of the packet timestamp displayed in the default time column'
complete -c rawshark -s u -d 'Specifies how packet timestamp formats in -t which are relative times (i. e'
complete -c rawshark -l log-level
complete -c rawshark -l log-fatal
complete -c rawshark -l log-domains
complete -c rawshark -l log-debug
complete -c rawshark -l log-noisy
complete -c rawshark -l log-fatal-domains
complete -c rawshark -l log-file

