# rdma_xclient
# Autogenerated from man page /usr/share/man/man1/rdma_xclient.1.gz
complete -c rdma_xclient -s s -d 'Specifies the address of the system that the rdma_server is running on'
complete -c rdma_xclient -s p -d 'Specifies the port number that the server listens on'

