# rdma-ndd
# Autogenerated from man page /usr/share/man/man8/rdma-ndd.8.gz
complete -c rdma-ndd -s f -l foreground -d 'Run in the foreground instead of as a daemon'
complete -c rdma-ndd -s d -l debug -d 'Log additional debugging information to syslog'
complete -c rdma-ndd -l systemd -d 'Enable systemd integration.  AUTHOR Ira Weiny < %ira. weiny@intel. com >'

