# reordercap
# Autogenerated from man page /usr/share/man/man1/reordercap.1.gz
complete -c reordercap -s h -l help
complete -c reordercap -s n
complete -c reordercap -s v -l version
complete -c reordercap -l log-level
complete -c reordercap -l log-fatal
complete -c reordercap -l log-domains
complete -c reordercap -l log-debug
complete -c reordercap -l log-noisy
complete -c reordercap -l log-fatal-domains
complete -c reordercap -l log-file

