# riostream
# Autogenerated from man page /usr/share/man/man1/riostream.1.gz
complete -c riostream -s s -d 'The network name or IP address of the server system listening for connections'
complete -c riostream -s b -d 'The local network address to bind to'
complete -c riostream -s B -d 'Indicates the size of the send and receive network buffers'
complete -c riostream -s I -d 'The number of times that the specified number of messages will be exchanged b…'
complete -c riostream -s C -d 'The number of messages to transfer from the client to the server and back aga…'
complete -c riostream -s S -d 'The size of each send transfer, in bytes'
complete -c riostream -s p -d 'The server\'s port number'

