# rmiregistry-openjdk21
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk21.1.gz
complete -c rmiregistry-openjdk21 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk21 -s J -s J -d 'Java interpreter'

