# rmiregistry-openjdk25
# Autogenerated from man page /usr/share/man/man1/rmiregistry-openjdk25.1.gz
complete -c rmiregistry-openjdk25 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk25 -s J -s J -d 'the Java interpreter'

