# rstream
# Autogenerated from man page /usr/share/man/man1/rstream.1.gz
complete -c rstream -s s -d 'The network name or IP address of the server system listening for connections'
complete -c rstream -s b -d 'The local network address to bind to'
complete -c rstream -s f -d 'Supported address formats are ip, ipv6, gid, or name'
complete -c rstream -s B -d 'Indicates the size of the send and receive network buffers'
complete -c rstream -s I -d 'The number of times that the specified number of messages will be exchanged b…'
complete -c rstream -s C -d 'The number of messages to transfer from the client to the server and back aga…'
complete -c rstream -s S -d 'The size of each send transfer, in bytes'
complete -c rstream -s p -d 'The server\'s port number'

