# rtkitctl
# Autogenerated from man page /usr/share/man/man8/rtkitctl.8.gz
complete -c rtkitctl -s h -l help -d 'Show a summary of options'
complete -c rtkitctl -l version -d 'Show version'
complete -c rtkitctl -l reset-known -d 'Reset real-time status of known threads'
complete -c rtkitctl -l reset-all -d 'Reset real-time status of all threads'
complete -c rtkitctl -l suspend -d 'Temporarily reset real-time status of known threads'
complete -c rtkitctl -l resume -d 'Restore real-time status of known threads temporarily reset by suspend'
complete -c rtkitctl -l start -d 'Start RealtimeKit if it is not running already'
complete -c rtkitctl -s k -l exit -d 'Terminate running RealtimeKit daemon'

