# saquery
# Autogenerated from man page /usr/share/man/man8/saquery.8.gz
complete -c saquery -s p -d 'get PathRecord info'
complete -c saquery -s N -d 'get NodeRecord info'
complete -c saquery -s D -l list -d 'get NodeDescriptions of CAs only'
complete -c saquery -s S -d 'get ServiceRecord info'
complete -c saquery -s I -d 'get InformInfoRecord (subscription) info'
complete -c saquery -s L -d 'return the Lids of the name specified'
complete -c saquery -s l -d 'return the unique Lid of the name specified'
complete -c saquery -s G -d 'return the Guids of the name specified'
complete -c saquery -s O -d 'return the name for the Lid specified'
complete -c saquery -s U -d 'return the name for the Guid specified'
complete -c saquery -s c -d 'get the SA\'s class port info'
complete -c saquery -s s -d 'return the PortInfoRecords with isSM or isSMdisabled capability mask bit on'
complete -c saquery -s g -d 'get multicast group info'
complete -c saquery -s m -d 'get multicast member info'
complete -c saquery -s x -d 'get LinkRecord info'
complete -c saquery -l src-to-dst -d 'get a PathRecord for <src:dst> where src and dst are either node names or LIDs'
complete -c saquery -l sgid-to-dgid -d 'get a PathRecord for sgid to dgid where both GIDs are in an IPv6 format accep…'
complete -c saquery -l smkey -d 'use SM_Key value for the query.  Will be used only with "trusted" queries'
complete -c saquery -s K -l show_keys -d 'show security keys (mkey, smkey, etc. ) associated with the request'
complete -c saquery -l pkey -d 'is specified then saquery will prompt for a value'
complete -c saquery -l qkey -d 'then saquery will prompt for a value'
complete -c saquery -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c saquery -s e -d 'show send and receive errors (timeouts and others)'
complete -c saquery -s v -l verbose -d 'increase the application verbosity level'
complete -c saquery -l outstanding_smps -s o -d 'Specify the number of outstanding SMP\'s which should be issued during the sca…'
complete -c saquery -l slid
complete -c saquery -l dlid
complete -c saquery -l mlid
complete -c saquery -l sgid
complete -c saquery -l dgid
complete -c saquery -l gid
complete -c saquery -l mgid
complete -c saquery -l reversible
complete -c saquery -l numb_path
complete -c saquery -l qos_class
complete -c saquery -l sl
complete -c saquery -l mtu
complete -c saquery -l rate
complete -c saquery -l pkt_lifetime
complete -c saquery -l tclass
complete -c saquery -l flow_label
complete -c saquery -l hop_limit
complete -c saquery -l scope
complete -c saquery -l join_state
complete -c saquery -l proxy_join
complete -c saquery -l service_id
complete -c saquery -s C -l Ca
complete -c saquery -s P -l Port -d 'Local port Selection'
complete -c saquery -s h -l help
complete -c saquery -s V -l version -d 'Configuration flags'
complete -c saquery -s t -l timeout
complete -c saquery -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c saquery -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf COMMON FILES CONFIG FILE'

