# sdjournal
# Autogenerated from man page /usr/share/man/man1/sdjournal.1.gz
complete -c sdjournal -l help
complete -c sdjournal -l version
complete -c sdjournal -l extcap-interfaces
complete -c sdjournal -l extcap-interface
complete -c sdjournal -l extcap-dlts
complete -c sdjournal -l extcap-config
complete -c sdjournal -l capture
complete -c sdjournal -l fifo
complete -c sdjournal -l start-from -d 'Start from the last <entry count> entries, similar to the "-n" or "--lines" a…'

