# serialver-openjdk25
# Autogenerated from man page /usr/share/man/man1/serialver-openjdk25.1.gz
complete -c serialver-openjdk25 -o classpath -d 'Sets the search path for application classes and resources'
complete -c serialver-openjdk25 -o Joption -d 'Passes the specified option to the Java Virtual Machine, where option is one …'

