# setlogcons
# Autogenerated from man page /usr/share/man/man8/setlogcons.8.gz
complete -c setlogcons -s C -l console -d 'the console device to be used'
complete -c setlogcons -s V -l version -d 'print version number'
complete -c setlogcons -s h -l help -d 'print this usage message'

