# sg3_utils_json
# Autogenerated from man page /usr/share/man/man8/sg3_utils_json.8.gz
complete -c sg3_utils_json -s j -l json -d 'JO is a string of zero or more characters whose order is not significant apar…'
complete -c sg3_utils_json -s J -d 'shorter form may also take an argument but an "=" must precede the JO argumen…'
complete -c sg3_utils_json -l js-file -d 'output is in JSON format and it is sent to a file named JFN'
complete -c sg3_utils_json -l verbose -d 'most utilities support is more general'
complete -c sg3_utils_json -l brief -l quiet -d 'cases (i. e \'sg_inq --descriptors\') the JSON output is expanded'

