# sg_decode_sense
# Autogenerated from man page /usr/share/man/man8/sg_decode_sense.8.gz
complete -c sg_decode_sense -s b -l binary -d 'the data is read in binary from a file called BFN'
complete -c sg_decode_sense -s c -l cdb -d 'treat the given string of hex arguments as bytes in a SCSI CDB and decode the…'
complete -c sg_decode_sense -s e -l err -d 'ES should be an "exit status" value between 0 and 255 that is available from …'
complete -c sg_decode_sense -s f -l file -d 'the sense data is read in ASCII hexadecimal from a file called HFN'
complete -c sg_decode_sense -s h -l help -d 'output the usage message then exit'
complete -c sg_decode_sense -s H -l hex -d 'this option is used once in conjunction with --write=WFN in order to change t…'
complete -c sg_decode_sense -s i -l inhex -d 'same action as --file=HFN'
complete -c sg_decode_sense -s I -l ignore-first -d 'many programs that output hex bytes (e. g'
complete -c sg_decode_sense -s j -l json -d 'output is in JSON format instead of plain text form'
complete -c sg_decode_sense -s J -l js-file -d 'output is in JSON format and it is sent to a file named JFN'
complete -c sg_decode_sense -s N -l nodecode -d 'Do not decode the given data as sense or a cdb'
complete -c sg_decode_sense -s n -l nospace -d 'expect ASCII hexadecimal to be a string of hexadecimal digits with no spaces …'
complete -c sg_decode_sense -s s -l status -d 'where SS is a SCSI status byte value, given in hexadecimal'
complete -c sg_decode_sense -s v -l verbose -d 'increase the degree of verbosity (debug messages)'
complete -c sg_decode_sense -s V -l version -d 'output version string then exit'
complete -c sg_decode_sense -s w -l write -d 'writes the sense data out to a file called WFN.  If necessary WFN is created'

