# sg_rep_density
# Autogenerated from man page /usr/share/man/man8/sg_rep_density.8.gz
complete -c sg_rep_density -s h -l help -d 'output the usage message then exit'
complete -c sg_rep_density -s H -l hex -d 'output the response in hexadecimal to stdout'
complete -c sg_rep_density -s i -l inhex -d 'where FN is a file name whose contents are assumed to be ASCII hexadecimal'
complete -c sg_rep_density -s m -l maxlen -d 'where LEN is the (maximum) response length in bytes'
complete -c sg_rep_density -s M -l media -d 'sets the MEDIA bit in the cdb which causes the density codes (or medium types…'
complete -c sg_rep_density -s r -l raw -d 'output the SCSI response (i. e'
complete -c sg_rep_density -s R -l readonly -d 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag)'
complete -c sg_rep_density -s t -l typem -d 'sets the MEDIUM TYPE bit in the cdb which causes the medium types supported b…'
complete -c sg_rep_density -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_rep_density -s V -l version -d 'print the version string and then exit'

