# sg_rem_rest_elem
# Autogenerated from man page /usr/share/man/man8/sg_rem_rest_elem.8.gz
complete -c sg_rem_rest_elem -s c -l capacity -d 'RC stands for Requested Capacity and is the number of logical blocks the DEVI…'
complete -c sg_rem_rest_elem -s e -l element -d 'where EID is an element identifier which is a 32 bit unsigned integer startin…'
complete -c sg_rem_rest_elem -s h -l help -d 'output the usage message then exit'
complete -c sg_rem_rest_elem -s q -l quick -d 'the default action (i. e'
complete -c sg_rem_rest_elem -s r -l remove -d 'causes the REMOVE ELEMENT AND TRUNCATE command to be sent to the DEVICE'
complete -c sg_rem_rest_elem -s R -l restore -d 'causes the RESTORE ELEMENTS AND REBUILD command to be sent to the DEVICE'
complete -c sg_rem_rest_elem -s t -l timeout -d 'where SE is the command timeout in seconds'
complete -c sg_rem_rest_elem -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_rem_rest_elem -l tmo
complete -c sg_rem_rest_elem -s V -l version -d 'print the version string and then exit'

