# sg_sat_datetime
# Autogenerated from man page /usr/share/man/man8/sg_sat_datetime.8.gz
complete -c sg_sat_datetime -s d -l dma -d 'use READ LOG DMA EXT to read the date and time value from the device'
complete -c sg_sat_datetime -s e -l elapsed -d 'assume the date and time from READ LOG [DMA] EXT is an elapsed time from an e…'
complete -c sg_sat_datetime -s f -l format -d 'output the date and time formatted using the default locale'
complete -c sg_sat_datetime -s h -l help -d 'output the usage message then exit'
complete -c sg_sat_datetime -s H -l hex -d 'output the date and time in ASCII hexadecimal'
complete -c sg_sat_datetime -s m -l milliseconds -d 'where MS is the number of milliseconds since 1970-01-01 00:00:00 UTC to set i…'
complete -c sg_sat_datetime -s R -l readonly -d 'open the DEVICE read-only'
complete -c sg_sat_datetime -s s -l seconds -d 'where SECS is the number of seconds since 1970-01-01 00:00:00 UTC to set in t…'
complete -c sg_sat_datetime -s S -l srep -d 'report the number of seconds since 1970-01-01 00:00:00 UTC'
complete -c sg_sat_datetime -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_sat_datetime -s V -l version -d 'print the version string and then exit'

