# sg_write_attr
# Autogenerated from man page /usr/share/man/man8/sg_write_attr.8.gz
complete -c sg_write_attr -s e -l enumerate -d 'enumerates all known attributes'
complete -c sg_write_attr -s E -l element -d 'where EA is an element address which is placed in the WRITE ATTRIBUTE cdb'
complete -c sg_write_attr -s h -l help -d 'output the usage message then exit'
complete -c sg_write_attr -s H -l hex -d 'used together with the input file (-i, --in=FN) to indicate input contents is…'
complete -c sg_write_attr -s i -l in -d 'FN is treated as a file name (or \'-\' for stdin) which contains attribute-valu…'
complete -c sg_write_attr -s l -l lvn -d 'where LVN is placed in the "logical volume number" field of the cdb'
complete -c sg_write_attr -s p -l pn -d 'where PN is placed in the "partition number" field of the cdb'
complete -c sg_write_attr -s r -l raw -d 'used together with the input file (-i, --in=FN) to indicate input format is b…'
complete -c sg_write_attr -s c -l wtc -d 'sets the WRITE THROUGH CACHE bit in the WRITE ATTRIBUTE cdb'
complete -c sg_write_attr -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_write_attr -s V -l version -d 'print the version string and then exit'

