# sg_z_act_query
# Autogenerated from man page /usr/share/man/man8/sg_z_act_query.8.gz
complete -c sg_z_act_query -s A -l activate -d 'sends a ZONE ACTIVATE command to the DEVICE.  The default (i. e'
complete -c sg_z_act_query -s a -l all -d 'sets the ALL field in the cdb'
complete -c sg_z_act_query -s f -l force -d 'when decoding the response to this command, certain sanity checks are done an…'
complete -c sg_z_act_query -s h -l help -d 'output the usage message then exit'
complete -c sg_z_act_query -s H -l hex -d 'output the response in hexadecimal to stdout'
complete -c sg_z_act_query -s i -l inhex -d 'where FN is a file name whose contents are assumed to be ASCII hexadecimal'
complete -c sg_z_act_query -s m -l maxlen -d 'where LEN is the (maximum) response length in bytes'
complete -c sg_z_act_query -s n -l num -d 'where ZS is placed in the "Number of zones" field in the cdb'
complete -c sg_z_act_query -s o -l other -d 'where the ZDID value will be placed in the "Other zone domain ID" field of th…'
complete -c sg_z_act_query -s q -l query -d 'causes the ZONE QUERY command to be sent to the DEVICE'
complete -c sg_z_act_query -s r -l raw -d 'output response in binary (to stdout) unless the --inhex=FN option is also gi…'
complete -c sg_z_act_query -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_z_act_query -s V -l version -d 'print the version string and then exit'
complete -c sg_z_act_query -s z -l zone -d 'where ID is placed in the cdb\'s ZONE ID field'

