# sminfo
# Autogenerated from man page /usr/share/man/man8/sminfo.8.gz
complete -c sminfo -s s -l state -d '0 not active . sp 1 discovering . sp 2 standby . sp 3 master'
complete -c sminfo -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c sminfo -s e -d 'show send and receive errors (timeouts and others)'
complete -c sminfo -s v -l verbose -d 'increase the application verbosity level'
complete -c sminfo -s y -l m_key -d 'use the specified M_key for requests'
complete -c sminfo -s p -l priority
complete -c sminfo -s a -l activity -d 'Addressing Flags'
complete -c sminfo -s D -l Direct -d 'Examples:    [options] -D [options] "0"          # self port    [options] -D …'
complete -c sminfo -s G -l Guid
complete -c sminfo -s L -l Lid -d 'Port Selection flags'
complete -c sminfo -s C -l Ca
complete -c sminfo -s P -l Port -d 'Local port Selection'
complete -c sminfo -s h -l help
complete -c sminfo -s V -l version -d 'Configuration flags'
complete -c sminfo -s t -l timeout
complete -c sminfo -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

