# smpdump
# Autogenerated from man page /usr/share/man/man8/smpdump.8.gz
complete -c smpdump -s s -l string -d 'Print strings in packet if possible'
complete -c smpdump -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c smpdump -s e -d 'show send and receive errors (timeouts and others)'
complete -c smpdump -s v -l verbose -d 'increase the application verbosity level'
complete -c smpdump -s D -l Direct -d 'Examples:    [options] -D [options] "0"          # self port    [options] -D …'
complete -c smpdump -s L -l Lid -d 'Port Selection flags'
complete -c smpdump -s C -l Ca
complete -c smpdump -s P -l Port -d 'Local port Selection'
complete -c smpdump -s h -l help
complete -c smpdump -s V -l version -d 'Configuration flags'
complete -c smpdump -s t -l timeout
complete -c smpdump -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

