# smpquery
# Autogenerated from man page /usr/share/man/man8/smpquery.8.gz
complete -c smpquery -s c -l combined -d 'Use Combined route address argument <lid> <DR_Path>'
complete -c smpquery -s x -l extended -d 'Set SMSupportsExtendedSpeeds bit 31 in AttributeModifier (only impacts PortIn…'
complete -c smpquery -s K -l show_keys -d 'show security keys (mkey, smkey, etc. ) associated with the request'
complete -c smpquery -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c smpquery -s e -d 'show send and receive errors (timeouts and others)'
complete -c smpquery -s v -l verbose -d 'increase the application verbosity level'
complete -c smpquery -s y -l m_key -d 'use the specified M_key for requests'
complete -c smpquery -s D -l Direct -d 'Examples:    [options] -D [options] "0"          # self port    [options] -D …'
complete -c smpquery -s G -l Guid
complete -c smpquery -s L -l Lid
complete -c smpquery -s s -l sm_port -d 'Port Selection flags'
complete -c smpquery -s C -l Ca
complete -c smpquery -s P -l Port -d 'Local port Selection'
complete -c smpquery -s h -l help
complete -c smpquery -s V -l version -d 'Configuration flags'
complete -c smpquery -s t -l timeout
complete -c smpquery -l node-name-map -d 'This file maps GUIDs to more user friendly names.   See FILES section'
complete -c smpquery -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

