# snapperd
# Autogenerated from man page /usr/share/man/man8/snapperd.8.gz
complete -c snapperd -l logger-type -d 'Set the logger type.  Possible values are none, stdout, logfile and syslog'
complete -c snapperd -l debug -d 'Turn on debugging'

