# snbk
# Autogenerated from man page /usr/share/man/man8/snbk.8.gz
complete -c snbk -s q -l quiet
complete -c snbk -s v -l verbose
complete -c snbk -l debug
complete -c snbk -l utc
complete -c snbk -l iso
complete -c snbk -s t -l table-style
complete -c snbk -l machine-readable
complete -c snbk -l csvout
complete -c snbk -l jsonout
complete -c snbk -l separator
complete -c snbk -l no-headers
complete -c snbk -s b -l backup-config
complete -c snbk -l no-dbus
complete -c snbk -l target-mode
complete -c snbk -l automatic
complete -c snbk -l version

