# spit
# Autogenerated from man page /usr/share/man/man1/spit.1.gz
complete -c spit -l species -d 'Specifies the type of LLM.   The default and only valid value is \'ollama\''
complete -c spit -l url -d 'Specifies the URL of the server that runs the LLM'
complete -c spit -s m -l model -d 'Specifies the model to use'
complete -c spit -l to -d 'Specifies the target language'
complete -c spit -l prompt -d 'Specifies the prompt to use before standard input'
complete -c spit -l postprocess -d 'Specifies a command to post-process the output. PP Informative output:'
complete -c spit -s h -l help -d 'Display this help and exit'
complete -c spit -s V -l version -d 'Output version information and exit.  AUTHOR Written by Bruno Haible'

