# sshdig
# Autogenerated from man page /usr/share/man/man1/sshdig.1.gz
complete -c sshdig -l help
complete -c sshdig -l version
complete -c sshdig -l extcap-interfaces
complete -c sshdig -l extcap-interface
complete -c sshdig -l extcap-dlts
complete -c sshdig -l extcap-config
complete -c sshdig -l extcap-capture-filter
complete -c sshdig -l capture
complete -c sshdig -l fifo
complete -c sshdig -l remote-host
complete -c sshdig -l remote-port
complete -c sshdig -l remote-username
complete -c sshdig -l remote-password
complete -c sshdig -l sshkey
complete -c sshdig -l sshkey-passphrase
complete -c sshdig -l proxycommand
complete -c sshdig -l remote-capture-command-select
complete -c sshdig -l remote-capture-command
complete -c sshdig -l remote-priv
complete -c sshdig -l remote-priv-user
complete -c sshdig -l remote-filter
complete -c sshdig -l remote-count
complete -c sshdig -l remote-modern-bpf
complete -c sshdig -l remote-io-snaplen

