# sshdump
# Autogenerated from man page /usr/share/man/man1/sshdump.1.gz
complete -c sshdump -l help
complete -c sshdump -l version
complete -c sshdump -l extcap-interfaces
complete -c sshdump -l extcap-interface
complete -c sshdump -l extcap-dlts
complete -c sshdump -l extcap-config
complete -c sshdump -l extcap-capture-filter
complete -c sshdump -l capture
complete -c sshdump -l fifo
complete -c sshdump -l remote-host
complete -c sshdump -l remote-port
complete -c sshdump -l remote-username
complete -c sshdump -l remote-password
complete -c sshdump -l sshkey
complete -c sshdump -l sshkey-passphrase
complete -c sshdump -l proxycommand
complete -c sshdump -l remote-interface
complete -c sshdump -l remote-capture-command-select -d 'The selection of the build-in support for remote capture commands'
complete -c sshdump -l remote-capture-command -d 'A custom remote capture command that produces the remote stream that is shown…'
complete -c sshdump -l remote-priv
complete -c sshdump -l remote-priv-user
complete -c sshdump -l remote-filter
complete -c sshdump -l remote-count
complete -c sshdump -l remote-noprom -d 'sshdump --extcap-interface=sshdump --fifo=/tmp/ssh'
complete -c sshdump -s i -s P -s w -d 'sshdump --extcap-interface=sshdump --fifo=/tmp/ssh'
complete -c sshdump -s U -d 'Note To stop capturing CTRL+C/kill/terminate the application'

