# stratoshark
# Autogenerated from man page /usr/share/man/man1/stratoshark.1.gz
complete -c stratoshark -s r -d OPTIONS
complete -c stratoshark -s a -l autostop -d 'Specify a criterion that specifies when Stratoshark should stop writing to a …'
complete -c stratoshark -s b -l ring-buffer -d 'Cause Stratoshark to run in "multiple files" mode'
complete -c stratoshark -s c
complete -c stratoshark -s C
complete -c stratoshark -l capture-comment -d 'When performing a capture file from the command line, with the -k flag, add a…'
complete -c stratoshark -s D -l list-sources
complete -c stratoshark -l display
complete -c stratoshark -s f -d 'Set the capture filter expression'
complete -c stratoshark -l fullscreen -d 'Start Stratoshark in full screen mode (kiosk mode)'
complete -c stratoshark -s g
complete -c stratoshark -s h -l help
complete -c stratoshark -s H
complete -c stratoshark -s i -l source -d 'Set the name of the capture source or pipe to use for live capture'
complete -c stratoshark -s j
complete -c stratoshark -s J -d 'After reading in a capture file using the -r flag, jump to the event matching…'
complete -c stratoshark -s k -d 'Start the capture session immediately'
complete -c stratoshark -s l
complete -c stratoshark -s S
complete -c stratoshark -s L -l list-data-link-types
complete -c stratoshark -l list-time-stamp-types
complete -c stratoshark -s o -d 'Set a preference or recent value, overriding the default value and any value …'
complete -c stratoshark -s P -d 'Special path settings usually detected automatically'
complete -c stratoshark -l read-file
complete -c stratoshark -s R -l read-filter
complete -c stratoshark -l temp-dir -d 'Specifies the directory into which temporary files (including capture files) …'
complete -c stratoshark -l time-stamp-type
complete -c stratoshark -l update-interval
complete -c stratoshark -s v -l version
complete -c stratoshark -s w
complete -c stratoshark -s X -d 'Specify an option to be passed to an Stratoshark module'
complete -c stratoshark -s Y -l display-filter
complete -c stratoshark -s z -d 'Get Stratoshark to collect various types of statistics and display the result…'
complete -c stratoshark -s d -d 'Like Wireshark\'s Decode As'
complete -c stratoshark -l disable-all-protocols
complete -c stratoshark -l disable-protocol
complete -c stratoshark -l disable-heuristic
complete -c stratoshark -l enable-protocol -d 'Enable dissection of proto_name'
complete -c stratoshark -l enable-heuristic
complete -c stratoshark -s K -d 'Load kerberos crypto keys from the specified keytab file'
complete -c stratoshark -s n
complete -c stratoshark -s N -d 'Turn on name resolving only for particular types of addresses and port number…'
complete -c stratoshark -l only-protocols
complete -c stratoshark -s t -d 'Set the format of the packet timestamp displayed in the default time column'
complete -c stratoshark -s u -d 'Specifies how packet timestamp formats in -t which are relative times (i. e'
complete -c stratoshark -l log-level
complete -c stratoshark -l log-fatal
complete -c stratoshark -l log-domains
complete -c stratoshark -l log-debug
complete -c stratoshark -l log-noisy
complete -c stratoshark -l log-fatal-domains
complete -c stratoshark -l log-file

