# strato
# Autogenerated from man page /usr/share/man/man1/strato.1.gz
complete -c strato -s r
complete -c strato -s F -d 'specify a file format supported by dumpcap(1), viz.  pcapng or pcap'
complete -c strato -s Q -s P -s V -s O -d 'cause the corresponding output to be displayed even though other output is su…'
complete -c strato -s 2 -d 'Perform a two-pass analysis'
complete -c strato -s a -l autostop -d 'Specify a criterion that specifies when strato is to stop writing to a captur…'
complete -c strato -s A -d 'Specify a user and a password when strato captures from a rpcap:// interface …'
complete -c strato -s b -l ring-buffer -d 'Cause strato to run in "multiple files" mode'
complete -c strato -s B -l buffer-size -d 'Set capture buffer size (in MiB, default is 2 MiB)'
complete -c strato -s c -d 'Set the maximum number of packets to read when capturing live data'
complete -c strato -s C -d 'Run with the given configuration profile.  If used in conjunction with'
complete -c strato -l global-profile -d 'would be used'
complete -c strato -s D -l list-interfaces -d 'Print a list of the interfaces on which strato can capture, and exit'
complete -c strato -s e -d 'Add a field to the list of fields to display if -T ek|fields|json|pdml is sel…'
complete -c strato -s E -d 'Set an option controlling the printing of fields when -T fields is selected'
complete -c strato -s f -d 'Set the capture filter expression'
complete -c strato -s g
complete -c strato -s G -d 'The -G option will cause strato to dump one of several types of glossaries an…'
complete -c strato -s h -l help
complete -c strato -s H -d 'Read a list of entries from a "hosts" file, which will then be written to a c…'
complete -c strato -s i -l interface -d 'Set the name of the network interface or pipe to use for live packet capture'
complete -c strato -s j -d 'Protocol match filter used for ek|json|jsonraw|pdml output file types'
complete -c strato -s J -d 'Protocol top level filter used for ek|json|jsonraw|pdml output file types'
complete -c strato -s l -d 'Flush the standard output after the information for each packet is printed'
complete -c strato -s L -l list-data-link-types
complete -c strato -s o -d 'Set a preference value, overriding the default value and any value read from …'
complete -c strato -l print -d 'Decode and display the packet summary or details, even if writing raw packet …'
complete -c strato -s q -d 'When capturing packets, don\'t display the continuous count of packets capture…'
complete -c strato -l read-file -d 'Read packet data from infile, can be any supported capture file format (inclu…'
complete -c strato -s R -l read-filter -d 'Cause the specified filter (which uses the syntax of read/display filters, ra…'
complete -c strato -s s -l snapshot-length -d 'Set the default snapshot length to use when capturing live data'
complete -c strato -s S
complete -c strato -s T -d 'Set the format of the output when viewing decoded packet data'
complete -c strato -s x -d 'If -P is specified it will print the packet summary only, with both'
complete -c strato -l elastic-mapping-filter -d 'strato -G elastic-mapping --elastic-mapping-filter ip,udp,dns or adding the f…'
complete -c strato -l temp-dir -d 'Specifies the directory into which temporary files (including capture files) …'
complete -c strato -s U -d 'PDUs export, exports PDUs from infile to outfile according to the tap name gi…'
complete -c strato -s v -l version
complete -c strato -s w -d 'Write raw packet data to outfile or to the standard output if outfile is \\-'
complete -c strato -s W -d 'Save extra information in the file if the format supports it'
complete -c strato -l hexdump -d 'Cause strato to print a hex and ASCII dump of the packet data with the abilit…'
complete -c strato -s X -d 'Specify an option to be passed to a strato module'
complete -c strato -s Y -l display-filter -d 'Cause the specified filter (which uses the syntax of read/display filters, ra…'
complete -c strato -s M -d 'Automatically reset internal session when reached to specified number of pack…'
complete -c strato -s z -d 'Get strato to collect various types of statistics and display the result afte…'
complete -c strato -l capture-comment -d 'Add a capture comment to the output file, if supported by the output file for…'
complete -c strato -l list-time-stamp-types
complete -c strato -l time-stamp-type
complete -c strato -l update-interval
complete -c strato -l color
complete -c strato -l no-duplicate-keys
complete -c strato -l export-objects -d 'Export all objects within a protocol into directory destdir'
complete -c strato -l print-timers
complete -c strato -l compress -d 'Compress the output file using the type compression format'
complete -c strato -s d -d 'Like Wireshark\'s Decode As'
complete -c strato -l disable-all-protocols
complete -c strato -l disable-protocol
complete -c strato -l disable-heuristic
complete -c strato -l enable-protocol -d 'Enable dissection of proto_name'
complete -c strato -l enable-heuristic
complete -c strato -s K -d 'Load kerberos crypto keys from the specified keytab file'
complete -c strato -s n
complete -c strato -s N -d 'Turn on name resolving only for particular types of addresses and port number…'
complete -c strato -l only-protocols
complete -c strato -s t -d 'Set the format of the packet timestamp displayed in the default time column'
complete -c strato -s u -d 'Specifies how packet timestamp formats in -t which are relative times (i. e'
complete -c strato -l log-level
complete -c strato -l log-fatal
complete -c strato -l log-domains
complete -c strato -l log-debug
complete -c strato -l log-noisy
complete -c strato -l log-fatal-domains
complete -c strato -l log-file

