# swww-kill
# Autogenerated from man page /usr/share/man/man1/swww-kill.1.gz
complete -c swww-kill -s n -l namespace -d 'Which wayland namespace to send this command to'
complete -c swww-kill -s h -l help -d 'Print help (see a summary with \'-h\')'

