# swww-restore
# Autogenerated from man page /usr/share/man/man1/swww-restore.1.gz
complete -c swww-restore -s n -l namespace -d 'Which wayland namespace to send this command to'
complete -c swww-restore -s o -l outputs -d 'Comma separated list of outputs to restore.  Use swww query to know which'
complete -c swww-restore -s h -l help -d 'Print help (see a summary with \'-h\')'

