# swww-query
# Autogenerated from man page /usr/share/man/man1/swww-query.1.gz
complete -c swww-query -s n -l namespace -d 'Which wayland namespace to send this command to'
complete -c swww-query -s h -l help -d 'Print help (see a summary with \'-h\')'

