# telnetd
# Autogenerated from man page /usr/share/man/man8/telnetd.8.gz
complete -c telnetd -s D -l debug -d 'set debugging level'
complete -c telnetd -s E -l exec-login -d 'set program to be executed instead of standard login(1)'
complete -c telnetd -s h -l no-hostinfo -d 'do not print host information before login has been completed'
complete -c telnetd -s l -l linemode -d 'set line mode'
complete -c telnetd -s n -l no-keepalive -d 'disable TCP keep-alive'
complete -c telnetd -s U -l reverse-lookup -d 'refuse connections from addresses that cannot be mapped back into a symbolic …'
complete -c telnetd -s '?' -l help -d 'give this help list'
complete -c telnetd -l usage -d 'give a short usage message'
complete -c telnetd -s V -l version -d 'print program version'

