# text2pcap
# Autogenerated from man page /usr/share/man/man1/text2pcap.1.gz
complete -c text2pcap -s a -d 'Enables ASCII text dump identification'
complete -c text2pcap -s b -d 'Specify the base (radix) of the encoding of the packet data in regex mode'
complete -c text2pcap -s D -d 'Indicates that the text before each input packet may start either with an I o…'
complete -c text2pcap -s e -d 'Include a dummy Ethernet header before each packet'
complete -c text2pcap -s E -d 'Sets the packet encapsulation type of the output capture file'
complete -c text2pcap -s F -d 'Sets the file format of the output capture file'
complete -c text2pcap -s h -l help
complete -c text2pcap -s i -d 'Include dummy IP headers before each packet'
complete -c text2pcap -s l -d 'Sets the packet encapsulation type of the output capture file, using pcap lin…'
complete -c text2pcap -s m -d 'Set the maximum packet length, default is 262144'
complete -c text2pcap -s N
complete -c text2pcap -s o -d 'Specify the radix for the offsets (hex, octal, decimal, or none)'
complete -c text2pcap -s P -d 'Include an EXPORTED_PDU header before each packet'
complete -c text2pcap -s q
complete -c text2pcap -s r -d 'Process the file in regex mode using regex as described above'
complete -c text2pcap -s s -d 'Include dummy SCTP headers before each packet'
complete -c text2pcap -s S -d 'Include dummy SCTP headers before each packet'
complete -c text2pcap -s t -d 'Treats the text before the packet as a date/time code; timefmt is a format st…'
complete -c text2pcap -s T -d 'Include dummy TCP headers before each packet'
complete -c text2pcap -s u -d 'Include dummy UDP headers before each packet'
complete -c text2pcap -s v -l version
complete -c text2pcap -s 4 -d 'Prepend dummy IP header with specified IPv4 source and destination addresses'
complete -c text2pcap -s 6 -d 'Prepend dummy IP header with specified IPv6 source and destination addresses'
complete -c text2pcap -l compress -d 'Compress the output file using the type compression format'
complete -c text2pcap -l little-endian -d 'Treat multiple byte groups as in little-endian byte order, instead of the def…'
complete -c text2pcap -l log-level
complete -c text2pcap -l log-fatal
complete -c text2pcap -l log-domains
complete -c text2pcap -l log-debug
complete -c text2pcap -l log-noisy
complete -c text2pcap -l log-fatal-domains
complete -c text2pcap -l log-file

