# thin_migrate
# Autogenerated from man page /usr/share/man/man8/thin_migrate.8.gz
complete -c thin_migrate -s h -l help -d 'Print help and exit'
complete -c thin_migrate -s V -l version -d 'Print version information and exit'
complete -c thin_migrate -l source-dev -d 'The input read-only thin device to copy'
complete -c thin_migrate -l dest-dev -d 'The output device as the copy destination'
complete -c thin_migrate -l dest-file -d 'The output file as the copy destination'
complete -c thin_migrate -s q -l quit -d 'Suppress output messages, return only exit code'
complete -c thin_migrate -l buffer-size-meg -d 'Specify the size of the data buffers, in megabytes.  EXAMPLE'

