# tinysparql-introspect
# Autogenerated from man page /usr/share/man/man1/tinysparql-introspect.1.gz
complete -c tinysparql-introspect -s b -l dbus-service -d 'Connects to a SPARQL endpoint at a D-Bus name'
complete -c tinysparql-introspect -s d -l database-path -d 'Connects to a database by location in the filesystem'
complete -c tinysparql-introspect -s r -l remote-service -d 'Connects to a HTTP SPARQL endpoint'
complete -c tinysparql-introspect -s c -l list-classes -d 'Returns a list of classes which describe the ontology used for storing data'
complete -c tinysparql-introspect -s x -l list-class-prefixes -d 'Returns a list of prefixes in shortened and long form'
complete -c tinysparql-introspect -s p -l list-properties -d 'Returns a list of properties which pertain to a class'
complete -c tinysparql-introspect -s n -l list-notifies -d 'Returns a list of classes which are notified over D-Bus about any changes tha…'
complete -c tinysparql-introspect -s i -l list-indexes -d 'Returns a list of properties which are indexed in the database'
complete -c tinysparql-introspect -s g -l list-graphs -d 'List all the named graphs in the database'
complete -c tinysparql-introspect -s t -l tree -d 'Prints a tree showing all parent classes of class in the ontology'
complete -c tinysparql-introspect -s s -l search -d 'Returns a list of classes and properties which partially match needle in the …'
complete -c tinysparql-introspect -l query
complete -c tinysparql-introspect -l get-shorthand -d and
complete -c tinysparql-introspect -l get-longhand -d 'for details).  If no class is given, the entire tree is shown'

