# tinysparql-sql
# Autogenerated from man page /usr/share/man/man1/tinysparql-sql.1.gz
complete -c tinysparql-sql -s f -l file -d 'Use a file with SPARQL content to query'
complete -c tinysparql-sql -s q -l query -d 'Use a sql string to query the database with'

