# tinysparql-query
# Autogenerated from man page /usr/share/man/man1/tinysparql-query.1.gz
complete -c tinysparql-query -s b -l dbus-service -d 'Connects to a SPARQL endpoint at a D-Bus name'
complete -c tinysparql-query -s d -l database-path -d 'Connects to a database by location in the filesystem'
complete -c tinysparql-query -s r -l remote-service -d 'Connects to a HTTP SPARQL endpoint'
complete -c tinysparql-query -s f -l file -d 'Use a file with SPARQL content to query or update'
complete -c tinysparql-query -s u -l update -d 'This has to be used with --query'
complete -c tinysparql-query -s a -l arg -d 'Provides an argument for a parameter declared in the SPARQL query string'
complete -c tinysparql-query -l query

