# tshark
# Autogenerated from man page /usr/share/man/man1/tshark.1.gz
complete -c tshark -s r
complete -c tshark -s F -d 'specify a file format supported by dumpcap(1), viz.  pcapng or pcap'
complete -c tshark -s Q -s P -s V -s O -d 'cause the corresponding output to be displayed even though other output is su…'
complete -c tshark -s 2 -d 'Perform a two-pass analysis'
complete -c tshark -s a -l autostop -d 'Specify a criterion that specifies when TShark is to stop writing to a captur…'
complete -c tshark -s A -d 'Specify a user and a password when TShark captures from a rpcap:// interface …'
complete -c tshark -s b -l ring-buffer -d 'Cause TShark to run in "multiple files" mode'
complete -c tshark -s B -l buffer-size -d 'Set capture buffer size (in MiB, default is 2 MiB)'
complete -c tshark -s c -d 'Set the maximum number of packets to read when capturing live data'
complete -c tshark -s C -d 'Run with the given configuration profile'
complete -c tshark -s D -l list-interfaces -d 'Print a list of the interfaces on which TShark can capture, and exit'
complete -c tshark -s e -d 'Add a field to the list of fields to display if -T ek|fields|json|pdml is sel…'
complete -c tshark -s E -d 'Set an option controlling the printing of fields when -T fields is selected'
complete -c tshark -s f -d 'Set the capture filter expression'
complete -c tshark -s g
complete -c tshark -s G -d 'The -G option will cause TShark to dump one of several types of glossaries an…'
complete -c tshark -s h -l help
complete -c tshark -s H -d 'Read a list of entries from a "hosts" file, which will then be written to a c…'
complete -c tshark -s i -l interface -d 'Set the name of the network interface or pipe to use for live packet capture'
complete -c tshark -s I -l monitor-mode -d 'Put the interface in "monitor mode"; this is supported only on IEEE 802'
complete -c tshark -s j -d 'Protocol match filter used for ek|json|jsonraw|pdml output file types'
complete -c tshark -s J -d 'Protocol top level filter used for ek|json|jsonraw|pdml output file types'
complete -c tshark -s l -d 'Flush the standard output after the information for each packet is printed'
complete -c tshark -s L -l list-data-link-types
complete -c tshark -s o -d 'Set a preference value, overriding the default value and any value read from …'
complete -c tshark -s p -l no-promiscuous-mode -d 'Don\'t put the interface into promiscuous mode'
complete -c tshark -l print -d 'Decode and display the packet summary or details, even if writing raw packet …'
complete -c tshark -s q -d 'When capturing packets, don\'t display the continuous count of packets capture…'
complete -c tshark -l read-file -d 'Read packet data from infile, can be any supported capture file format (inclu…'
complete -c tshark -s R -l read-filter -d 'Cause the specified filter (which uses the syntax of read/display filters, ra…'
complete -c tshark -s s -l snapshot-length -d 'Set the default snapshot length to use when capturing live data'
complete -c tshark -s S
complete -c tshark -s T -d 'Set the format of the output when viewing decoded packet data'
complete -c tshark -s x -d 'If -P is specified it will print the packet summary only, with both'
complete -c tshark -l elastic-mapping-filter -d 'tshark -G elastic-mapping --elastic-mapping-filter ip,udp,dns or adding the f…'
complete -c tshark -l temp-dir -d 'Specifies the directory into which temporary files (including capture files) …'
complete -c tshark -s U -d 'PDUs export, exports PDUs from infile to outfile according to the tap name gi…'
complete -c tshark -s v -l version
complete -c tshark -s w -d 'Write raw packet data to outfile or to the standard output if outfile is \\-'
complete -c tshark -s W -d 'Save extra information in the file if the format supports it'
complete -c tshark -l hexdump -d 'Cause TShark to print a hex and ASCII dump of the packet data with the abilit…'
complete -c tshark -s X -d 'Specify an option to be passed to a TShark module'
complete -c tshark -s y -l linktype -d 'Set the data link type to use while capturing packets'
complete -c tshark -s Y -l display-filter -d 'Cause the specified filter (which uses the syntax of read/display filters, ra…'
complete -c tshark -s M -d 'Automatically reset internal session when reached to specified number of pack…'
complete -c tshark -s z -d 'Get TShark to collect various types of statistics and display the result afte…'
complete -c tshark -s n
complete -c tshark -l capture-comment -d 'Add a capture comment to the output file, if supported by the output file for…'
complete -c tshark -l list-time-stamp-types
complete -c tshark -l time-stamp-type
complete -c tshark -l update-interval
complete -c tshark -l color
complete -c tshark -l no-duplicate-keys
complete -c tshark -l export-objects -d 'Export all objects within a protocol into directory destdir'
complete -c tshark -l print-timers
complete -c tshark -l compress -d 'Compress the output file using the type compression format'
complete -c tshark -s d -d 'Like Wireshark\'s Decode As'
complete -c tshark -l disable-all-protocols
complete -c tshark -l disable-protocol
complete -c tshark -l disable-heuristic
complete -c tshark -l enable-protocol -d 'Enable dissection of proto_name'
complete -c tshark -l enable-heuristic
complete -c tshark -s K -d 'Load kerberos crypto keys from the specified keytab file'
complete -c tshark -s N -d 'Turn on name resolving only for particular types of addresses and port number…'
complete -c tshark -l only-protocols
complete -c tshark -s t -d 'Set the format of the packet timestamp displayed in the default time column'
complete -c tshark -s u -d 'Specifies how packet timestamp formats in -t which are relative times (i. e'
complete -c tshark -l log-level
complete -c tshark -l log-fatal
complete -c tshark -l log-domains
complete -c tshark -l log-debug
complete -c tshark -l log-noisy
complete -c tshark -l log-fatal-domains
complete -c tshark -l log-file

