# typst-info
# Autogenerated from man page /usr/share/man/man1/typst-info.1.gz
complete -c typst-info -s f -l format -d 'The format to serialize in, if it should be machine-readable'
complete -c typst-info -l pretty -d 'Whether to pretty-print the serialized output.   Only applies to JSON format'
complete -c typst-info -s h -l help -d 'Print help (see a summary with \\-h)'

