# typst-update
# Autogenerated from man page /usr/share/man/man1/typst-update.1.gz
complete -c typst-update -l force -d 'Forces a downgrade to an older version (required for downgrading)'
complete -c typst-update -l revert -d 'Reverts to the version from before the last update (only possible if `typst u…'
complete -c typst-update -l backup-path -d 'Custom path to the backup file created on update and used by `--revert`, defa…'
complete -c typst-update -s h -l help -d 'Print help'

