# typst-fonts
# Autogenerated from man page /usr/share/man/man1/typst-fonts.1.gz
complete -c typst-fonts -l font-path -d 'Adds additional directories that are recursively searched for fonts'
complete -c typst-fonts -l ignore-system-fonts -d 'Ensures system fonts won\\*(Aqt be searched, unless explicitly included via `-…'
complete -c typst-fonts -l ignore-embedded-fonts -d 'Ensures fonts embedded into Typst won\\*(Aqt be considered '
complete -c typst-fonts -l variants -d 'Also lists style variants of each font family'
complete -c typst-fonts -s h -l help -d 'Print help (see a summary with \\-h)'

