# tzselect
# Autogenerated from man page /usr/share/man/man8/tzselect.8.gz
complete -c tzselect -s c -d 'Instead of asking for continent and then country and then city, ask for selec…'
complete -c tzselect -s n -d 'When  -c is used, display the closest  limit locations (default 10)'
complete -c tzselect -l help -d 'Output help information and exit'
complete -c tzselect -l version -d 'Output version information and exit.  ENVIRONMENT VARIABLES'

