# ubxtool
# Autogenerated from man page /usr/share/man/man1/ubxtool.1.gz
complete -c ubxtool -s '?' -s h -l help
complete -c ubxtool -s c -l command
complete -c ubxtool -l device
complete -c ubxtool -s d -l disable
complete -c ubxtool -s e -l enable
complete -c ubxtool -s f -l file
complete -c ubxtool -s g -l getitem
complete -c ubxtool -l host
complete -c ubxtool -s i -l portid
complete -c ubxtool -s p -l preset
complete -c ubxtool -l port
complete -c ubxtool -s P -l protver
complete -c ubxtool -s r -o readonly
complete -c ubxtool -s R -l rawfile
complete -c ubxtool -s s -l inspeed
complete -c ubxtool -s S -l setspeed
complete -c ubxtool -s t -l timestamp
complete -c ubxtool -s v -l verbosity
complete -c ubxtool -s V -l version
complete -c ubxtool -s w -l wait
complete -c ubxtool -s x -l delitem
complete -c ubxtool -s z -l setitem

