# udpdump
# Autogenerated from man page /usr/share/man/man1/udpdump.1.gz
complete -c udpdump -l help
complete -c udpdump -l version
complete -c udpdump -l extcap-interfaces
complete -c udpdump -l extcap-interface
complete -c udpdump -l extcap-dlts
complete -c udpdump -l extcap-config
complete -c udpdump -l capture
complete -c udpdump -l fifo
complete -c udpdump -l port
complete -c udpdump -l payload

