# udpong
# Autogenerated from man page /usr/share/man/man1/udpong.1.gz
complete -c udpong -s s -d 'The network name or IP address of the server system listening for connections'
complete -c udpong -s b -d 'The local network address to bind to'
complete -c udpong -s B -d 'Indicates the size of the send and receive network buffers'
complete -c udpong -s C -d 'The number of messages to transfer from the client to the server and back aga…'
complete -c udpong -s S -d 'The size of each send transfer, in bytes.   (default 1000)'
complete -c udpong -s p -d 'The server\'s port number'

