# upower
# Autogenerated from man page /usr/share/man/man1/upower.1.gz
complete -c upower -s b -l battery -d 'Dump all parameters for battery devices'
complete -c upower -s d -l dump -d 'Dump all parameters for all devices'
complete -c upower -s e -l enumerate -d 'Enumerate the object paths of all devices on the system'
complete -c upower -s m -l monitor -d 'Connect to the UPower daemon and print a line every time a power source is ad…'
complete -c upower -l monitor-detail -d 'Like --monitor but prints the full details of the power source whenever an ev…'
complete -c upower -s i -l show-info -d 'Show information about the given device'
complete -c upower -s v -l version -d 'Print version information for the client and daemon'
complete -c upower -s h -l help -d 'Show help options'

