# upx
# Autogenerated from man page /usr/share/man/man1/upx.1.gz
complete -c upx -s q
complete -c upx -o qq
complete -c upx -o qqq
complete -c upx -l help
complete -c upx -l version
complete -c upx -l exact -d 'after decompression with option -d'
complete -c upx -s k
complete -c upx -s o
complete -c upx -l brute -l no-lzma -d 'o 4 Try if --overlay=strip works'

