# uuctl
# Autogenerated from man page /usr/share/man/man1/uuctl.1.gz
complete -c uuctl -s a -l all -d 'T}	T{ Show all units without filtering out uwsm\'s compositor services.  T} T{'
complete -c uuctl -s h -l help -d 'T}	T{ Show help and exit T} SEE ALSO'

