# uwsm-app
# Autogenerated from man page /usr/share/man/man1/uwsm-app.1.gz
complete -c uwsm-app -s s -d 'T}	T{ Slice selector (default: a): T} T{'
complete -c uwsm-app -s t -d 'T}	T{ Type of unit to launch (default: scope, can be preset by UWSM_APP_UNIT_…'
complete -c uwsm-app -s a -d 'T}	T{ Override app name (a substring in unit name).  T} T{'
complete -c uwsm-app -s u -d 'T}	T{ Override the whole autogenerated unit name.  T} T{'
complete -c uwsm-app -s d -d 'T}	T{ Unit Description.  T} T{'
complete -c uwsm-app -s S -d 'T}	T{ Silence stdout, stderr, or both.  T} T{'
complete -c uwsm-app -s T -d 'T}	T{ Launch app in a terminal'

