# valgrind
# Autogenerated from man page /usr/share/man/man1/valgrind.1.gz
complete -c valgrind -l tool
complete -c valgrind -s h -l help
complete -c valgrind -l help-debug
complete -c valgrind -l version
complete -c valgrind -s q -l quiet
complete -c valgrind -s v -l verbose
complete -c valgrind -l trace-children
complete -c valgrind -l trace-children-skip
complete -c valgrind -l trace-children-skip-by-arg
complete -c valgrind -l child-silent-after-fork
complete -c valgrind -l xml
complete -c valgrind -l vgdb
complete -c valgrind -l vgdb-error
complete -c valgrind -l vgdb-stop-at
complete -c valgrind -l track-fds
complete -c valgrind -l modify-fds
complete -c valgrind -l time-stamp
complete -c valgrind -l log-fd
complete -c valgrind -l log-file
complete -c valgrind -l log-socket
complete -c valgrind -l enable-debuginfod
complete -c valgrind -l xml-fd
complete -c valgrind -l xml-file -d or
complete -c valgrind -l xml-socket -d 'to specify where the XML is to be sent'
complete -c valgrind -s 1
complete -c valgrind -l xml-user-comment
complete -c valgrind -l demangle
complete -c valgrind -l num-callers
complete -c valgrind -l unw-stack-scan-thresh -l unw-stack-scan-frames
complete -c valgrind -l error-limit
complete -c valgrind -l error-exitcode
complete -c valgrind -l exit-on-first-error
complete -c valgrind -l error-markers
complete -c valgrind -l show-error-list
complete -c valgrind -s s
complete -c valgrind -l sigill-diagnostics
complete -c valgrind -l keep-debuginfo
complete -c valgrind -l show-below-main
complete -c valgrind -l fullpath-after
complete -c valgrind -l fullpath-after-specified
complete -c valgrind -l extra-debuginfo-path
complete -c valgrind -l debuginfo-server
complete -c valgrind -l allow-mismatched-debuginfo
complete -c valgrind -l suppressions
complete -c valgrind -l gen-suppressions
complete -c valgrind -l input-fd
complete -c valgrind -l dsymutil
complete -c valgrind -l max-stackframe
complete -c valgrind -l main-stacksize
complete -c valgrind -l max-threads
complete -c valgrind -l realloc-zero-bytes-frees
complete -c valgrind -l alignment
complete -c valgrind -l redzone-size
complete -c valgrind -l xtree-memory
complete -c valgrind -l keep-stacktraces -d or
complete -c valgrind -l xtree-memory-file
complete -c valgrind -l smc-check
complete -c valgrind -l read-inline-info
complete -c valgrind -l read-var-info
complete -c valgrind -l vgdb-poll
complete -c valgrind -l vgdb-shadow-registers
complete -c valgrind -l vgdb-prefix
complete -c valgrind -l run-libc-freeres
complete -c valgrind -l run-cxx-freeres
complete -c valgrind -l sim-hints
complete -c valgrind -l scheduling-quantum
complete -c valgrind -l fair-sched
complete -c valgrind -l kernel-variant
complete -c valgrind -l merge-recursive-frames
complete -c valgrind -l num-transtab-sectors
complete -c valgrind -l avg-transtab-entry-size -d '(about 40 MB per sector for Memcheck).  Use the option'
complete -c valgrind -l stats -d 'to obtain precise information about the memory used by a sector and the alloc…'
complete -c valgrind -l track-origins -d 'increases the size of the basic block translations.  Use'
complete -c valgrind -l aspace-minaddr
complete -c valgrind -l valgrind-stacksize
complete -c valgrind -l show-emwarns
complete -c valgrind -l require-text-symbol
complete -c valgrind -l soname-synonyms
complete -c valgrind -l progress-interval
complete -c valgrind -l leak-check
complete -c valgrind -l show-leak-kinds -d and
complete -c valgrind -l errors-for-leak-kinds
complete -c valgrind -l leak-resolution
complete -c valgrind -l leak-check-heuristics
complete -c valgrind -l show-reachable -l show-possibly-lost
complete -c valgrind -l xtree-leak
complete -c valgrind -l xtree-leak-file
complete -c valgrind -l undef-value-errors
complete -c valgrind -l partial-loads-ok
complete -c valgrind -l expensive-definedness-checks
complete -c valgrind -l freelist-vol
complete -c valgrind -l freelist-big-blocks
complete -c valgrind -l workaround-gcc296-bugs
complete -c valgrind -l ignore-range-below-sp -d 'to specify the exact range of offsets below the stack pointer that should be …'
complete -c valgrind -l show-mismatched-frees
complete -c valgrind -l show-realloc-size-zero
complete -c valgrind -l ignore-ranges
complete -c valgrind -l malloc-fill
complete -c valgrind -l free-fill
complete -c valgrind -l cachegrind-out-file
complete -c valgrind -l cache-sim
complete -c valgrind -l branch-sim
complete -c valgrind -l instr-at-start
complete -c valgrind -l I1
complete -c valgrind -l D1
complete -c valgrind -l LL
complete -c valgrind -l callgrind-out-file
complete -c valgrind -l dump-line
complete -c valgrind -l dump-instr
complete -c valgrind -l compress-strings
complete -c valgrind -l compress-pos
complete -c valgrind -l combine-dumps
complete -c valgrind -l dump-every-bb
complete -c valgrind -l dump-before
complete -c valgrind -l zero-before
complete -c valgrind -l dump-after
complete -c valgrind -l instr-atstart
complete -c valgrind -l collect-atstart
complete -c valgrind -l toggle-collect
complete -c valgrind -l collect-state
complete -c valgrind -l collect-jumps
complete -c valgrind -l collect-systime
complete -c valgrind -l collect-bus
complete -c valgrind -l free-is-write
complete -c valgrind -l track-lockorders
complete -c valgrind -l history-level
complete -c valgrind -l history-backtrace-size -d 'entries (default 8) or to'
complete -c valgrind -l delta-stacktrace
complete -c valgrind -l conflict-cache-size
complete -c valgrind -l check-stack-refs
complete -c valgrind -l ignore-thread-creation
complete -c valgrind -l check-stack-var
complete -c valgrind -l exclusive-threshold
complete -c valgrind -l join-list-vol
complete -c valgrind -l segment-merging
complete -c valgrind -l segment-merging-interval
complete -c valgrind -l shared-threshold
complete -c valgrind -l show-confl-seg
complete -c valgrind -l show-stack-usage
complete -c valgrind -l trace-addr
complete -c valgrind -l ptrace-addr
complete -c valgrind -l trace-alloc
complete -c valgrind -l trace-barrier
complete -c valgrind -l trace-cond
complete -c valgrind -l trace-fork-join
complete -c valgrind -l trace-hb
complete -c valgrind -l trace-mutex
complete -c valgrind -l trace-rwlock
complete -c valgrind -l trace-semaphore
complete -c valgrind -l heap
complete -c valgrind -l heap-admin
complete -c valgrind -l stacks
complete -c valgrind -o px-default -l px-file-backed
complete -c valgrind -l pages-as-heap
complete -c valgrind -l depth
complete -c valgrind -l alloc-fn
complete -c valgrind -l ignore-fn
complete -c valgrind -l threshold
complete -c valgrind -l peak-inaccuracy
complete -c valgrind -l time-unit
complete -c valgrind -l detailed-freq
complete -c valgrind -l max-snapshots
complete -c valgrind -l massif-out-file
complete -c valgrind -l bb-out-file
complete -c valgrind -l pc-out-file
complete -c valgrind -l interval-size
complete -c valgrind -l instr-count-only
complete -c valgrind -l basic-counts
complete -c valgrind -l fnname -d 'option (the default is main)'
complete -c valgrind -l detailed-counts
complete -c valgrind -l trace-mem
complete -c valgrind -l trace-superblocks

