# vendstat
# Autogenerated from man page /usr/share/man/man8/vendstat.8.gz
complete -c vendstat -s N -d 'show IS3 or IS4 general information'
complete -c vendstat -s w -d 'show IS3 port xmit wait counters'
complete -c vendstat -s i -d 'show IS4 counter group info'
complete -c vendstat -s c -d 'configure IS4 counter groups. sp Configure IS4 counter groups 0 and 1'
complete -c vendstat -s R -l Read -d 'Read configuration space record at addr'
complete -c vendstat -s W -l Write -d 'Write configuration space record at addr'
complete -c vendstat -s d -d 'raise the IB debugging level.  May be used several times (-ddd or -d -d -d)'
complete -c vendstat -s e -d 'show send and receive errors (timeouts and others)'
complete -c vendstat -s v -l verbose -d 'increase the application verbosity level'
complete -c vendstat -s G -l Guid
complete -c vendstat -s L -l Lid
complete -c vendstat -s s -l sm_port -d 'Port Selection flags'
complete -c vendstat -s C -l Ca
complete -c vendstat -s P -l Port -d 'Local port Selection'
complete -c vendstat -s h -l help
complete -c vendstat -s V -l version -d 'Configuration flags'
complete -c vendstat -s t -l timeout
complete -c vendstat -l config -s z -d 'Default: /etc/infiniband-diags/ibdiag. conf FILES CONFIG FILE'

