# veritysetup
# Autogenerated from man page /usr/share/man/man8/veritysetup.8.gz
complete -c veritysetup -l batch-mode -s q
complete -c veritysetup -l cancel-deferred
complete -c veritysetup -l check-at-most-once
complete -c veritysetup -l data-blocks
complete -c veritysetup -l data-block-size
complete -c veritysetup -l debug
complete -c veritysetup -l deferred
complete -c veritysetup -l error-as-corruption
complete -c veritysetup -l fec-device
complete -c veritysetup -l fec-offset
complete -c veritysetup -l fec-roots
complete -c veritysetup -l format
complete -c veritysetup -l hash
complete -c veritysetup -l hash-block-size
complete -c veritysetup -l hash-offset
complete -c veritysetup -l help -s '?'
complete -c veritysetup -l ignore-corruption -l restart-on-corruption -l panic-on-corruption
complete -c veritysetup -l ignore-zero-blocks
complete -c veritysetup -l no-superblock
complete -c veritysetup -l root-hash-file
complete -c veritysetup -l root-hash-signature
complete -c veritysetup -l salt
complete -c veritysetup -l shared
complete -c veritysetup -l usage
complete -c veritysetup -l use-tasklets
complete -c veritysetup -l uuid
complete -c veritysetup -l verbose -s v
complete -c veritysetup -l version -s V

