# vgchange
# Autogenerated from man page /usr/share/man/man8/vgchange.8.gz
complete -c vgchange -l persist -d ']'
complete -c vgchange -l poll -d 'vgchange/lvchange skip autoactivation, and defer to pvscan autoactivation'

