# vimtutor
# Autogenerated from man page /usr/share/man/man1/vimtutor.1.gz
complete -c vimtutor -s l -l languageISO639 -d 'Set the two or three letter language code.  E. g.  \'it\', \'es\', \'bar\''
complete -c vimtutor -s c -l chapterNUMBER -d 'Set the chapter number.  Defaults to chapter one'
complete -c vimtutor -s g -l gui -d 'Start  vimtutor in the GUI version of vim if available, otherwise fallback to…'
complete -c vimtutor -s h -l help -d 'Display usage information'
complete -c vimtutor -l language -d 'Set the two or three letter language code.  E. g.  \'it\', \'es\', \'bar\''
complete -c vimtutor -l chapter -d 'Set the chapter number.  Defaults to chapter one'
complete -c vimtutor -l list -d 'Display chapters and languages'

