# wifidump
# Autogenerated from man page /usr/share/man/man1/wifidump.1.gz
complete -c wifidump -l help
complete -c wifidump -l version
complete -c wifidump -l extcap-interfaces
complete -c wifidump -l extcap-interface
complete -c wifidump -l extcap-dlts
complete -c wifidump -l extcap-config
complete -c wifidump -l capture
complete -c wifidump -l fifo
complete -c wifidump -l remote-host
complete -c wifidump -l remote-port
complete -c wifidump -l remote-username
complete -c wifidump -l remote-password
complete -c wifidump -l sshkey
complete -c wifidump -l remote-interface
complete -c wifidump -l remote-channel-frequency
complete -c wifidump -l remote-channel-width
complete -c wifidump -l extcap-capture-filter

