# winetricks
# Autogenerated from man page /usr/share/man/man1/winetricks.1.gz
complete -c winetricks -l country -d 'Set country code to CC and don\'t detect your IP address when retrying downloa…'
complete -c winetricks -s f -l force -d 'Don\'t check whether packages were already installed'
complete -c winetricks -l gui -d 'Show GUI diagnostics even when driven by the command-line interface'
complete -c winetricks -l isolate -d 'Install each app or game in its own bottle'
complete -c winetricks -l self-update -d 'Update this application to the last version'
complete -c winetricks -l update-rollback -d 'Rollback the last self update'
complete -c winetricks -l no-isolate -d 'Don\'t install each app or game in its own bottle (default)'
complete -c winetricks -l no-clean -d 'Don\'t delete temp directories (useful during debugging)'
complete -c winetricks -l optin -d 'Opt in to reporting which verbs you use to the Winetricks maintainers'
complete -c winetricks -l optout -d 'Opt out of reporting which verbs you use to the Winetricks maintainers'
complete -c winetricks -s q -l unattended -d 'Don\'t ask any questions, just install automatically'
complete -c winetricks -s t -l torify -d 'Run downloads under torify, if available'
complete -c winetricks -s v -l verbose -d 'Echo all commands as they are executed'
complete -c winetricks -l verify -d 'Run (automated) GUI tests for verbs, if available'
complete -c winetricks -s h -l help -d 'Display this message and exit'
complete -c winetricks -s V -l version -d 'Display version and exit'

