# wtype
# Autogenerated from man page /usr/share/man/man1/wtype.1.gz
complete -c wtype -o MMOD -d 'Press modifier MOD'
complete -c wtype -o mMOD -d 'Release modifier MOD'
complete -c wtype -o PKEY -d 'Press key KEY'
complete -c wtype -o pKEY -d 'Release key KEY'
complete -c wtype -o kKEY -d 'Type (press and release) key KEY'
complete -c wtype -o dTIME -d 'Sleep for TIME milliseconds between keystrokes when typing texts'
complete -c wtype -o sTIME -d 'Sleep for TIME milliseconds before interpreting the following options'
complete -c wtype -s M -d 'Press modifier MOD'
complete -c wtype -s m -d 'Release modifier MOD'
complete -c wtype -s P -d 'Press key KEY'
complete -c wtype -s p -d 'Release key KEY'
complete -c wtype -s k -d 'Type (press and release) key KEY'
complete -c wtype -s d -d 'Sleep for TIME milliseconds between keystrokes when typing texts'
complete -c wtype -s s -d 'Sleep for TIME milliseconds before interpreting the following options'

