# xfs_property
# Autogenerated from man page /usr/share/man/man8/xfs_property.8.gz
complete -c xfs_property -s V -d 'Print the version number and exits'
complete -c xfs_property -s v -d 'flag is specified, prints the values as well'

