# xfs_scrub_all
# Autogenerated from man page /usr/share/man/man8/xfs_scrub_all.8.gz
complete -c xfs_scrub_all -l auto-media-scan-interval -d 'Automatically enable the file data scan (i. e'
complete -c xfs_scrub_all -l auto-media-scan-stamp -d 'Path to a file that will record the last time the media scan was run'
complete -c xfs_scrub_all -s h -d 'Display help'
complete -c xfs_scrub_all -s x -d 'Read all file data extents to look for disk errors'
complete -c xfs_scrub_all -s V -d 'Prints the version number and exits'

