# xgpsspeed
# Autogenerated from man page /usr/share/man/man1/xgpsspeed.1.gz
complete -c xgpsspeed -s '?' -s h -l help
complete -c xgpsspeed -o device
complete -c xgpsspeed -s D -l debug
complete -c xgpsspeed -l host
complete -c xgpsspeed -s p -l port
complete -c xgpsspeed -s V -l version

