# xgps
# Autogenerated from man page /usr/share/man/man1/xgps.1.gz
complete -c xgps -s '?' -s h -l help
complete -c xgps -o device
complete -c xgps -s D -l debug
complete -c xgps -l host
complete -c xgps -s l -l llfmt
complete -c xgps -s p -l port
complete -c xgps -s r -l rotate
complete -c xgps -s c -l const
complete -c xgps -s V -l version

