# xkbcli-interactive-x11
# Autogenerated from man page /usr/share/man/man1/xkbcli-interactive-x11.1.gz
complete -c xkbcli-interactive-x11 -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-interactive-x11 -o '\\-local\\-state' -d 'Enable local state handling and ignore modifiers/layouts state updates from t…'
complete -c xkbcli-interactive-x11 -o '\\-keymap' -d 'Load the XKB keymap from a file instead of the keymap from the compositor'
complete -c xkbcli-interactive-x11 -o '\\-format' -d 'Specify the keymap format (numeric or label, e. g. \\& v1 )'
complete -c xkbcli-interactive-x11 -o '\\-enable\\-compose' -d 'Enable Compose functionality'
complete -c xkbcli-interactive-x11 -o '\\-verbose' -d 'Enable verbose debugging output'
complete -c xkbcli-interactive-x11 -s 1 -d 'Enable uniline event output'
complete -c xkbcli-interactive-x11 -o '\\-multiline' -d 'Enable multiline event output El SEE ALSO xkbcli 1, xkbcli\\-interactive\\-evde…'

