# xkbcli-dump-keymap-x11
# Autogenerated from man page /usr/share/man/man1/xkbcli-dump-keymap-x11.1.gz
complete -c xkbcli-dump-keymap-x11 -o '\\-format' -d 'Specify the keymap format (numeric or label, e. g. \\& v1 )'
complete -c xkbcli-dump-keymap-x11 -o '\\-no\\-pretty' -d 'Disable pretty-printing for keymap serialization'
complete -c xkbcli-dump-keymap-x11 -o '\\-drop\\-unused' -d 'Disable unused bits serialization'
complete -c xkbcli-dump-keymap-x11 -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-dump-keymap-x11 -o '\\-verbose' -d 'Enable verbose debugging output El SEE ALSO xkbcli 1, xkbcli\\-interactive\\-x1…'

