# xkbcli-how-to-type
# Autogenerated from man page /usr/share/man/man1/xkbcli-how-to-type.1.gz
complete -c xkbcli-how-to-type -o '\\-keysym' -d 'Treat the argument as only as a keysym'
complete -c xkbcli-how-to-type -o '\\-disable\\-compose' -d 'Disable Compose support'
complete -c xkbcli-how-to-type -o '\\-format' -d 'Specify the keymap format (numeric or label, e. g. \\& v1 )'
complete -c xkbcli-how-to-type -o '\\-keymap' -d 'Load the XKB keymap from a file, ignore RMLVO options'
complete -c xkbcli-how-to-type -o '\\-rules' -d 'The XKB ruleset'
complete -c xkbcli-how-to-type -o '\\-model' -d 'The XKB model'
complete -c xkbcli-how-to-type -o '\\-layout' -d 'The XKB layout'
complete -c xkbcli-how-to-type -o '\\-variant' -d 'The XKB layout variant'
complete -c xkbcli-how-to-type -o '\\-options' -d 'The XKB options'
complete -c xkbcli-how-to-type -o '\\-enable\\-environment\\-names' -d 'Allow to set the default RMLVO values via the following environment variables…'
complete -c xkbcli-how-to-type -o '\\-verbose' -d 'Enable verbose debugging output'
complete -c xkbcli-how-to-type -o '\\-help' -d 'Print a help message and exit.  El SEE ALSO xkbcli 1, https://xkbcommon'

