# xkbcli-dump-keymap-wayland
# Autogenerated from man page /usr/share/man/man1/xkbcli-dump-keymap-wayland.1.gz
complete -c xkbcli-dump-keymap-wayland -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-dump-keymap-wayland -o '\\-verbose' -d 'Enable verbose debugging output'
complete -c xkbcli-dump-keymap-wayland -o '\\-input\\-format' -d 'The keymap format (numeric or label, e. g. \\& v1 ) for parsing'
complete -c xkbcli-dump-keymap-wayland -o '\\-output\\-format' -d 'The keymap format (numeric or label, e. g. \\& v1 ) for serializing'
complete -c xkbcli-dump-keymap-wayland -o '\\-format' -d 'The keymap format (numeric or label, e. g'
complete -c xkbcli-dump-keymap-wayland -o '\\-no\\-pretty' -d 'Disable pretty-printing for keymap serialization'
complete -c xkbcli-dump-keymap-wayland -o '\\-drop\\-unused' -d 'Disable unused bits serialization'
complete -c xkbcli-dump-keymap-wayland -o '\\-raw' -d 'Print the raw keymap, without parsing it'

