# xkbcli-compile-compose
# Autogenerated from man page /usr/share/man/man1/xkbcli-compile-compose.1.gz
complete -c xkbcli-compile-compose -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-compile-compose -o '\\-verbose' -d 'Enable verbose debugging output'
complete -c xkbcli-compile-compose -o '\\-file' -d 'Specify a Compose file to load, or \\- to read the standard input'
complete -c xkbcli-compile-compose -o '\\-locale' -d 'Specify the locale directly, instead of relying on the environment variables …'
complete -c xkbcli-compile-compose -o '\\-test' -d 'Test compilation but do not print the Compose file El SEE ALSO xkbcli 1, Comp…'

