# zdump
# Autogenerated from man page /usr/share/man/man8/zdump.8.gz
complete -c zdump -l version -d 'Output version information and exit'
complete -c zdump -l help -d 'Output short usage message and exit'
complete -c zdump -s i -d 'Output a description of time intervals'
complete -c zdump -s v -d 'Output a verbose description of time intervals'
complete -c zdump -s V -d 'Like  -v , except omit output concerning extreme time and year values'
complete -c zdump -s c -d 'Cut off interval output at the given year(s)'
complete -c zdump -o 500
complete -c zdump -s t -d 'Cut off interval output at the given time(s), given in decimal seconds since …'
complete -c zdump -o '	-	-103126	LMT' -d '1896-01-13	12:01:26	-1030	HST 1933-04-30	03	-0930	HDT	1 1933-05-21	11	-1030	H…'
complete -c zdump -o '	-	+031212	LMT' -d '1924-04-30	23:47:48	+03 1930-06-21	01	+04 1981-04-01	01	+05		1 1981-09-30	23	…'

