# zerk
# Autogenerated from man page /usr/share/man/man1/zerk.1.gz
complete -c zerk -s '?' -s h
complete -c zerk -s c
complete -c zerk -s d
complete -c zerk -s e
complete -c zerk -s f
complete -c zerk -s O
complete -c zerk -s p
complete -c zerk -s r
complete -c zerk -s R
complete -c zerk -s S
complete -c zerk -s s
complete -c zerk -s V
complete -c zerk -s v
complete -c zerk -s W
complete -c zerk -s w

